### ISSUE TITLE
Decide how to modify ScubaGear so that it shows the source line where errors occur

### ISSUE THREAD

**Issue by tkol2022** [cisagov/ScubaGear#1005]
# 💡 Summary #

While working on an AAD enhancement it came to my attention that ScubaGear does not show the source line / cmdlet when errors occur, at least in certain scenarios. This makes it challenging to debug what the problem is. In the screenshot below it shows me that there was a permissions problem but did not indicate where the problem was. I ended up having to run the debugger on the code and step through line by line until I found the cmdlet that produced the permissions error. Not only is this tedious, in many cases we don't have the luxury of stepping through the code (e.g. when a user reports a bug or when an automated process fails).

The scope of this issue is to come up with some alternatives, discuss them with the team and gain consensus, then prototype one or more of the ideas. Actually fixing ScubaGear will be put into a separate issue.

![image](https://github.com/cisagov/ScubaGear/assets/107076927/cc93624e-94b3-4096-9ce0-316e95b824c0)

## Overarching goals of standardized error message printing
- Make sure error messages print the stack trace so that we can troubleshoot when problems occur.
- Make sure the stack trace indicates the correct line where the error occurred. See example in comment below where the catch block inside the Invoke-ProviderList prints the wrong source lines.
- Make sure the error handling logic correctly aborts execution under export provider failures. For example, right now the orchestrator continues to run additional logic if Export-AADProvider fails, which might not make sense.

## Implementation notes ##

- [x] Determine the root cause of the error suppression.
- [x] Discuss with the team about implementation alternatives to rectify the suppression.
- [x] Create a separate issue to implement one of the alternatives once there is consensus.
- [x] Ted publish the throw statements that help simulate errors at various junctures in the code
- [x] Alex publish the prototype code branch which contains his new function to standardizing the printing of errors

**Comment by tkol2022** [comment]
> @tkol2022 Can we split this into an exploratory issue first to determine ways to address and then a separate issue to implement the chosen approach?

updated

**Comment by james-garriss** [comment]
Just to clarify, add those lines *in a catch block*.

```
try {
  <do something that can throw an exception>
}
catch {
  Write-Warning $_.ScriptStackTrace
  Write-Warning $_.Exception
  Write-Warning $_.ErrorDetails
  <do something to handle the exception>
}

**Comment by tkol2022** [comment]
@schrolla I would like to reconsider the priority on this one to high. I was working on some AAD code today and the fact that the TryCommand() function replaces the source error with a generic one made it more challenging to debug. I had to step through the code versus having the actual error I might have been able to determine root cause much quicker.

**Comment by tkol2022** [comment]
### Recent discussion summary
I met with Alex on Friday 9/27 and we went through numerous aspects of the issue. Alex showed me a new sample function that he developed which prints out error messages in a standard format including the stacktrace which is currently missing from ScubaGear and is critical when we conduct troubleshooting. I went through numerous try catch blocks in the code that currently have different error messages outputs and I demonstrated a simulation of errors at various locations. Here is a summary of the meetings and other information related to this issue.

#### Action Items

- [ ] Ted publish the throw statements that help simulate errors at various junctures in the code
- [ ] Ted create new issue to codify the error message enhancement into ScubaGear
- [ ] Alex publish the prototype code branch which contains his new function to standardizing the printing of errors

#### Reproducing the current problem due to incorrect or missing stacktrace. This is just a demonstration of one problem. There are others.

1. Simulate an error condition inside of Export-AADProvider by adding a throw statement somewhere inside the provider processing logic. Add the statement below.

`throw "Ted's random AAD error"`

What happens?
I see two error messages and a warning message. The first error message is below. The **line number** where the error occurred **is Wrong**.
`"Invoke-ProviderList : Error with the AAD Provider. See the exception message for more details:  Ted's random AAD error" At C:\Users\tkolovos\Downloads\ScubaGear-errormessages\PowerShell\ScubaGear\Modules\Orchestrator.psm1:372
`

Then I get the message `"WARNING: aad will be omitted from the output because of the failure above"`

Then I get the error message below.
`"All indicated Product Providers failed to execute; aborting ScubaGear execution."
`
#### Questions to the ScubaGear team

- In TryCommand the error messages are printed using **Write-Warning**. Should they be **Write-Error** instead since the errors can indicate a problem evaluating one or more policies?

- After line 600 in Orchestrator, why does the orchestrator continue if there was a failure when calling the Export-AADProvider or similar provider functions? After line 600 the orchestrator is trying to manipulate the provider JSON. Not sure it makes sense to do that if exporting failed?

**Comment by amart241** [comment]
From Parking Lot and discussions we have decided on a way forward. Should be ready to close.
