### ISSUE TITLE
CSV should Include the Requirement from the Report.

### ISSUE THREAD

**Issue by wingcomm** [cisagov/ScubaGear#1015]
# 💡 Summary #

We would like to see the requirement field (highlighted in red) incorporated into the TestResutlts.csv output to make it more readable/useful. 

![Screenshot 2024-03-21 at 2 45 28 AM](https://github.com/cisagov/ScubaGear/assets/9159510/77a314f5-843e-4c51-9dfe-4cbd1badfa16)

## Motivation and context ##

To make the tool more useful.

This would be useful because...

It make the CSV more readable with important context about what items passed/failed.

Please provide details for implementation, such as:

Add a "Requirement" column to the TestResults.csv and include the requirement text for each finding like the screenshot above.

**Comment by gdasher** [comment]
In #970 we added support for a consolidated JSON output (ScubaResults.json).  This will be available in the upcoming release and it includes the Requirement text.

We will look at updating the TestResults.csv to include this info in the future, but I wanted to flag that as you may be able to take advantage of it when that release comes out.

**Comment by adhilto** [comment]
@wingcomm thanks for the feedback. I've created a new issue that tracks this as well as a few other csv enhancements: https://github.com/cisagov/ScubaGear/issues/1026. Closing this issue, refer to the new issue for updates.
