### ISSUE TITLE
Add Functional Tests for AAD 3.3v1

### ISSUE THREAD

**Issue by ssatyapal123** [cisagov/ScubaGear#1017]
# 💡 Summary #
To fully close issue #410, need to complete the functional test cases to improve automated testing features.
What is the work, as a high-level summary?

## Motivation and context ##

MS.AAD.3.3v1 requires checks on the Microsoft Authenticator MFA login user context settings to help protect the tenant when phishing resistant MFA has not been enforced and Microsoft Authenticator is used. The functional unit tests should check for various combinations of these settings to ensure that pass/fail conditions are being successfully met by the Rego code.

## Implementation notes ##
Run Functional Unit Tests

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Functional tests are passing

**Comment by tkol2022** [comment]
Was completed as part of PR #1014
