### ISSUE TITLE
Fix Markdown in readme

### ISSUE THREAD

**Issue by james-garriss** [cisagov/ScubaGear#1021]
# 🐛 Summary #

There's invalid Markdown in the readme that's causing GitHub Pages to render incorrectly.

## To reproduce ##

Go to https://cisagov.github.io/ScubaGear/
Look at the section titled "User Permissions"

## Expected behavior ##

I expect everything to look perfect.

**Comment by mitchelbaker-cisa** [comment]
For the table rendering incorrectly this may be the culprit? https://github.com/orgs/community/discussions/23945
