### ISSUE TITLE
Bug with MS.AAD.5.2v1 - "Only administrators SHALL be allowed to consent to applications."

### ISSUE THREAD

**Issue by sgendron50** [cisagov/ScubaGear#1022]
# 🐛 Summary #

What's wrong? Please be specific.

In the report, MS.AAD.5.2v1 is displaying "Fail", however, I've verified in Azure Portal --> Enterprise Apps --> Consent & Permissions, that "User consent for applications" is set to "Do not allow user consent". I've flipped it on and off, and ran the report again, but it still fails with: 

1 authorization policies found that allow non-admin users to consent to third-party applications:
authorizationPolicy

Invoke-SCuBA -ProductNames aad

## Expected behavior ##

I expected that 5.2 would pass.

## Any helpful log output or screenshots ##

Paste the results here:

```console

```

Add any screenshots of the problem here.

**Comment by tkol2022** [comment]
@sgendron50 Thanks for reporting this. We are starting to see if we can re-produce it. @dagarwal-mitre 

- What type of tenant license do you have? E5, G5, G3, etc. 
- Is this a new problem?
- Do you see any error messages in the terminal when running ScubaGear?

**Comment by sgendron50** [comment]
@tkol2022 - We have an E5 license. I can't tell you if this is a new problem because we just used this for the first time. No, no error messages were displayed in the terminal. Let me know if there is anything else I can provide to assist.

**Comment by amandaw33** [comment]
We similarly hit this and similarly to @sgendron50 in Entra we do have user consent disabled, but over in admin center --> settings --> org settings --> services --> user consent to apps is checked, but I get an error trying to uncheck it (I thought I'd uncheck it to just stay consistent).  "We couldn't save your changes. Close and reopen this setting to try again"

Googling hasn't led me to how this setting interacts or may be overridden by the Entra setting.

**Comment by DanielWahlgren** [comment]
We hit it aswell, and just started using it, so can't tell if it is new or not. We have E5 licenses, and have configured the settings seemingly correct in Entra. We were also unable to disable the setting in admin center like @amandaw33 pointed out.

Thank you for making this tool avaliable to the public.

**Comment by tkol2022** [comment]
> We hit it aswell, and just started using it, so can't tell if it is new or not. We have E5 licenses, and have configured the settings seemingly correct in Entra. We were also unable to disable the setting in admin center like @amandaw33 pointed out.
> 
> Thank you for making this tool avaliable to the public.

Happy to know that people are using it! Appreciate the feedback.

**Comment by tkol2022** [comment]
FYI - The fix for this has been merged into the main branch. You can download the zip file from main if you want to test it - see screenshot below. It will also be included in our upcoming official release bundle.

![image](https://github.com/cisagov/ScubaGear/assets/107076927/a7943a47-3617-4238-bfc9-d0fc7ea37737)
