### ISSUE TITLE
Make Invoke-ScubaCached backwards compatible with ScubaResults.json

### ISSUE THREAD

**Issue by buidav** [cisagov/ScubaGear#1023]
# 💡 Summary #

RunCached is a messy function that violates several different  programming principles but was created to do some neat little ScubaGear tricks. 
Following in the same spirit, this issue is to add functionality to ScubaCached to be able to convert `ProviderSettingsExport.json` to `ScubaResults.json` format.  See #970 for specifics on the ScubaResults.json

## Motivation and context ##

For our own internal use.

## Implementation notes ##
Modification of ScubaCached with the `-MergeJson` parameter.

## Acceptance criteria ##

When we are able to convert `ProviderSettingsExport.json` to `ScubaResults.json` on demand.

**Comment by adhilto** [comment]
Adding this to the orchestrator seems to do the trick:
![image](https://github.com/cisagov/ScubaGear/assets/106177711/f260d69e-251a-40bd-99a7-4ab9ec1186b5)
