### ISSUE TITLE
Functional test for MS.AAD.5.3v1 is showing inconsistent results for G5 vs E5 tenants.

### ISSUE THREAD

**Issue by nanda-katikaneni** [cisagov/ScubaGear#1024]
# 🐛 Summary #

This issue found through nightly functional tests: complaint test case for MS.AAD.5.3v1 on G5 tenant is failing (indicating ScubaGear showing incorrect result when tenant is in complaint with SCB.) The same test run against E5 tenant is passing the functional test. Note that this test is run in the runcached mode. 

Test results on E5 tenant - showing all 5.3 test cases passing:
Running tests from 'Products.Tests.ps1'
Describing Policy Checks for aad
 Context Start tests for policy MS.AAD.5.3v1
  Context Execute test, MS.AAD.5.3v1 Non-Compliant case - No Admin Consent workflow configured
VERBOSE: Download the right chromedriver from 'http://chromedriver.chromium.org/downloads'
    [+] Check test case results 126.66s (126.55s|114ms)
  Context Execute test, MS.AAD.5.3v1 Non-Compliant case - No Admin Consent workflow configured false
VERBOSE: Download the right chromedriver from 'http://chromedriver.chromium.org/downloads'
    [+] Check test case results 39.56s (39.55s|7ms)
  Context Execute test, MS.AAD.5.3v1 Compliant case - Admin Consent workflow is configured true
VERBOSE: Download the right chromedriver from 'http://chromedriver.chromium.org/downloads'
    [+] Check test case results 24.33s (24.32s|4ms)
Tests completed in 198.26s
Tests Passed: 3, Failed: 0, Skipped: 0 NotRun: 51

Test results on G5 tenant - showing the failure for the complaint test case:
Running tests from 'Products.Tests.ps1'
Describing Policy Checks for aad
 Context Start tests for policy MS.AAD.5.3v1
  Context Execute test, MS.AAD.5.3v1 Non-Compliant case - No Admin Consent workflow configured
VERBOSE: Download the right chromedriver from 'http://chromedriver.chromium.org/downloads'
    [+] Check test case results 33.75s (33.73s|18ms)
  Context Execute test, MS.AAD.5.3v1 Non-Compliant case - No Admin Consent workflow configured false
VERBOSE: Download the right chromedriver from 'http://chromedriver.chromium.org/downloads'
    [+] Check test case results 32.74s (32.74s|5ms)
  Context Execute test, MS.AAD.5.3v1 Compliant case - Admin Consent workflow is configured true
VERBOSE: Download the right chromedriver from 'http://chromedriver.chromium.org/downloads'
    [-] Check test case results 31.64s (31.63s|6ms)
     Expected $true, but got $false.
     at $PolicyResultObj.RequirementMet | Should -Be $ExpectedResult, C:\Users\NKATIKANENI\ScubaGear-Flipper\ScubaGear\Testing\Functional\Products\Products.Tests.ps1:282
     at <ScriptBlock>, C:\Users\NKATIKANENI\ScubaGear-Flipper\ScubaGear\Testing\Functional\Products\Products.Tests.ps1:282
Tests completed in 100.11s
Tests Passed: 2, Failed: 1, Skipped: 0 NotRun: 51

## To reproduce ##

1. Run AAD functional test plan against a g5 tenant and a e5 tenant
2. Observe the test results for MS.AAD.5.3v1

## Expected behavior ##

The functional test suite of AAD should pass all test cases for all tenant types including G5, E5 etc.

**Comment by tkol2022** [comment]
### Problem identified
The problem was that the functional test case was modifying the [0] element in the directory_settings array in the JSON for the functional test case. In the G5 tenant that produced two elements [0] and [1] with the same field name (EnableAdminConsentRequests) duplicated and therefore this was throwing off the Rego. I fixed the functional test case by ensuring that it only creates a single element. See the before and after screenshots below.

Before:
![image](https://github.com/cisagov/ScubaGear/assets/107076927/d8a763da-45e8-420f-82e0-00386034a64d)


After:
![image](https://github.com/cisagov/ScubaGear/assets/107076927/ba4265cf-2960-4186-96c5-2c655d2e4b5d)
