### ISSUE TITLE
Enhance csv version of output

### ISSUE THREAD

**Issue by adhilto** [cisagov/ScubaGear#1026]
# 💡 Summary #
Enhance the csv output to include details such as the requirement text and result values. Basically, make it a csv version of the reports.

## Motivation and context ##
While ScubaGear does output a csv version of the output, this functionality has not been updated in some time and does not include several enhancements that have been made. For example, it does not include the requirement text (#1015) or the "Result" value.

This would allow people to access their results in a machine-readable format or port their results to Excel spreadsheets.

## Implementation notes ##
PR #970 created a json version of the output. The easiest way to implement the csv enhancement would probably be to convert the ScubaResults.json "Results" key into a csv.

## Acceptance criteria ##
- [ ] A csv version of the output is available

**Comment by james-garriss** [comment]
> The easiest way to implement the csv enhancement would probably be to convert the ScubaResults.json "Results" key into a csv.

Almost.

The easiest way to implement the csv enhancement would probably be to allow any downstream system to convert the ScubaResults.json "Results" key into a csv.

FTFY.
