### ISSUE TITLE
Azure AD Functional Testing

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#1033]
# 💡 Summary #

As part of Glacier release, to ensure that the tool's update is accurate, detailed functional testing has been planned. Each policy will be functionally tested to check that all pass/fail scenarios have been correctly processed by the tool using existing automated functional test plans.

This issue functionally tests each policy of Azure AD product of ScubaGear tool. The main objective is to test Azure AD policies and ensure that ScubaGear tool is providing the correct result for each possible configuration option. 

## Motivation and context ##
This functional testing ensures that ScubaGear results of pass/fail are accurate based on the latest version of the code.

## Implementation notes ##
For each Azure AD policy do the following:

- [ ] Configure the automated testing and run against each tenant type for which a variant test plan is present.  Run the automated test plans (e.g. regular, g5, etc.) and note the results.
- [ ] For each test failure, investigate and note the cause of the failure and log any new issues needed to resolve

For details on how to use and execute the functional tests, please see #592 or reach out to the dev team via other channels.

## Acceptance criteria ##

- [ ] All existing test plan variants for the product have been successfully run
- [ ] Test plan results have been reviewed and any issues resolved or reported as new issues

**Comment by nanda-katikaneni** [comment]
Ran Functional test suite against G5, E5, G3 tenants - all tests passed (from ScubaGear pov). There is one documentation issue #1044, one functional test issue #1024 and one infrastructure issue on G3 test-tenant - none of these should affect the Glacier release.

**Comment by nanda-katikaneni** [comment]
GccHigh tests are all done with no issues. 
<img width="875" alt="Screenshot 2024-04-04 at 11 26 11 AM" src="https://github.com/cisagov/ScubaGear/assets/104993331/940acf2e-11f0-4491-8e21-c69fe6c8c853">

**Comment by nanda-katikaneni** [comment]
Manual spot check tests on multiple tenants passed - closing this task as completed.
