### ISSUE TITLE
SharePoint/OneDrive Functional Testing

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#1035]
# 💡 Summary #

As part of Glacier release, to ensure that the tool's update is accurate, detailed functional testing has been planned. Each policy will be functionally tested to check that all pass/fail scenarios have been correctly processed by the tool using existing automated functional test plans.

This issue functionally tests each policy of SharePoint/OneDrive product of ScubaGear tool. The main objective is to test SharePoint/OneDrive policies and ensure that ScubaGear tool is providing the correct result for each possible configuration option. 

## Motivation and context ##
This functional testing ensures that ScubaGear results of pass/fail are accurate based on the latest version of the code.

## Implementation notes ##
For each SharePoint/OneDrive policy do the following:

- [x] Configure the automated testing and run against each tenant type for which a variant test plan is present.  Run the automated test plans (e.g. regular, g5, etc.) and note the results.
- [x] For each test failure, investigate and note the cause of the failure and log any new issues needed to resolve

For details on how to use and execute the functional tests, please see #592 or reach out to the dev team via other channels.

## Acceptance criteria ##

- [x] All existing test plan variants for the product have been successfully run
- [x] Test plan results have been reviewed and any issues resolved or reported as new issues

**Comment by Sloane4** [comment]
# SharePoint ran clean on all tenants

## E5
### PNP
![image](https://github.com/cisagov/ScubaGear/assets/47129205/a704ed77-7ff6-4b2e-82e7-d0db7870f08a)

### SPO


## G5
### PNP
![image](https://github.com/cisagov/ScubaGear/assets/47129205/a13283bb-804e-4640-a121-7cb2cc5b1d9d)

### SPO



## GCC HIGH
### PNP


### SPO


## G3
### PNP


### SPO
