### ISSUE TITLE
Modify Sharepoint so that the policies only execute when applicable and produce a consistent N/A message

### ISSUE THREAD

**Issue by tkol2022** [cisagov/ScubaGear#1064]
# 💡 Summary #

Several of the Sharepoint Rego policies are implemented to execute even under circumstances when they are not applicable. The code should be modified to rectify this. For example, policy 3.2 should only be evaluated when the external sharing slider is set to the value Anyone (i.e. anyone links is turned on) - otherwise the report should produce an N/A. Another way to think about this is, if an organization is not using Anyone links, then ScubaGear shouldn't be checking the security configurations for anyone links because it produces inconsistent results - we have had publicly reported issues on this topic. Sections 1 and 3 of the Sharepoint baseline contain policies that fall within the scope of this epic.

A second item that this epic should address is making sure that the output in the report accurately reflects whether a policy was evaluated or not. If a policy was not evaluated, the report should produce an N/A - currently it produces a Pass which incorrectly implies that the policy configuration was checked. We have started making changes to AAD to better handle N/A cases and therefore Sharepoint should be consistent. Since there are open bug reports on these issues, it makes sense to address the N/A problem as the bugs are fixed.

Section 3 issues included:
- #950 (policy 3.3)
- #951 (policy 3.2)
- #952 (policy 3.1)

Section 1 issues:
- #1062 (policies 1.3 and 1.4)

## Implementation notes ##

- [x] Implement the issues noted above

**Comment by tkol2022** [comment]
The reason I placed this into Halibut is that all of the issues have the same general implementation logic to correct the deficiencies so it might make the most sense to code them together.

**Comment by Sloane4** [comment]
Closing as al issues addressed
