### ISSUE TITLE
Clean up sample config files

### ISSUE THREAD

**Issue by james-garriss** [cisagov/ScubaGear#1075]
# 💡 Summary #

What is the work, as a high-level summary?  Cleaning up the sample config files.

## Motivation and context ##

The sample config files are located [here](https://github.com/cisagov/ScubaGear/tree/main/PowerShell/ScubaGear/Sample-Config-Files).  If you look in the one for [AAD](https://github.com/cisagov/ScubaGear/blob/main/PowerShell/ScubaGear/Sample-Config-Files/aad-config.yaml) as one example, there are comments for adding config parameters for SharePoint and Teams.  Someone needs to walk through all the config files and clean out all the debris that has gathered over the years.

This would be useful because cluttered and confusing config files are cluttered and confusing.

## Implementation notes ##

Please provide details for implementation, such as:

- Look at each sample config file.
- Remove any debris.
- Fix any issues.
- Improve the description.
- Add many helpful comments.
- Test ScubaGear using each of the config files and ensure everything is working.

## Acceptance criteria ##

How do we know when this work is done?

- [ ] The config files are clean and work as expected.

**Comment by tkol2022** [comment]
@amart241 Here is the updated list of policies that support exclusions for Entra ID in the config file. I just updated the documentation branch that James is working on with this information as well.

![image](https://github.com/cisagov/ScubaGear/assets/107076927/f2e9805d-8beb-460b-a45f-bd358db308b2)
