### ISSUE TITLE
None of the Microsoft.Graph.Beta cmdlets work in GCC High

### ISSUE THREAD

**Issue by wheelerk** [cisagov/ScubaGear#1086]
# 🐛 Summary #

What's wrong? Please be specific.
The Get-MgBeta cmdlets do not work in GCC High.  I think there was a change several weeks ago where the cmdlets were moved out of Beta if that is such a thing.  If I change the scripts to install and import the production graph modules this resolves the issue for all of the cmdlets except the Get-MgDirectorySettings.  I now get the following warning message.  "WARNING: Error running Get-MgDirectorySetting. The term 'Get-MgDirectorySetting' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."

## To reproduce ##

1. Do this
1. Then this

## Expected behavior ##

What did you expect to happen that didn't?

## Any helpful log output or screenshots ##

Paste the results here:

```console

```

Add any screenshots of the problem here.

**Comment by wheelerk** [comment]
ScubaGear version 1.2.0.  I'll give this ago again Monday.  I'll remove and reinstall the Microsoft Beta modules again.  Are you running Scuba from an admin or non admin powershell?  Thanks.

**Comment by wheelerk** [comment]
> Invoke-SCuBA -M365Environment gcchigh

Well it looks like the device I was using actually didn't have all the beta modules installed.  Thanks for pointing me in the right direction. :-)  I got a pretty clean run this time.  The report showed 6 Exchange errors.  Get-ScubaSpfRecord, Get-ScubaDkimRecord and 4 Get-ScubaDmarcRecord did not execute successfully.

**Comment by gdasher** [comment]
Feel free to file a separate issue for the failures with errors and we can take a look.  We'll go ahead and close this one.  

Sometimes we get errors on those in organizations using split horizon DNS, especially if certain fallbacks are blocked.
