### ISSUE TITLE
Issues with sharepoint authentication please help

### ISSUE THREAD

**Issue by ghost** [cisagov/ScubaGear#1101]
PS C:\Netsmart\Scuba\ScubaGear-1.2.0\ScubaGear-1.2.0\PowerShell\ScubaGear> Invoke-SCuBA -ProductNames sharepoint
Connect-Tenant : Error establishing a connection with sharepoint. Object reference not set to an instance of an object.
At C:\Netsmart\Scuba\ScubaGear-1.2.0\ScubaGear-1.2.0\PowerShell\ScubaGear\Modules\Orchestrator.psm1:1175 char:26
+         $AnyFailedAuth = Connect-Tenant @ConnectTenantParams
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Connect-Tenant

WARNING: sharepoint will be omitted from the output because of failed authentication
All indicated Products were unable to authenticate; aborting ScubaGear execution
At C:\Netsmart\Scuba\ScubaGear-1.2.0\ScubaGear-1.2.0\PowerShell\ScubaGear\Modules\Orchestrator.psm1:1210 char:9
+         throw "$($ExceptionMessage); aborting ScubaGear execution"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (All indicated P...aGear execution:String) [], RuntimeException
    + FullyQualifiedErrorId : All indicated Products were unable to authenticate; aborting ScubaGear execution

**Comment by sleggy** [comment]
I'm getting the same error too!

**Comment by sleggy** [comment]
I'm getting the same error and I'm running the versions below with SPO Administrator role.

PSVersion = 5.1.22621.2506
SPO Module Version = 16.0.2451
