### ISSUE TITLE
ExchangeOnlineManagement v3.5.0 fails to connect to Exchange/Defender in non-interactive mode

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#1115]
# 🐛 Summary #

ScubaGear is failing to connect to Exchange and Defenders APIs due to a new bug in the v3.5.0 release of the the Microsoft [ExchangeOnlineManagement](https://www.powershellgallery.com/packages/ExchangeOnlineManagement/) PowerShell module.

Starting last Friday, ScubaGear automated smoke testing started failing to connect to Defender and Exchange.  We isolated the issue to an update of the Microsoft [ExchangeOnlineManagement](https://www.powershellgallery.com/packages/ExchangeOnlineManagement/) PowerShell module which released a new version (3.5.0) on the same day.  Testing showed that using 3.4.0 worked, while using 3.5.0 with no other changes caused ScubaGear to fail when trying to run Connect-ExchangeOnline or Connect-IPPSSession to interact with those services using service principal authentication.  Interactive user auth still works.  

This appears to be a bug in the dependent upstream PowerShell module that ScubaGear relies upon to connect.

## To reproduce ##

The error we receive is shown below after executing the command:

Connect-ExchangeOnline -AppID <app_id> -ShowBanner:$false -CertificateThumbprint <thumbprint> -Organization <org_name>

![Screenshot 2024-05-22 at 4 06 32 PM](https://github.com/cisagov/ScubaGear/assets/108814318/ca18b805-cbf3-4fef-b9e5-c678fd302a00)

This same command and argument set works when the older 3.4.0 version of the module is installed instead.  The change notes for v3.5.0 doesn’t seem to indicate any breaking changes or other updates that would affect a connect.

## Expected behavior ##

We expected the Connect-ExchangeOnline command to complete successfully when given valid service principal credentials on a machine with the references certificate and private key.

## Any helpful log output or screenshots ##

See screenshot inline above.

**Comment by gdasher** [comment]
Have we identified an upstream bug for this issue yet as it appears from what you've posted to be a legitimate bug.
