### ISSUE TITLE
AzureAD Functional Testing

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#1124]
# 💡 Summary #

As part of Halibut release, to ensure that the tool's update is accurate, detailed functional testing has been planned. Each policy will be functionally tested to check that all pass/fail scenarios have been correctly processed by the tool using existing automated functional test plans.

This issue functionally tests each policy of Azure AD product of ScubaGear tool. The main objective is to test Azure AD policies and ensure that ScubaGear tool is providing the correct result for each possible configuration option. 

## Motivation and context ##
This functional testing ensures that ScubaGear results of pass/fail are accurate based on the latest version of the code.

## Implementation notes ##
For each Azure AD policy do the following:

- [x] Configure the automated testing and run against each tenant type for which a variant testplan is present.  Run the automated test plans (e.g. regular, g5, etc.) and note the results.
- [x] For each test failure, investigate and note the cause of the failure and log any new issues needed to resolve

For details on how to use and execute the functional tests, please see the Testing documentation in [Testing/Readme.md](https://github.com/cisagov/ScubaGear/tree/735-FunctionalTests-Documentation/Testing) or reach out to the dev team via other channels.

## Acceptance criteria ##

- [x] All existing test plan variants for the product have been successfully run
- [x] Test plan results have been reviewed and any issues resolved or reported as new issues (Link created issues below)

**Comment by dagarwal-mitre** [comment]
When running the G3 With no variant, the AAD functional test fails for AAD-3.2v1
<img width="805" alt="AAD G3 Error" src="https://github.com/cisagov/ScubaGear/assets/147526644/7fac44ba-c9ad-45d2-ba48-a1e822d3f19c">
<img width="805" alt="AAD G3 (No Variant)" src="https://github.com/cisagov/ScubaGear/assets/147526644/4a63dbfb-a314-4fa0-a51a-2657cd2cfd9a">

**Comment by tkol2022** [comment]
> When running the G3 With no variant, the AAD functional test fails for AAD-3.2v1 @tkol2022 <img alt="AAD G3 Error" width="805" src="https://private-user-images.githubusercontent.com/147526644/336567951-7fac44ba-c9ad-45d2-ba48-a1e822d3f19c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MzI4MDMsIm5iZiI6MTcxNzUzMjUwMywicGF0aCI6Ii8xNDc1MjY2NDQvMzM2NTY3OTUxLTdmYWM0NGJhLWM5YWQtNDVkMi1iYTQ4LWExZTgyMmQzZjE5Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQyMDIxNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNGFkZWFkNzM1OGM0ODBlOTc2NThkYzNiMjdjZDBmYjg0NmQ1YzVlM2ZhZmI1MjY1ZDQ1ZDhjYWFiZWQ2OTFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fuW9T3P8YrknlIY_QbgXXg55W3b2Mh9xCI1SHkUDiFA"> <img alt="AAD G3 (No Variant)" width="805" src="https://private-user-images.githubusercontent.com/147526644/336568347-a85d0b41-1bcf-4b99-8d2b-3ef50bfeb170.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MzI4MDMsIm5iZiI6MTcxNzUzMjUwMywicGF0aCI6Ii8xNDc1MjY2NDQvMzM2NTY4MzQ3LWE4NWQwYjQxLTFiY2YtNGI5OS04ZDJiLTNlZjUwYmZlYjE3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQyMDIxNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNWZiODZmZTQyMWI5ZWVkZTY0OGI0Y2Y2MGQ3OGVlNDA4YTg0YjY4MGE3NDVjNGU0MGEwZmYwNTlkMjQyNjRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5M6K-kDFPSPVKGiWHBZO-v53ek7Z5fqFxooSe01xSX4">

@schrolla @nanda-katikaneni @dagarwal-mitre I investigated this and this specific test scenario failure is to be expected at this time due to reasons that I will explain offline at the stand-up.  The release should not be delayed due to this and this is not a bug in the AAD code.

**Comment by dagarwal-mitre** [comment]
All other AAD functional tests were passed, here are the results:
AAD G5 No Variant:
<img width="959" alt="AAD G5 (No Variant)" src="https://github.com/cisagov/ScubaGear/assets/147526644/413d753b-61fa-4197-bc3e-1ae243b7b9d5">
AAD G5 Variant:
<img width="963" alt="AAD G5" src="https://github.com/cisagov/ScubaGear/assets/147526644/9e33c57a-84ec-4125-ae50-d21b580e5635">
AAD E5 No Variant:
<img width="791" alt="AAD E5 (No Variant)" src="https://github.com/cisagov/ScubaGear/assets/147526644/ffb45baf-4b2d-470b-90b8-fde993ba0992">
AAD E5 Variant:
<img width="801" alt="AAD E5 Variant" src="https://github.com/cisagov/ScubaGear/assets/147526644/b6e653b7-457c-4a2c-81f2-5a2423f69d81">
AAD GCC High No Variant:
<img width="783" alt="AAD GCCHigh (No Variant)" src="https://github.com/cisagov/ScubaGear/assets/147526644/0723dd39-38f7-4e63-b7f5-ce31375baf89">
AAD GCC High Variant:
<img width="769" alt="AAD GCCHigh Variant" src="https://github.com/cisagov/ScubaGear/assets/147526644/41ac96a5-566e-4a48-bb33-1a4ae311e961">
AAD G3 No Variant (error discussed above):
<img width="805" alt="AAD G3 (No Variant)" src="https://github.com/cisagov/ScubaGear/assets/147526644/26a13f07-67bb-4a72-8d7c-dd8ff92f8583">
AAD G3 Variant: 
<img width="793" alt="AAD G3 Variant" src="https://github.com/cisagov/ScubaGear/assets/147526644/94b55ea3-64da-4881-b852-cd92d9e38480">

**Comment by dagarwal-mitre** [comment]
Noticed when running from PSGallery on all products, the links for the baselines document are not working and leading to a file not found, as well as the note within the AAD to the readme
![fc41d28b-39e9-44ed-91d5-3f0ae978f68d](https://github.com/cisagov/ScubaGear/assets/147526644/6365acf4-6b06-4c59-b946-af533abb313e)
<img width="1464" alt="Screenshot 2024-06-05 at 2 57 02 PM" src="https://github.com/cisagov/ScubaGear/assets/147526644/aadac998-a845-43c7-895d-9d424bb87124">
