### ISSUE TITLE
Generate sample reports for Halibut

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#1131]
# 💡 Summary #

After the version bump, generate a new sample report from the latest ScubaGear version and replace the existing sample reports in the repository with them.

## Motivation and context ##

This is useful to ensure that the sample reporting reflects the latest results from the new release of the tool.

## Implementation notes ##

Please provide details for implementation, such as:

- Install the latest pre-release version of ScubaGear on a test machine
- Generate a report against a test tenant using user credentials
- Validate the report results
- Manually sanitize tenant and user details from the JSON, CSV, and HTML reports

## Acceptance criteria ##

How do we know when this work is done?

- [ ] A new sample report reflecting the latest pre-release version is successfully added to the repository
- [x] All tenant and user details have been reviewed and removed or anonymized from the sample report

**Comment by adhilto** [comment]
Would we want to generate the sample data with or without the `MergeJson` flag?

**Comment by adhilto** [comment]
> > Would we want to generate the sample data with or without the `MergeJson` flag?
> 
> That's a good question. I did wonder about the new JSON output, but since we usually generate what an average user would get running plain `Invoke-Scuba` it wouldn't generally be included. Do you think it would be helpful/instructive for the folks that do use that output to have a sample in the repo, @adhilto ?

I think it would be, but I also see the value in having the sample output be what ScubaGear does by default. I personally think the new json output would be valuable for anyone and should eventually be the default, but that's dependent on https://github.com/cisagov/ScubaGear/issues/1023. So...for now maybe we don't include it yet but add it for a later release?
