### ISSUE TITLE
OneDrive 2.3 Baseline policy clarification

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#115]
# 💡 Summary #

Split and clarify the current OneDrive 2.3 baselline v.0.1 policy "Link Permissions SHOULD Be Set to Enabled Anyone Links to View" into two separate policies to make it easier for readers to understand and for automation to report.

## Motivation and context ##

The current baseline policy is a solid best practice, but the wording does not make it clear that there are two separate settings needed to properly protect links:  one to make the default sharing link only be to others within the organization (i.e., not anyone) and a second to make sure when a user does make a link available to anyone that the default permissions on that link are view only.

This would be useful because right now the baseline does reference the Microsoft best practice that includes both settings, but the implementation section 2.3.4 in the baseline itself only shows the setting changes to address the view only portion.  

## Implementation notes ##

Recommended update would be to split this policy into two policies to address both the default link sharing type and the anyone link default permissions.  Both policies would still include references to the same Microsoft best practices document but the implementation details would differ.

The new policies would be something like the following:

2.3  Default Link Sharing Type SHOULD NOT Be Set to Anyone
If Anyone link sharing is enabled, the default when creating a link is set to Anyone.  Providing a more secure default option can mitigate unintentional sharing with unauthenticated anonymous third parties.  To do so, set the default sharing type to be limited to people within your organization instead.

The implementation details would then be as follows:

To set the default file and folder sharing link for the organization:

1. Open the **SharePoint admin center**, and select **Sharing**.
2. Under **File and folder links**, select **Only people in your organization** or **Specific people (only the people the user specifies)**.
3. Select **Save**

2.4 Anyone link permissions SHOULD be Set to View Only

The implementation section would include instructions

1. Open the **SharePoint admin center**.
2. In the left-hand navigation pane, expand **Policies**, then select **Sharing**.
3. Under **Advanced settings for Anyone links**, set the **Files** permissions to **View**.
3. Under **Advanced settings for Anyone links**, set the **Folders** permissions to **View**.

## Acceptance criteria ##

How do we know when this work is done?

- [ ] OneDrive baseline is updated to include split policies
- [ ] Associated automation has been updated to correctly assess and report updated 2.3/2.4 policy states

**Comment by tkol2022** [comment]
Recommend a slight wording on your policy to make it more specific and match the implementation more closely.

Old: "Anyone link permissions SHOULD be Set to View Only"

**Recommended**: "Anyone link permissions SHOULD be Set to View Only for both Files and Folders"

**Comment by tkol2022** [comment]
@schrolla @ethanb-cisa @ahuynhMITRE I do not agree with adding a new policy "Default Link Sharing Type SHOULD NOT Be Set to Anyone" to the OneDrive baseline. This setting is already covered in the Sharepoint code in 2.1 and it checks the value of the field DefaultSharingLinkType which according to Microsoft's documentation, "Lets administrators choose what type of link appears is selected in the "Get a link" sharing dialog box in **OneDrive for Business and SharePoint Online**." I do not think duplicate code is valuable and it creates more maintenance.

**Comment by ethanb-cisa** [comment]
@tkol2022 I think I agree with you. It appears there is no way to use ODB w/o SPO. If you're configuring ODB you'll also configure SPO, so there shouldn't be a gap there.

**Comment by nanda-katikaneni** [comment]
Possibly fixed by #393

**Comment by tkol2022** [comment]
Upon review, I believe this will be addressed by the Sharepoint / OneDrive baseline update. These are two separate policies.
