### ISSUE TITLE
Minor inaccuracy in the MergeJson documentation

### ISSUE THREAD

**Issue by adhilto** [cisagov/ScubaGear#1154]
# 🐛 Summary #
The documentation for [MergeJson](https://github.com/cisagov/ScubaGear/blob/main/docs/configuration/parameters.md#mergejson) states:
> MergeJson combines the JSON files (named TeamsReport.json) in the IndividualReports folder together with the ProviderSettingsExport.json into an uber JSON file. These files are deleted, though the combined report, TestResults.json is not deleted.

However, TestResults.json is the file output by the Rego, not the combined report. The name of the combined report is ScubaResults.json, though that can be changed via the `OutJsonFileName` parameter.

## To reproduce ##
N/A

## Expected behavior ##
The documentation calls out the ScubaResults.json file, not the TestResults.json file, and possibly the `OutJsonFileName` parameter as well.

**Comment by james-garriss** [comment]
What I wrote is correct, but I see how it's confusing, as a reader could easily conflate TestResults.json with ScubaResults.json.  I rewrote to make it clearer.  TY!
