### ISSUE TITLE
PSGallery v1.3.0 package signatures not valid

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#1165]
# 🐛 Summary #

The v1.3.0 release of ScubaGear published to PSGallery appears to have invalid authenticode signatures which is causing installation from PSGallery to fail.  Review of this behavior shows that it is user/region dependent and indicates a caching issue due to removal/relisting of the v1.3.0 release to PSGallery.

## To reproduce ##

1. Make sure ScubaGear is not installed on local machine.  Use `Uninstall-Module -Name ScubaGear` if previously installed via PSGallery.
1. Run `Install-Module -Name ScubaGear -RequiredVersion 1.3.0` to download and install v1.3.0 of ScubaGear

## Expected behavior ##

I expected the ScubaGear module to validate its signatures based on the proper authenticode signature on the catalog and scripts and for the module to be installed successfully.

## Any helpful log output or screenshots ##

Screenshot showing failure when running `Install-Module -Name ScubaGear` due to bad authenticode signatures.
<img width="1328" alt="Screenshot 2024-06-14 at 10 17 03 AM" src="https://github.com/cisagov/ScubaGear/assets/108814318/199a36fb-63ad-4e64-8c31-51ee59ca7b20">

**Comment by mitchelbaker-cisa** [comment]
We've had PSGallery flush their CDN of the ScubaGear package. If you are encountering this error then please try uninstalling/reinstalling the 1.3.0 package:  

```
Uninstall-Module -Name ScubaGear 
```
```
Install-Module -Name ScubaGear -RequiredVersion 1.3.0
```
