### ISSUE TITLE
Add shields.io badges to README

### ISSUE THREAD

**Issue by mitchelbaker-cisa** [cisagov/ScubaGear#1166]
# 💡 Summary ##

Add license, GitHub/PSGallery versions, CICD workflow, open issues, and GitHub/PSGallery download badges.

## Motivation and context ##

This would be useful because it helps redirect users to [GitHub releases](https://github.com/cisagov/ScubaGear/releases), [ScubaGear module on PSGallery](https://www.powershellgallery.com/packages/ScubaGear/1.3.0), as well as displaying our CICD workflow, licensing, etc.

## Implementation notes ##

See badges here: https://github.com/cisagov/ScubaGear/tree/1166-add-download-badges

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Badges are displayed correctly in README and github pages documentation is consistent

**Comment by james-garriss** [comment]
Love the idea!
