### ISSUE TITLE
Getting an unable to parse input:  yaml  error

### ISSUE THREAD

**Issue by insanedasi** [cisagov/ScubaGear#12]
# 🐛 Summary #

When I run the script using all products, I get a message saying "unable to parse input: yaml: line 184: found unknown escape character"   followed by a much of objects not found in the Orchestrator.psml.    If I run the products individually in the RunScuba script the issue does not occur. 

Basically, if I run this, I get the error:
$ProductNames = @("aad", "defender", "exo", "onedrive", "sharepoint", "teams") # The specific products that you want the tool to assess.
 
If I run the script with this (tested with all products) it runs find
$ProductNames =@("teams")

Any help would be greatly appreciated.

![2022-11-11_10-25-43](https://user-images.githubusercontent.com/38466410/201387930-11c59553-36df-4a7c-b340-11d340a512c6.png)

**Comment by ethanb-cisa** [comment]
Thanks for opening the issue. We're looking into it and will assign someone to the issue soon. 

Can you step through each baseline and maybe identify which baseline is generating the error? It seems like Teams runs fine, but one of the others might be the problem.

**Comment by insanedasi** [comment]
When you run the base lines individually the issue is not duplicated.  However as soon as you run it all of them together (the default in the script) then I get this.  I have tested this against multiple tenants and the results are all the same.

**Comment by LatetoGitHub** [comment]
I have the same issue, except it's occurring on a different line. Tried two separate tenants, one with Business Premium licenses, and the other with a mix of many different license types. 

![image](https://user-images.githubusercontent.com/22645887/204316035-67a69e4a-3e77-4385-8920-1c6bca5f7af2.png)

**Comment by LatetoGitHub** [comment]
Here's the line from ProviderSettingsExport.json file

![image](https://user-images.githubusercontent.com/22645887/204317212-e2f61b02-3b33-41a1-92d1-cdfb558406c8.png)

**Comment by LatetoGitHub** [comment]
Thanks, I was able to use the omit Teams workaround to get the reports generated. I was running the scripts from Windows Terminal on Win 11, just in case it helps

`
Name                           Value
----                           -----
PSVersion                      5.1.22621.608
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.608
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
`

**Comment by insanedasi** [comment]
I apologize for the delay in responding.   Here is line 184:

                                 "StopSyncTimestamp":  "\/Date(1657087007367)\/"


I am currently testing out the various combinations and will post any finding once I have completed.
For licensing the following is true:
1 tenant has o365 E3 
2 tenants have M365 E5
All 3 tenants have Azure AD P2  

The error is observable in all 3 tenants.

**Comment by ethanb-cisa** [comment]
Closed in #24
