### ISSUE TITLE
AzureAD Functional Testing

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#1247]
# 💡 Summary #

As part of Iceberg release, to ensure that the tool's update is accurate, detailed functional testing has been planned. Each policy will be functionally tested to check that all pass/fail scenarios have been correctly processed by the tool using existing automated functional test plans.

This issue functionally tests each policy of Azure AD product of ScubaGear tool. The main objective is to test Azure AD policies and ensure that ScubaGear tool is providing the correct result for each possible configuration option. 

## Motivation and context ##
This functional testing ensures that ScubaGear results of pass/fail are accurate based on the latest version of the code.

## Implementation notes ##
For each Azure AD policy do the following:

- [x] Configure the automated testing and run against each tenant type for which a variant testplan is present.  Run the automated test plans (e.g. regular, g5, etc.) and note the results.
- [x] For each test failure, investigate and note the cause of the failure and log any new issues needed to resolve

For details on how to use and execute the functional tests, please see the Testing documentation in [Testing/Readme.md](https://github.com/cisagov/ScubaGear/blob/main/Testing/Readme.md) or reach out to the dev team via other channels.

## Acceptance criteria ##

- [x] All existing test plan variants for the product have been successfully run
- [x] Test plan results have been reviewed and any issues resolved or reported as new issues (Link created issues below)

**Comment by dagarwal-mitre** [comment]
# E5
<img width="779" alt="E5 no var" src="https://github.com/user-attachments/assets/4a380e37-19e8-4a19-853a-4fb18133af1f">
##E5 Variant
<img width="672" alt="E5 Var" src="https://github.com/user-attachments/assets/e85eecfa-e300-4e8e-b6eb-e40b0e46f9ec">

# G5
<img width="679" alt="G5 no var" src="https://github.com/user-attachments/assets/2c629ac4-0944-4f10-973f-4155c32b5765">
##G5 Variant
<img width="783" alt="G5 Var" src="https://github.com/user-attachments/assets/da376f9b-c2e0-4374-a6f5-f47a1bb9146d">

# G3
<img width="743" alt="G3" src="https://github.com/user-attachments/assets/9271b138-e674-4730-968b-866b0a589675">
##G3 Variant
<img width="721" alt="G3 Var" src="https://github.com/user-attachments/assets/f884557e-7d73-4665-a087-e2ecaa0fe89e">
