### ISSUE TITLE
PowerPlatform Functional Testing

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#1250]
# 💡 Summary #

As part of Iceberg release, to ensure that the tool's update is accurate, detailed functional testing has been planned. Each policy will be functionally tested to check that all pass/fail scenarios have been correctly processed by the tool using existing automated functional test plans.

This issue functionally tests each policy of Power Platform product of ScubaGear tool. The main objective is to test Power Platform policies and ensure that ScubaGear tool is providing the correct result for each possible configuration option. 

## Motivation and context ##
This functional testing ensures that ScubaGear results of pass/fail are accurate based on the latest version of the code.

## Implementation notes ##
For each Power Platform  policy do the following:

- [x] Configure the automated testing and run against each tenant type for which a variant testplan is present.  Run the automated test plans (e.g. regular, g5, etc.) and note the results.
- [x] For each test failure, investigate and note the cause of the failure and log any new issues needed to resolve

For details on how to use and execute the functional tests, please see the Testing documentation in [Testing/Readme.md](https://github.com/cisagov/ScubaGear/blob/main/Testing/Readme.md) or reach out to the dev team via other channels.

## Acceptance criteria ##

- [x] All existing test plan variants for the product have been successfully run
- [x] Test plan results have been reviewed and any issues resolved or reported as new issues (Link created issues below)

**Comment by ahuynhMITRE** [comment]
G5
<img width="966" alt="PowerPlatform-G5" src="https://github.com/user-attachments/assets/982afbf4-a73a-44da-82b2-754dadf0261f">

GCC High
<img width="894" alt="PowerPlatform-GCCHIGH" src="https://github.com/user-attachments/assets/5e7850a2-7571-4517-8bf4-d84b80fb23c7">

G3
<img width="906" alt="PowerPlatform-G3" src="https://github.com/user-attachments/assets/8079616d-636f-4685-b160-4c6659b24f72">

Commercial 
<img width="1044" alt="PowerPlatform-E5" src="https://github.com/user-attachments/assets/73d9b1bc-9543-4ac7-82f3-75d9ca9d61a0">

**Comment by ahuynhMITRE** [comment]
all functional test screenshots provided above
