### ISSUE TITLE
SharePoint and OneDrive Functional Testing

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#1251]
# 💡 Summary #

As part of Iceberg release, to ensure that the tool's update is accurate, detailed functional testing has been planned. Each policy will be functionally tested to check that all pass/fail scenarios have been correctly processed by the tool using existing automated functional test plans.

This issue functionally tests each policy of SharePoint/OneDrive product of ScubaGear tool. The main objective is to test SharePoint and OneDrive policies and ensure that ScubaGear tool is providing the correct result for each possible configuration option. 

## Motivation and context ##
This functional testing ensures that ScubaGear results of pass/fail are accurate based on the latest version of the code.

## Implementation notes ##
For each SharePoint and/or OneDrive policy do the following:

- [x] Configure the automated testing and run against each tenant type for which a variant testplan is present.  Run the automated test plans (e.g. regular, g5, etc.) and note the results.
- [x] For each test failure, investigate and note the cause of the failure and log any new issues needed to resolve

For details on how to use and execute the functional tests, please see the Testing documentation in [Testing/Readme.md](https://github.com/cisagov/ScubaGear/blob/main/Testing/Readme.md) or reach out to the dev team via other channels.

## Acceptance criteria ##

- [x] All existing test plan variants for the product have been successfully run
- [x] Test plan results have been reviewed and any issues resolved or reported as new issues (Link created issues below)

**Comment by tkol2022** [comment]
G3 PnP Test
Ran with service principal and got three failed test cases which are expected for policy 1.4 due to a recently discovered settings that is being deprecated by Microsoft. See #1267 for details.

![image](https://github.com/user-attachments/assets/2231d964-33b1-46da-84d8-b4e3a2a6b1d3)

**Comment by tkol2022** [comment]
G5 Pnp Test
Same results as G3 Pnp test.
![image](https://github.com/user-attachments/assets/690af813-e599-4092-ad72-460cf0e0892e)

**Comment by tkol2022** [comment]
E5 Pnp test
Same results as G3 Pnp test. No new issues.
![image](https://github.com/user-attachments/assets/28ca0c8f-1c63-4d29-8aea-b1136a5d57e8)

**Comment by tkol2022** [comment]
GCC High Pnp test
Same results as G3 Pnp test. No new issues.

![image](https://github.com/user-attachments/assets/43b62882-5cbd-40cf-890c-5ad67618c918)

**Comment by tkol2022** [comment]
E5 SPO test
Same results as G3 Pnp test. No new issues.
![image](https://github.com/user-attachments/assets/86523f98-b2eb-4557-8191-1440be09e15d)

**Comment by tkol2022** [comment]
G5 SPO test
Same results as G3 Pnp test. No new issues.
![image](https://github.com/user-attachments/assets/77e96ba5-c5af-439a-aed3-327490264e1f)

**Comment by tkol2022** [comment]
I think this should be closed.
