### ISSUE TITLE
SharePoint incorrectly produces N/A for policy 3.3

### ISSUE THREAD

**Issue by mitchelbaker-cisa** [cisagov/ScubaGear#1307]
# 🐛 Summary #

[MS.SHAREPOINT.3.3v1](https://github.com/cisagov/ScubaGear/blob/main/PowerShell/ScubaGear/baselines/sharepoint.md#mssharepoint33v1) states the following which is incorrect: 

- _Note:_ This policy is only applicable if the external sharing slider on the admin center sharing page is set to **Anyone** or **New and existing guests**.

## To reproduce ##

1. Sign in to SharePoint admin center, go to Policies > Sharing
2. Change the external sharing slider to "Existing Guests", "New and existing guests", and "Anyone" and note the checkbox for `People who use a verification code must reauthenticate after this many days` is displayed in all three options. 

## Expected behavior ##

1. [MS.SHAREPOINT.3.3v1](https://github.com/cisagov/ScubaGear/blob/main/PowerShell/ScubaGear/baselines/sharepoint.md#mssharepoint33v1) should be revised to be:

- _Note:_ This policy is only applicable if the external sharing slider on the admin center sharing page is not set to **Only people in your organization**.

Rego changes need to be made to reflect above:

```
# Standard case
tests contain { ... } if {
  SharingCapability in [NEWANDEXISTINGGUESTS, ANYONE, EXISTINGGUESTS]
}

# N/A case
tests contain { ... } if {
  SharingCapability != ONLYPEOPLEINORG
}
```

![Screenshot (202)](https://github.com/user-attachments/assets/33010193-1095-46ef-b359-980400976f9c)

## Any helpful log output or screenshots ##

Current policy: 

![Screenshot (197)](https://github.com/user-attachments/assets/304f77be-d07e-4769-98f4-ba594926fbc0)

**Comment by tkol2022** [comment]
I met with Mitchel and Beth to demonstrate why the policy is only applicable when the external sharing slider is set to Anyone or New and existing guests. Those are the only two settings where Sharepoint enables verification code users. Closing the issue since no changes are necessary.
