### ISSUE TITLE
Functional tests for Defender cannot find AADReport.json

### ISSUE THREAD

**Issue by james-garriss** [cisagov/ScubaGear#1328]
# 🐛 Summary #

Some of the functional tests for Defender give this warning:

```
WARNING: Error involving the creation of CSV version of output. See the exception message for more details: Cannot find
path 'D:\a\ScubaGear\ScubaGear\repo\M365BaselineConformance_2024_09_24_11_43_30\IndividualReports\AADReport.json' 
because it does not exist.
```

It may that this is a cut-n-paste bug that was not caught from making MergeJson the default.

## To reproduce ##

Look at the Defender runs here:

https://github.com/cisagov/ScubaGear/actions/runs/11012671837

## Expected behavior ##

* The tests should be able to find the files that they need.
* The Defender tests should find Defender files, not AAD files.
* The tests should throw an *Error* not a *Warning* when they fail.

**Comment by adhilto** [comment]
I'm still digging into this, but some observations:
- Only the tests that use the `RunScuba` driver and a config file are failing, so likely an issue inside the `if ($ConfigFileName -and ('RunScuba' -eq $TestDriver)){` branch of Product.Tests.ps1
- Those config files indicate that `ProductNames` is just `defender`. So there really shouldn't be a AADReport.json file. So why is it trying to load it?
- The `ConvertTo-ResultsCsv` function uses the `ProductNames` parameter to determine which json files should exist. So somehow `AAD` has found its way into the `ProductNames` list by the time this function was called.

**Comment by adhilto** [comment]
Figured it out. The problem was that the call to `ConvertTo-ResultsCsv` made by `Invoke-SCuBA` wasn't using the product names given by the config file.

This is the fix. Just need to test to ensure it doesn't break anything else.
![image](https://github.com/user-attachments/assets/9ed7506c-6161-4b78-8898-b5e49a9a4b31)

**Comment by adhilto** [comment]
> Does this mean that the "OutFolderPath" shown should also be using $ScubaConfig.OutFolderPath to prevent issues with paths?

Good catch. Yes, I think so.
