### ISSUE TITLE
Invalid JSON primitive error when running Invoke-Scuba -ProductNames aad

### ISSUE THREAD

**Issue by 4D5A** [cisagov/ScubaGear#134]
# 🐛 Summary #

When you run the command ```Invoke-SCuBA -ProductNames aad```, the script returns the error, "Invalid JSON primitive error."

## To reproduce ##

1. Use PowerShell version 5
2. Run the command ```Invoke-SCuBA -ProductNames aad```
## Expected behavior ##

The module should have completed successfully and opened the HTML report.

## Any helpful log output or screenshots ##

![image](https://user-images.githubusercontent.com/10344127/214699267-365df9e6-c6fe-4def-ab7b-53b9cbcbabcf.png)

The following files are in the report directory after the script exits.

![image](https://user-images.githubusercontent.com/10344127/214699565-3f996cac-60c7-44e7-815f-985e86266e90.png)

**Comment by 4D5A** [comment]
It appears that the aad report is being written to ./ScubaGear-0.2.0/_baselinename_ instead of ./ScubaGear-0.2.0/PowerShell/_baselinename_.

**Comment by 4D5A** [comment]
The problem appears to be with data found in ProviderSettingsExport.json. In my example, the problem is with the "conditional_access_policies". That line of code does not validate as proper JSON. Below is the relevant content:

```json
"conditional_access_policies": ,
	"authorization_policies": {
		"AllowEmailVerifiedUsersToJoinOrganization": true,
		"AllowInvitesFrom": "adminsAndGuestInviters",
		"AllowUserConsentForRiskyApps": null,
		"AllowedToSignUpEmailBasedSubscriptions": true,
		"AllowedToUseSspr": true,
		"BlockMsolPowerShell": false,
		"DefaultUserRoleOverrides": null,
		"DefaultUserRolePermissions": {
			"AllowedToCreateApps": true,
			"AllowedToCreateSecurityGroups": true,
			"AllowedToReadBitlockerKeysForOwnedDevice": true,
			"AllowedToReadOtherUsers": true
		},
		"DeletedDateTime": null,
		"Description": "Used to manage authorization related settings across the company.",
		"DisplayName": "Authorization Policy",
		"EnabledPreviewFeatures": [

		],
		"GuestUserRoleId": "2af84b1e-32c8-42b7-82bc-daa82404023b",
		"Id": "authorizationPolicy",
		"PermissionGrantPolicyIdsAssignedToDefaultUserRole": [
			"ManagePermissionGrantsForSelf.microsoft-user-default-legacy"
		],
		"AdditionalProperties": {

		}
	},
	"admin_consent_policies": {
		"Id": null,
		"IsEnabled": false,
		"NotifyReviewers": false,
		"RemindersEnabled": false,
		"RequestDurationInDays": 0,
		"Reviewers": [

		],
		"Version": 0,
		"AdditionalProperties": {
			"@odata.context": "https://graph.microsoft.com/beta/$metadata#policies/adminConsentRequestPolicy/$entity"
		}
	},
```

**Comment by 4D5A** [comment]
I submitted a fix in [https://github.com/cisagov/ScubaGear/pull/136](https://github.com/cisagov/ScubaGear/pull/136).

**Comment by adhilto** [comment]
Thanks for bringing this to our attention and for your PR. Could you confirm which version of the code you're using? This seems very similar to a previous issue (#19) which was fixed by https://github.com/cisagov/ScubaGear/pull/100. The fix has been merged into main, though it hasn't made it to the next release yet.

**Comment by 4D5A** [comment]
Thank you, @adhilto. Yes, you are correct. This appears to be a duplicate of issue #19. I used release 0.2.0 instead of pulling the newest version. Thank you for reviewing this.
