### ISSUE TITLE
unable to parse input: yaml: invalid trailing UTF-8 octet 

### ISSUE THREAD

**Issue by adminvb29** [cisagov/ScubaGear#140]
# 🐛 Summary #

I am running scuba and getting the following error - unable to parse input: yaml: invalid trailing UTF-8 octet .  After researching it seems that this was fixed in a previous version but I have the latest 0.2.1.

Thank You!
Here is a screenshot

```

Add any screenshots of the problem here.
<img width="662" alt="Screenshot 2023-01-29 110505" src="https://user-images.githubusercontent.com/110404675/215338967-62fa836b-dff5-4ab2-9c64-e1403c760d1d.png">

**Comment by gdasher** [comment]
Link to download main branch: https://github.com/cisagov/ScubaGear/archive/refs/heads/main.zip

**Comment by adminvb29** [comment]
well, thank you guys - current branch removed the error and the report ran but there were other outputs that looked problematic, although the report seem to run fine - do you want me to report in a new bug or leave it here?

<img width="663" alt="image" src="https://user-images.githubusercontent.com/110404675/216174537-0b139bf5-d750-4bda-b8d0-1c23dd37986a.png">

**Comment by gdasher** [comment]
Please file a new issue with the details.  Thanks!
