### ISSUE TITLE
Submit consolidated change document for review and approval (Kraken release)

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#1449]
# 💡 Summary #

Several SCuBA M365 baseline policy updates and additions are in the process of being reviewed, developed, and made.  As part of the new continuous baseline update process, we will submit a consolidated change Word document which reflect any additions/revisions/deletions to the baselines.

## Motivation and context ##

Baseline changes are necessary to keep pace with changing services and evolving guidance. The change document is also required to get CISA approval of latest baseline updates for Kraken's release.

## Implementation notes ##

Please provide details for implementation, such as:

- Developers review each issue for fix or enhancement against current baseline
- Perform testing necessary to validate behavior and understand settings
- Make recommendation to group for policy updates or changes
- Create updates and issue PR for review of small changes

Current document is hosted at the link below
​[ SCuBA M365 Consolidated Changes Kraken.docx](TBD)

## Acceptance criteria ##

The following changes are captured as a part of the document

- [x] #1203 
- [x] #1385 
- [x] #1399 
- [x] #1432

**Comment by ahuynhMITRE** [comment]
sent to @mitchelbaker-cisa to route to comms to process through the CB publication process on 12/12
