### ISSUE TITLE
Add unique ID to each test

### ISSUE THREAD

**Issue by leitzler** [cisagov/ScubaGear#148]
# 💡 Summary #

Add unique ID to tests in the .rego files.

## Motivation and context ##

I'd like to be able to distinguish each test somehow. As it looks today multiple tests share the same `Control`, which seems to be the closest thing to an ID there is for now.

E.g.:
https://github.com/cisagov/ScubaGear/blob/af31c45f5d16e6cb53c5a2969a805e20655066de/Rego/SharepointConfig.rego#L97-L105
and:
https://github.com/cisagov/ScubaGear/blob/af31c45f5d16e6cb53c5a2969a805e20655066de/Rego/SharepointConfig.rego#L119-L127

## Implementation notes ##

By either adding a new field, or update the existing `Control` to `Sharepoint 2.4.1`, we would be able to have something unique to refer to.

## Acceptance criteria ##

- [ ] Each test has an unique identifier

**Comment by ahuynhMITRE** [comment]
Hello @leitzler we are currently working on a schema to label each policy with a unique identifier. The baselines and ScubaGear will be updated with this in the Emerald release.

**Comment by ahuynhMITRE** [comment]
Unique identifiers are a part of #212 for the next release. This issue will be closed as a duplicate.
