### ISSUE TITLE
Inconsistent AADAdditionalData JSON structure in Get-AADTenantDetail

### ISSUE THREAD

**Issue by buidav** [cisagov/ScubaGear#151]
# 🐛 Summary #

This issue was discovered during the escapades of last week. 

`Get-AADTenantDetail` is using a pipe to do the `| ConvertTo-Json` rather than using `ConvertTo-Json @()`. 
As we discovered in the past, piping to `ConvertTo-Json` leads to inconsistent JSON structure. 

This issue is impacting efforts on other tasks which are creating scripts to omit sensitive information from the Provider.json.

----------------------------------------------------
Offending code in `ExportAADProvider.psm1`
```
function Get-AADTenantDetail {
     .....
    $TenantInfo = $TenantInfo | ConvertTo-Json -Depth 4
    $TenantInfo
}
```
## To reproduce ##

Run `Invoke-SCuBA -ProductNames aad` against Test Tenant 1 (G5) and Test Tenant 5 (E3)

## Expected behavior ##

Consistent JSON structure for the tenant data across different tenants. 

## Any helpful log output or screenshots ##

@nanda-katikaneni for specifics.

**Comment by nanda-katikaneni** [comment]
One correction the JSON structure for the tenant details when assessing AAD is inconsistent with other products JSON structure - but it is consistent across tenant types. 

Get-AADTenantDetail for Test-Tenant#1/G5 or Test-Tenant#5/E3 results in the following object format:
   "tenant_details": {
        "AADAdditionalData": {
                                             },
         "TenantId":  "xxxxx",
         "DisplayName":  "yyyyy",
         "DomainName":  "cisaent.onmicrosoft.com"
},


While for other products, the Get-TenantDetail results in the following array format:
        "tenant_details": [
    {
        "TenantId":  "xxxxx",
        "EXOAdditionalData":  "yyyy",
        "DisplayName":  "zzzzz",
        "DomainName":  "cisaent.onmicrosoft.com"
    }
],
