### ISSUE TITLE
OneDrive checks the wrong field for the External Sharing permission level

### ISSUE THREAD

**Issue by tkol2022** [cisagov/ScubaGear#154]
# 🐛 Summary #

OneDrive policy 2.1 checks the OneDriveLoopSharingCapability field to get the value of the external sharing permission level. It should check the **OneDriveSharingCapability** field instead.

The OneDriveSharingCapability field is not found in the MS documentation for Set-SPOTenant but it was identified as the correct field via testing and I verified that it is in the ProviderSettingsExport.json. The OneDrive**LoopSharing**Capability field corresponds to a different feature related to the sharing of whiteboards in Teams meetings.

## Details ##

Run the command below and you will see that it **enables** the ability for OneDrive users to share files externally with Anyone.

`set-spotenant -OneDriveSharingCapability ExternalUserAndGuestSharing
`
![image](https://user-images.githubusercontent.com/107076927/218868164-b84433a2-088c-40d4-91b2-2b8bc945f69b.png)

Run the command below and you will see that it **prevents** the ability for OneDrive users to share files externally with Anyone (that option is greyed out).
`set-spotenant -OneDriveSharingCapability Disabled
`

![image](https://user-images.githubusercontent.com/107076927/218868522-8aa2af04-1aa8-4c36-8c7a-33b1cd34de50.png)

I also verified that changing this setting reflects in the Sharepoint Admin center external sharing slider widget for OneDrive and vice-versa, changing the admin center widget modifies the value of the OneDriveSharingCapability field in ProviderSettingsExport.json.

### Addressing this in the Dolphin release
Since there is already a pull request in progress that modifies the respective Rego policy, the fix will be incorporated into that and should not be heavy lift.

**Comment by Dylan-MITRE** [comment]
Will addresses in PR #122

**Comment by Dylan-MITRE** [comment]
close as #122 is merged
