### ISSUE TITLE
Additional Defender prodcuts

### ISSUE THREAD

**Issue by DeanGross** [cisagov/ScubaGear#16]
# 💡 Summary #

Please add baselines and assessments for the other products in the M365 Defender suite, specifically Defender for Endpoint, Defender for Identity and Defender for Cloud Apps.

## Motivation and context ##

Only providing baselines for Defender for Office 365 is not sufficient. there are many other attack paths that don't include email. 

This would be useful because... organizations need help protecting themselves from all of the attack paths. 

## Implementation notes ##

It would be similar to the documents and tools provided for Defender for O365

## Acceptance criteria ##

When the baselines for all the M365 Defender suite have been published.

- [ ] Criterion

**Comment by ethanb-cisa** [comment]
Closing all `baseline-document` issues to make it easier to track outstanding code issues. If we have questions on your feedback, we'll re-open this issue.
