### ISSUE TITLE
Blank OneDrive 2.2 & 2.3 Report when running with Service Principals. 

### ISSUE THREAD

**Issue by buidav** [cisagov/ScubaGear#160]
# 🐛 Summary #

When running OneDrive with Service Principals, Controls 2.2 and 2.3 are showing up as blank spots on the report. 

## To reproduce ##

On main
```
Invoke-SCuBA -ProductNames onedrive -CertificateThumbprint 1AS2FEWA21 -Organization testtenant1.onmicrosoft.com -AppID 55543221
```

## Expected behavior ##

These controls are utilizing fields that PnP PowerShell cannot grab.  They should be marked as Not-Implemented like OneDrive 2.1 when running with Service Principals. 

## Any helpful log output or screenshots ##
<img width="782" alt="BlankReport" src="https://user-images.githubusercontent.com/105074908/220421757-4fa86647-998d-40b4-989e-a6bc2a137149.PNG">

**Comment by crutchfield** [comment]
Updated to identify manual check required for 2.2 & 2.3 when using service principal.

  
![image](https://user-images.githubusercontent.com/7025068/224339009-7be93e2a-12c3-40ec-b13e-284f4dbbfd2f.png)

![image](https://user-images.githubusercontent.com/7025068/224339139-e66faff1-5a7f-4639-934c-b538eae247c3.png)
