### ISSUE TITLE
Agency 4 Pilot: Teams 2.7 possible bug

### ISSUE THREAD

**Issue by ahuynhMITRE** [cisagov/ScubaGear#162]
feature is noted by Agency 4 to not be available in GCC but was marked as a "PASS". Agency 5 was noted to fail this policy so further investigation into the check and policy is requested.

**Comment by tkol2022** [comment]
### Reviewed 12/14
@ahuynhMITRE @adhilto Please review and close if this is OBE.
If it is still valid, please assign a size label.
Also, I'd like to see more details in the description, including how to re-create the problem.

**Comment by adhilto** [comment]
OBE by https://github.com/cisagov/ScubaGear/pull/333.
