### ISSUE TITLE
Agency 4 Pilot: Exchange 2.4 false negative

### ISSUE THREAD

**Issue by ahuynhMITRE** [cisagov/ScubaGear#163]
Agency 4 noted that they comply with the following policy "A DMARC policy SHALL be published for every second-level domain" but the report is showing as "FAIL"

**Comment by tkol2022** [comment]
### Reviewed 12/14
@ahuynhMITRE @adhilto Please review and close if this is OBE.
If it is still valid, please assign a size label.

**Comment by adhilto** [comment]
OBE by update to add DoH fallback
