### ISSUE TITLE
Product names list not check for unique

### ISSUE THREAD

**Issue by crutchfield** [cisagov/ScubaGear#171]
# 🐛 Summary #

The orchestrator assumes the provided product names are unique.  We do not check to verify.  

## To reproduce ##

1. Invoke-Scuba -ProductNames aad, aad

## Expected behavior ##
We should either reject Product names parameter as invalid or Get-Uniqu when we sort the product names in the rchestrator. 

What did you expect to happen that didn't?

Log into service once as needed.

**Comment by tkol2022** [comment]
### Reviewed 12/14
@crutchfield Please review to ensure this is still valid and not OBE. If it has been taken care of, please close the issue.

**Comment by crutchfield** [comment]
> ### Reviewed 12/14
> @crutchfield Please review to ensure this is still valid and not OBE. If it has been taken care of, please close the issue.

Issue is still valid.  Set size to tiny.

**Comment by twneale** [comment]
I'll try to fumble my way through a well-formed PR with this one.

**Comment by Sloane4** [comment]
Should monitor issue #190 as it can affect this issue
