### ISSUE TITLE
Disconnect SCuBA Tenant attempts to disconnect from services multiple times

### ISSUE THREAD

**Issue by crutchfield** [cisagov/ScubaGear#172]
# 🐛 Summary #

Disconnect SCuBA Tenant attempts to disconnect from services multiple times

## To reproduce ##

1. Disconnect-SCuBATenant

We call disconncet from each service once. 

What did you expect to happen that didn't?

Unit test shows calls (i.e., Disconnect-MgGraph, Disconnect-ExchangeOnline) invoked multiple times.  Need to update unit test to check for Exactly 1 call to disconnect.

**Comment by tkol2022** [comment]
### Reviewed 12/14
@crutchfield  Please review the respective code and close this if the problem is OBE.
Also add a size label based on your assessment.

**Comment by crutchfield** [comment]
Review of FLipper baseline show unit test has been updated to check for single disconnect from identified services.  Closing issue.
