### ISSUE TITLE
Orchestrator's Invoke-Connection allows invalid products

### ISSUE THREAD

**Issue by crutchfield** [cisagov/ScubaGear#173]
# 🐛 Summary #

Orchestrator's Invoke-Connection allows invalid products

## To reproduce ##

1. Visual inspection

## Expected behavior ##

What did you expect to happen that didn't?

Add unit test that verifies parameter, ProductNames, is validated and throws exception if invlaid product provided.

**Comment by tkol2022** [comment]
### Reviewed 12/14
@crutchfield Please review the respective code and close this if the problem has been resolved.
Also I placed a priority of low since this is not a user facing problem.

**Comment by crutchfield** [comment]
Reviewing the current code base (flipper) show sufficeint validation of product parameter. Closing issue.
