### ISSUE TITLE
OneDrive 2.2 link sharing false negatives

### ISSUE THREAD

**Issue by pl4nty** [cisagov/ScubaGear#174]
# 🐛 Summary #

The following requirements are unexpectedly reported as unmet:

* An expiration date SHOULD be set for Anyone links
* Expiration date SHOULD be set to thirty days

However, these are met - visible in the GUI and via PowerShell (DefaultSharingLinkType=AnonymousAccess, RequireAnonymousLinksExpireInDays=30).

<img width="324" alt="image" src="https://user-images.githubusercontent.com/21111317/222347956-f499454f-526c-44fe-89e4-23535fb02aa4.png">

## To reproduce ##

1. Configure tenant to meet the requirements
2. Run SCuBA against the OneDrive workload

This test case was a commercial tenant with E3 licensing.

**Comment by pl4nty** [comment]
This was observed on e4557d9de5330ea48e8d4ddf40a1582f7adae87a, but I'll pull latest (10fef24cb0c654d4bbfa6975bc6a7cc8098c38ec) and try to repro

**Comment by pl4nty** [comment]
Latest just gives no results:

<img width="630" alt="image" src="https://user-images.githubusercontent.com/21111317/222359172-4b8667bc-325e-4682-be22-d641343ab99a.png">

**Comment by pl4nty** [comment]
@schrolla possibly - I used interactive auth

**Comment by tkol2022** [comment]
@pl4nty Can you please run the command below and paste your output here? Thank you!

Get-SPOTenant | Select-Object OneDriveSharingCapability, RequireAnonymousLinksExpireInDays

![image](https://user-images.githubusercontent.com/107076927/223915632-e41d0483-044e-4f56-a7aa-f054554b8221.png)

**Comment by pl4nty** [comment]
Just retried on the latest version, the issue is still present.

@tkol2022 `OneDriveSharingCapability` is missing from the response object in this tenant:

<table>
<tr>
	<td>Property
	<td>Value
<tr>
	<td>SharingCapability
	<td>ExternalUserAndGuestSharing
<tr>
	<td>OneDriveLoopSharingCapability
	<td>ExternalUserAndGuestSharing
<tr>
	<td>CoreLoopSharingCapability         
	<td>ExternalUserAndGuestSharing
<tr>
	<td>CoreSharingCapability             
	<td>ExternalUserAndGuestSharing
<tr>
	<td>RequireAnonymousLinksExpireInDays 
	<td>30
</table>

**Comment by tkol2022** [comment]
May have been closed by mistake. This issue is not tied to the problems in OneDrive when running with a service principal. I'm reopening until resolved.

**Comment by tkol2022** [comment]
@pl4nty Thanks much for getting back.

Please provide the following information to help us debug:

- Can you confirm that the identity you are using to run the tool has the [minimum permission for OneDrive as per the User Permissions section in the README](https://github.com/cisagov/ScubaGear#user-permissions)?

- Can you please also let us know what overall license level your tenant has? E3, E5, G3, G5, or other...

- Run the command below and upload the text file. This will show which fields are coming back from the tenant:

`Get-SPOTenant | Get-Member > onedrivefields.txt`

**Comment by pl4nty** [comment]
Apologies, I think this was bad perms. Either way, it's resolved with the latest version so I'm happy to close this

**Comment by tkol2022** [comment]
Thank you Tom. Also we appreciate the time you took to report this and follow-up on it!
