### ISSUE TITLE
Device Security Baseline for Cross-Tenant Access

### ISSUE THREAD

**Issue by pkothare** [cisagov/ScubaGear#18]
## 💡 Summary ##

Section 2.17 of the [Microsoft Azure Active Directory Baseline](https://www.cisa.gov/sites/default/files/publications/Microsoft%20Azure%20Active%20Directory%20M365%20Minimum%20Viable%20SCB%20Draft%20v0.1.pdf) states that the device claim (compliance status of the device) from the home tenant should be trusted for guests in the resource tenant. When conditional access policies are evaluated during authentication, it only renders a binary answer of whether a device is compliant or not. While this type of policy provides a rudimentary filter for blocking access to non-compliant devices, it does not yield that a guest user's device complies with the resource tenant's security requirements and fundamentally goes against the ZT concept of **not** allowing implicit trust across boundaries.

## Motivation and context ##

Let's consider a simple scenario of a resource tenant and home tenant have differing security requirements for HAADJ/AADJ devices. If the resource tenant requires BitLocker to be enabled for a device to be marked as compliant, but the home tenant does **not** require BitLocker to be enabled to mark a device as compliant, then a user from the home tenant (with whom a resource has been shared) can access a resource as a guest user within the resource tenant without meeting the BitLocker requirements of the resource tenant. This carries a significant security risk if there were no other DLP policies applied to the resources. This yields the question, what is the _real_ value of section 2.17 in the context of guest users as it stands today? While general guidance for securing devices has been laid out through a lot of publications from NIST and CISA, there has to be consensus and a shared understanding of what is considered _secure_ before the implementation steps 2 and 3 under section 2.17.4 are executed. This is confounded by the fact that CISOs and CIOs may have opposing opinions on the on this topic.   

We also have to consider that sharing real-time device configuration across two tenants is probably not a capability that Microsoft can (or will) implement for the conditional access policy feature set any time soon. If and when they do, it can be incorporated into the baseline. In the meantime, to be pragmatic, CISA should _also_ provide a framework for how device trust should be established.

This would be helpful so that CISOs and CIOs can follow guidance from a single authoritative source and build consensus on the absolute minimum required device configuration to meet the security thresholds for cross-tenant collaboration.   

## Implementation notes ##
The framework could include the following:
- Publishing a [security baseline for Windows Devices](https://learn.microsoft.com/en-us/mem/intune/protect/security-baselines) (or use an existing one that defines the bare minimum required).
- Developing scripts that can generate reports about whether security baselines for a tenant have been implemented or not.
- Providing guidance on how home tenant ISOs should supply their security baseline reports as evidence to resource tenant ISOs through Interagency agreements (or some other medium).

## Acceptance criteria ##

Resource tenant implementers have a shared understanding with home tenant implementers on the minimum security/configuration requirements for devices, before cross-tenant access is enabled.

**Comment by ethanb-cisa** [comment]
Thanks for your feedback! We will review your feedback and take it into consideration for the next baseline update.

Closing all `baseline-document` issues to make it easier to track outstanding code issues. If we have questions on your feedback, we'll re-open this issue.
