### ISSUE TITLE
Dolphin release candidate testing - EXO Product Assessment Sanity Testing

### ISSUE THREAD

**Issue by nanda-katikaneni** [cisagov/ScubaGear#180]
# 💡 Summary #

In preparation of releasing the Dolphin or v0.3.0 of ScubaGear code, conduct sanity testing of the EXO product. Objective and Scope of the task are provided below.

Objectives:
1. There are no regression issues in the EXO product assessments with Dolphin Release
2. Additional sanity testing to ensure that: each policy assessment result is shown in the report, assessment works against all available tenants (G5/E5, G3/E3)  
3. EXO product assessment works both in interactive and non-interactive (service principal) modes.

Scope:
1. Detailed functional testing of each policy statement result is out of scope
2. Consistent results between interactive/non-interactive modes and no operational issues in running the test against all tenant types are within the scope.

## Motivation and context ##
This would be useful to ensure that Dolphin release is stable

## Implementation notes ##
Before the test, ensure that test user has minimum user role on a given tenant to assess EXO (look into README). Then, execute the EXO product assessment on all available tenants – first in interactive mode and then in non-interactive mode. After the test verify the following:
1. Verify that all tests run without errors and results reports are generated. Each policy has a result (no empty results)
2. Ensure that there are no regressions from Coral release – for the tested tenant compare the result report from current assessment against saved Coral release results - ensure that any different result is consistent with code change (provide a detailed explanation on any observed diff in results)

## Acceptance criteria ##
1. EXO product assessment works in both interactive and non-interactive mode against G5, E5, G3 and E3 tenants.
2. There are no crashes and/or empty results
3. Results are consistent with Coral release assessment results - any diff is consistent with code changes (viz. support for conditional access policies)

**Comment by adhilto** [comment]
Testing performed:
- Tested against a G5 tenant. All products run (`Invoke-Scuba`)
- Tested against a E5 tenant. All products run (`Invoke-Scuba`)
- Tested against a G3 tenant. All products run (`Invoke-Scuba`)
- Tested EXO in isolation (`Invoke-SCuBA -ProductNames exo`)
- Tested as a non-admin user
- Tested with a service principal

Issues found:
- https://github.com/cisagov/ScubaGear/issues/214
