### ISSUE TITLE
Dolphin release candidate testing - SharePoint Online Product Assessment Sanity Testing

### ISSUE THREAD

**Issue by nanda-katikaneni** [cisagov/ScubaGear#181]
# 💡 Summary #

In preparation of releasing the Dolphin or v0.3.0 of ScubaGear code, conduct sanity testing of the SPO product. Objective and Scope of the task are provided below.

Objectives:
1. There are no regression issues in the SPO product assessments with Dolphin Release
2. Additional sanity testing to ensure that: each policy assessment result is shown in the report, assessment works against all available tenants (G5/E5, G3/E3)  
3. SPO product assessment works both in interactive and non-interactive (service principal) modes.

Scope:
1. Detailed functional testing of each policy statement result is out of scope
2. Consistent results between interactive/non-interactive modes and no operational issues in running the test against all tenant types are within the scope.

## Motivation and context ##
This would be useful to ensure that Dolphin release is stable

## Implementation notes ##
Before the test, ensure that test user has minimum user role on a given tenant to assess the SharePoint Online (look into README). Then, execute the SPO product assessment on all available tenants – first in interactive mode and then in non-interactive mode. After the test verify the following:

1. Verify that all tests run without errors and results reports are generated. Each policy has a result (no empty results)
2. Ensure that there are no regressions from Coral release – for the tested tenant compare the result report from current assessment against saved Coral release results - ensure that any different result is consistent with code change (provide a detailed explanation on any observed diff in results)
3. 

## Acceptance criteria ##

1. SPO product assessment works in both interactive and non-interactive mode against G5, E5, G3 and E3 tenants.
2. There are no crashes and/or empty results
3. Results are consistent with Coral release assessment results - any diff is consistent with code changes (viz. support for conditional access policies)

**Comment by Sloane4** [comment]
**Cisaent- NOT interactive mode**

- [x] Light Mode works **PASS**
- [x] Dark Mode works **PASS**
- [x] No Empty Results **PASS**

_2.1_
- [x] Test 1: File and folder links set to specific people passes **PASS**
- [x] Test 2: File and folder links set to only in org fails **PASS**
- [x] Test 3: File and folder links set to anyone with link fails **PASS**

_2.2_
- [x] Test 1: Sharepoint external sharing set to in org passes **PASS**
- [x] Test 2: Sharepoint external sharing set to new & existing passes **PASS**
- [x] Test 3: Sharepoint external sharing set to existing passes **PASS**
- [x] Test 4: Sharepoint external sharing set to anyone fails **PASS**

_2.3_
- [x] Test 1: Not-Implemented

_2.4 Policy 1_
- [x] Test 1: Sharepoint external sharing set to in org passes **PASS**
- [x] Test 2: Sharepoint external sharing not set to in org, guest expire enabled, expire = 30 days passes **PASS**
- [x] Test 3: Sharepoint external sharing not set to in org, guest expire not enabled, expire = 30 days fails **PASS**
- [x] Test 4: Sharepoint external sharing not set to in org, guest expire enabled, expire not 30 days fails **PASS**
- [x] Test 5: Sharepoint external sharing not set to in org, guest expire not enabled, expire not 30 days fails **PASS**

_2.4 Policy 2_
- [x] Test 1: Sharepoint external sharing set to in org passes **PASS**
- [x] Test 2: Sharepoint external sharing not set to in org, reath enabled, reauth = 30 days passes **PASS**
- [x] Test 3: Sharepoint external sharing not set to in org, reath not enabled, reauth = 30 days fails **PASS**
- [x] Test 4: Sharepoint external sharing not set to in org, reath enabled, reauth not 30 days fails **PASS**
- [x] Test 5: Sharepoint external sharing not set to in org, reath not enabled, reauth not 30 days fails **PASS**

_2.5_
- [x] Test 1: No running custom scripts passes **PASS**
- [x] Test 2: Can run custom scripts fails **PASS**

**Comment by Sloane4** [comment]
**Cisaent- interactive mode**

- [] Light Mode works ****
- [] Dark Mode works ****
- [] No Empty Results ****

_2.1_
- [] Test 1: File and folder links set to specific people passes ****
- [] Test 2: File and folder links set to only in org fails ****
- [] Test 3: File and folder links set to anyone with link fails ****

_2.2_
- [] Test 1: Sharepoint external sharing set to in org passes ****
- [] Test 2: Sharepoint external sharing set to new & existing passes ****
- [] Test 3: Sharepoint external sharing set to existing passes ****
- [] Test 4: Sharepoint external sharing set to anyone fails ****

_2.3_
- [] Test 1: Not-Implemented

_2.4 Policy 1_
- [] Test 1: Sharepoint external sharing set to in org passes ****
- [] Test 2: Sharepoint external sharing not set to in org, guest expire enabled, expire = 30 days passes ****
- [] Test 3: Sharepoint external sharing not set to in org, guest expire not enabled, expire = 30 days fails ****
- [] Test 4: Sharepoint external sharing not set to in org, guest expire enabled, expire not 30 days fails ****
- [] Test 5: Sharepoint external sharing not set to in org, guest expire not enabled, expire not 30 days fails ****

_2.4 Policy 2_
- [] Test 1: Sharepoint external sharing set to in org passes ****
- [] Test 2: Sharepoint external sharing not set to in org, reath enabled, reauth = 30 days passes ****
- [] Test 3: Sharepoint external sharing not set to in org, reath not enabled, reauth = 30 days fails ****
- [] Test 4: Sharepoint external sharing not set to in org, reath enabled, reauth not 30 days fails ****
- [] Test 5: Sharepoint external sharing not set to in org, reath not enabled, reauth not 30 days fails ****

_2.5_
- [] Test 1: No running custom scripts passes ****
- [] Test 2: Can run custom scripts fails ****

**Comment by Sloane4** [comment]
**G3- interactive mode**

- [] Light Mode works ****
- [] Dark Mode works ****
- [] No Empty Results ****

_2.1_
- [] Test 1: File and folder links set to specific people passes ****
- [] Test 2: File and folder links set to only in org fails ****
- [] Test 3: File and folder links set to anyone with link fails ****

_2.2_
- [] Test 1: Sharepoint external sharing set to in org passes ****
- [] Test 2: Sharepoint external sharing set to new & existing passes ****
- [] Test 3: Sharepoint external sharing set to existing passes ****
- [] Test 4: Sharepoint external sharing set to anyone fails ****

_2.3_
- [] Test 1: Not-Implemented

_2.4 Policy 1_
- [] Test 1: Sharepoint external sharing set to in org passes ****
- [] Test 2: Sharepoint external sharing not set to in org, guest expire enabled, expire = 30 days passes ****
- [] Test 3: Sharepoint external sharing not set to in org, guest expire not enabled, expire = 30 days fails ****
- [] Test 4: Sharepoint external sharing not set to in org, guest expire enabled, expire not 30 days fails ****
- [] Test 5: Sharepoint external sharing not set to in org, guest expire not enabled, expire not 30 days fails ****

_2.4 Policy 2_
- [] Test 1: Sharepoint external sharing set to in org passes ****
- [] Test 2: Sharepoint external sharing not set to in org, reath enabled, reauth = 30 days passes ****
- [] Test 3: Sharepoint external sharing not set to in org, reath not enabled, reauth = 30 days fails ****
- [] Test 4: Sharepoint external sharing not set to in org, reath enabled, reauth not 30 days fails ****
- [] Test 5: Sharepoint external sharing not set to in org, reath not enabled, reauth not 30 days fails ****

_2.5_
- [] Test 1: No running custom scripts passes ****
- [] Test 2: Can run custom scripts fails ****

**Comment by Sloane4** [comment]
**G3- NOT interactive mode**

- [] Light Mode works ****
- [] Dark Mode works ****
- [] No Empty Results ****

_2.1_
- [] Test 1: File and folder links set to specific people passes ****
- [] Test 2: File and folder links set to only in org fails ****
- [] Test 3: File and folder links set to anyone with link fails ****

_2.2_
- [] Test 1: Sharepoint external sharing set to in org passes ****
- [] Test 2: Sharepoint external sharing set to new & existing passes ****
- [] Test 3: Sharepoint external sharing set to existing passes ****
- [] Test 4: Sharepoint external sharing set to anyone fails ****

_2.3_
- [] Test 1: Not-Implemented

_2.4 Policy 1_
- [] Test 1: Sharepoint external sharing set to in org passes ****
- [] Test 2: Sharepoint external sharing not set to in org, guest expire enabled, expire = 30 days passes ****
- [] Test 3: Sharepoint external sharing not set to in org, guest expire not enabled, expire = 30 days fails ****
- [] Test 4: Sharepoint external sharing not set to in org, guest expire enabled, expire not 30 days fails ****
- [] Test 5: Sharepoint external sharing not set to in org, guest expire not enabled, expire not 30 days fails ****

_2.4 Policy 2_
- [] Test 1: Sharepoint external sharing set to in org passes ****
- [] Test 2: Sharepoint external sharing not set to in org, reath enabled, reauth = 30 days passes ****
- [] Test 3: Sharepoint external sharing not set to in org, reath not enabled, reauth = 30 days fails ****
- [] Test 4: Sharepoint external sharing not set to in org, reath enabled, reauth not 30 days fails ****
- [] Test 5: Sharepoint external sharing not set to in org, reath not enabled, reauth not 30 days fails ****

_2.5_
- [] Test 1: No running custom scripts passes ****
- [] Test 2: Can run custom scripts fails ****
