### ISSUE TITLE
ProviderSettingsExport.json is broken JSON

### ISSUE THREAD

**Issue by Sankgreall** [cisagov/ScubaGear#19]
# 🐛 Summary #
ProviderSettingsExport.json is broken JSON, resulting in the following reporting error:

```
ConvertFrom-Json : Invalid JSON primitive: .
At C:\Users\Sankgreall\Documents\AzureDevOps\ScubaGear\PowerShell\ScubaGear\Modules\CreateReport\CreateReport.psm1:39
char:44
+ $SettingsExport =  Get-Content $FileName | ConvertFrom-Json
+                                            ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
```

Upon investigating ProviderSettingsExport.json and sticking it in a JSON validator, it flagged the following section:

```
            "conditional_access_policies": ,
    "authorization_policies": {
    "AllowEmailVerifiedUsersToJoinOrganization":  false,
    "AllowInvitesFrom":  "everyone",
    "AllowUserConsentForRiskyApps":  null,
    "AllowedToSignUpEmailBasedSubscriptions":  true,
    "AllowedToUseSspr":  true,
    "BlockMsolPowerShell":  false,
    "DefaultUserRoleOverrides":  null,
    "DefaultUserRolePermissions":  {
                                       "AllowedToCreateApps":  true,
                                       "AllowedToCreateSecurityGroups":  true,
                                       "AllowedToReadBitlockerKeysForOwnedDevice":  true,
                                       "AllowedToReadOtherUsers":  true
                                   },
    "DeletedDateTime":  null,
    "Description":  "Used to manage authorization related settings across the company.",
    "DisplayName":  "Authorization Policy",
    "EnabledPreviewFeatures":  [

                               ],
    "GuestUserRoleId":  "10dae51f-b6af-4016-8d66-8c2a99b929b3",
    "Id":  "authorizationPolicy",
    "PermissionGrantPolicyIdsAssignedToDefaultUserRole":  [
                                                              "ManagePermissionGrantsForSelf.microsoft-user-default-legacy"
                                                          ],
    "AdditionalProperties":  {

                             }
},
```

I'm assuming this is either supposed to be `"conditional_access_policies": "[some value]"` or `"conditional_access_policies": {... nested dict}`

## To reproduce ##

- I've been conducting my testing on a newly provisioned O365 tenant under the MS Developer Sandbox scheme. This is on E3 licensing and configured with a baseline of features.

- Running the script against this tenant lead to this issue. Should be capable of reproducing as all sandbox tenants are theoretically the same.

## Expected behavior ##

Report should be populated, but it's unable to parse JSON

**Comment by Sankgreall** [comment]
- There are no conditional access policies defined on this tenant
- User is Global Admin
- Output of `Connect-MgGraph -Scopes 'Policy.Read.All'` is: `Welcome To Microsoft Graph!`
- Output of `Get-MgIdentityConditionalAccessPolicy | Format-List` is: null

Hope that helps!

**Comment by Sankgreall** [comment]
As a test, I re-ran SCuBA after creating a test conditional access policy and confirming that `Get-MgIdentityConditionalAccessPolicy | Format-List` returned valid data.

Works fine - perhaps just needs to set an empty dict/array if the result from that query is blank.

**Comment by LucasFerguson** [comment]
I am experiencing the same issue. My solution is to set `$AllPolicies = "null"` in the file `ExportAADProvider.psm1`
This probably results in inaccurate results for AAD, but at least the report is able to be generated.

**Comment by Sankgreall** [comment]
This error only triggers if there are zero conditional access policies to report, so if you are experiencing the error and setting $AllPolicies to null, then you won't be losing any data.
