### ISSUE TITLE
Min and Max OPA executable version for ScubaGear

### ISSUE THREAD

**Issue by Dylan-MITRE** [cisagov/ScubaGear#196]
# 💡 Summary #

Check the compatible OPA executable version 

## Motivation and context ##

Currently we are using OPA executable v0.42.1 and the most current version is v0.50.0 we are 8 versions behind
would be good to know what OPA executable is compatible with our product.

## Implementation notes ##

Please provide details for implementation, such as:

- testing different versions of OPA executable's compatibility 

## Acceptance criteria ##

How do we know when this work is done?

- [ ] figure out the min and max version of compatible OPA executable

**Comment by gdasher** [comment]
Related to #195

**Comment by mitchelbaker-cisa** [comment]
Testing Invoke-SCuBA command across all tenants: 

Pass/fail compatibility for the following OPA versions:

- [x] v0.42.2
- [x] v0.43.1
- [x] v0.44.0
- [x] v0.45.0
- [x] v0.46.3
- [x] v0.47.4

![Screenshot 2023-10-31 115559](https://github.com/cisagov/ScubaGear/assets/149098823/3e73ceff-58b1-45c9-bb47-84b1b251234a)

Fixed above by running `.\AllowBasicAuthentication.ps1`

- [x] v0.48.0
- [x] v0.49.2

All tenants run as expected, but Microsoft Teams has 5 Powershell errors

Console output: 

![Screenshot 2023-10-31 120444](https://github.com/cisagov/ScubaGear/assets/149098823/e390fe6b-dafa-4978-9d1c-54365f061487)

**Teams 2.4 External User Access SHALL Be Restricted**
- 1 test: Get-CSTenantFederationConfiguration did not execute successfully

**Teams 2.5 Unmanaged User Access SHALL Be Restricted**
- 2 tests: Get-CSTenantFederationConfiguration did not execute successfully

**Teams 2.6 Contact with Skupe Users SHALL Be Blocked**
- 1 test: Get-CSTenantFederationConfiguration did not execute successfully

**Teams 2.10 Only the Meeting Organizer SHOULD Be Able to Record Live Events** 
- 1 test: Get-CsTeamsMeetingBroadcastPolicy did not execute successfully 

Reran tests against this OPA version, `.\AllowBasicAuthentication.ps1` seems to have cleared up Powershell errors

- [x] v0.51.0
- [x] v0.52.0
- [x] v0.53.1
- [x] v0.54.0
- [x] v0.55.0
- [x] v0.56.0
- [x] v0.57.1

**Comment by mitchelbaker-cisa** [comment]
Pass/fail compatibility for OPA versions (Emerald release): 

- [x] v0.42.2
- [x] v0.43.1
- [x] v0.44.0
- [x] v0.45.0
- [x] v0.46.3
- [x] v0.47.4
- [x] v0.48.0
- [x] v0.49.2
- [x] v0.51.0
- [x] v0.52.0
- [x] v0.53.1
- [x] v0.54.0
- [x] v0.55.0
- [x] v0.56.0
- [x] v0.57.1

**Comment by mitchelbaker-cisa** [comment]
v0.42.2 up to v0.58.0 (latest) runs ScubaGear with no issues for commercial/gcc licenses. Still need to run tests for gcchigh
