### ISSUE TITLE
Dolphin Release Tasks

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#199]
# 💡 Summary #

Perform packaging and labeling activities for SCuBAGear Dolphin release.

## Motivation and context ##

Release activities need to be completed for the current repository HEAD to be labelled, tagged, and packaged for release.

## Implementation notes ##

In order to properly release a new SCuBAGear tool version, several tasks must be accomplished in order.  Please complete the tasks below to complete the new release.

- [x] Change tool version in PowerShell module [manifest](https://github.com/cisagov/ScubaGear/blob/main/PowerShell/ScubaGear/ScubaGear.psd1)
- [x] Update embedded [sample report](https://github.com/cisagov/ScubaGear/tree/main/sample-report) to reflect latest release output
- [x] Create a new tag on the main branch with the Dolphin release version number based on semantic versioning rules (e.g., 0.3.0)
- [x] Manually run the [Build and Sign Release] (https://github.com/cisagov/ScubaGear/actions/workflows/run_release.yaml) action
- [x] Confirm the release artifacts are published on GitHub release page
- [x] Confirm new release is marked as `Set as a pre-release` on the project release page, click `Save changes` NOT `Publish release`
- [x] Update release notes for the release using the same format as prior releases, click `Save changes` NOT `Publish release`
- [x] When ready to make public, edit release and uncheck  `Set as a pre-release` and check `Set as latest release` instead.  Finally, click `Publish release`

## Acceptance criteria ##

- [x] SCuBAGear PowerShell manifest version has been incremented to reflect new value
- [x] Project sample report has been updated to reflect latest release output
- [x] Dolphin release artifacts have been successfully signed
- [x] Release artifacts are published with release notes on the GitHub project releases page
- [x] New release is shown as the latest release on the project page

**Comment by nanda-katikaneni** [comment]
Closing this issue as all tasks are complete.

**Comment by nanda-katikaneni** [comment]
Closing this issue as all tasks are complete.
