### ISSUE TITLE
Sample Report Output

### ISSUE THREAD

**Issue by anthonynogales** [cisagov/ScubaGear#2]
Is it possible to provide a sample output of the report generated by this tool?

**Comment by PeanutTheAdmin** [comment]
+1

**Comment by ramarasuriya** [comment]
+1

**Comment by ethanb-cisa** [comment]
[M365BaselineConformance_2022_11_01_08_32_30.zip](https://github.com/cisagov/ScubaGear/files/9909810/M365BaselineConformance_2022_11_01_08_32_30.zip)

Thanks for the suggestion. Attached is a sample report from a test tenant (so most controls fail). 

We plan to add this to the repo in future releases.

**Comment by ethanb-cisa** [comment]
Re-opening until we merge next release

**Comment by ethanb-cisa** [comment]
Closed in #24
