### ISSUE TITLE
Test the PowerShell execution policy with new signed Dolphin build

### ISSUE THREAD

**Issue by nanda-katikaneni** [cisagov/ScubaGear#204]
# 💡 Summary #

Test the PowerShell execution policy with Dolphin RC build. (Dolphin Test build at https://github.com/cisagov/ScubaGear/releases)

## Motivation and context ##

The ScubaGear build packages are now signed. This test ensures that the package signing does not affect running the tool on a typical windows test environment. 

This would be useful because...it ensures the stability of the build and sign pipeline being used. 

## Acceptance criteria ##

The ScubaGear execution should go smooth on windows with typical PowerShell execution policy. Any issues should be documented along with execution policy of the test system.

**Comment by tkol2022** [comment]
I tested the suggested execution policy in the README updates #208 using the command below against a zip file created with the signed Powershell files on a fresh virtual machine and it works as expected - no warnings or prompts that mention execution policy restrictions. Now that the files are signed, invoking setup and ScubaGear work as expected.

`Set-ExecutionPolicy RemoteSigned`
