### ISSUE TITLE
Update Graph PowerShell module cmdlets for Graph PowerShell v2

### ISSUE THREAD

**Issue by buidav** [cisagov/ScubaGear#205]
# 💡 Summary #

Microsoft Graph PowerShell [Graph PowerShell v2](https://devblogs.microsoft.com/microsoft365dev/microsoft-graph-powershell-v2-is-now-in-public-preview-half-the-size-and-will-speed-up-your-automations/) is in public preview and due to be released soon. There is a significant change to how to beta endpoint is selected in v2. This issue is for updating the relevant cmdlets to the new format and testing to be sure there are no issues with updating to the Graph v2 PowerShell module for ScubaGear.

## Implementation notes ##
- Update the Graph PowerShell cmdlets in the AAD Provider module
- the Graph authentication cmdlets in the Connection module

## Acceptance criteria ##
All Graph cmdlets used in ScubaGear are updated to their Graph v2 Beta cmdlet counterparts if they exist. 
Remove step in run_powershell_test.yaml that removes version 2.0 of graph. 

## ** Impact Analysis
Before the work is conducted to change ScubaGear code to v2, the engineer assigned to this issue will perform an impact analysis, document the results of the analysis in this issue and then the group will perform a group discussion at a planning meeting. This will help to scope the necessary resources including testing hours since making these coding updates is a heavy lift and there could be significant impacts to the software.

**Comment by jpedlow** [comment]
@schrolla thanks for linking my PR :) Still a little bit of a WIP (I'm still learning SCUBA and the process here, but It's up and running in my env, I'll keep adding tweaks over the week as time permits)

I plan on chasing the powershell errors in the picture below, but here's the main screen after running on Graph 2.2:
![image](https://github.com/cisagov/ScubaGear/assets/46536194/f2a239d7-9435-4643-9260-57cdf7b57576)

**Comment by crutchfield** [comment]
Close with #514

**Comment by jpedlow** [comment]
Awesome, thank you @crutchfield  :)
I hope you have a great week!
