### ISSUE TITLE
Adjudicate "substantive changes" to the AAD Scubagear code

### ISSUE THREAD

**Issue by ahuynhMITRE** [cisagov/ScubaGear#210]
# 💡 Summary #
SCuBAGear code needs to work with the latest version of the SCuBA M365 Secure Configuration Baselines. 

 - [x] Expand/test baseline JSON generation against AAD (based on #209)
 - [x] Collapse AAD rego requirement/control fields into single ID field
 - [x] Update rego unit tests to use new ID field rather than requirement/control
 - [x] Adjust AAD rego policy ordering to match new policy groups
 - [x] Update reporter to use new baseline format and generated JSON
 - [x] Add versioned baseline links to reporter output
 - [x] Add check for missing tests to reporter execution
 
## Motivation and context ##

The automation code should work directly from the associated markdown to match policy IDs and policy groups so that a proper assessment report can be generated from a given baseline version.

## Implementation notes ##
The implementation would include updates to the baseline JSON markdown file that would be generated from the newly restructured baseline policy markdown documents as well as changes across the existing code base.  The new JSON file would be made available as a reference for the other code for policy IDs and groups rather than requiring those IDs and groups be embedded within multiple components of the code base directly.

## Acceptance criteria ##

How do we know when this work is done?

- [x] JSON successfully generated from new AAD baseline document with all policy groups and IDs captured
- [x] AAD provider and Rego policies run without errors using new policy groups and IDs
- [x] HTML assessment report successfully generated for AAD and shows new policy groups and IDs
- [x] HTML report includes links to the proper version of AAD baseline policies used during assessment
- [x] Reporter module displays a warning during execution if there are no test results for any of the AAD policy items

**Comment by tkol2022** [comment]
@crutchfield Can you kindly double check this? I know we discussed at the meeting last week. You already took care of the work for this issue correct? Can we close this one?

**Comment by crutchfield** [comment]
> @crutchfield Can you kindly double check this? I know we discussed at the meeting last week. You already took care of the work for this issue correct? Can we close this one?

All items identifie in issue are adressed.  The only item that needs addressed is: 
WARNING: WARNING: No test results found for Control Id MS.AAD.12.2v1
It is covered in #318

**Comment by tkol2022** [comment]
I'm closing this since the work items were completed as part of a different issue which was merged to Emerald.
