### ISSUE TITLE
Adjudicate AAD comments on the comment matrix 

### ISSUE THREAD

**Issue by ahuynhMITRE** [cisagov/ScubaGear#211]
- [x] Send out link to Comments Matrix to the Baseline POCs
- [x] Andrew to schedule meetings with Baseline POCs
- [x] Internally review (Andrew & Baseline POCs) AAD comments from the comments matrix 
Purpose:
   1. Walkthrough comments with the baseline POCs to provide context
   2. Determine if additional follow-up with the original commenter is needed
- [x] Review comments with CISA to do the following:
   1. Prioritization of all comments reviewed 
   2. Creation of GitHub issues for the critical/high priority items into the backlog for further refinement
- [x] Refinement of created GitHub Issues into release lifecycle

**Comment by tkol2022** [comment]
A total of 56 comments were reviewed and addressed. There are numerous GitHub issues to update specific baseline policies and update ScubaGear, currently being worked on for Emerald. I also created an issue to review the 6 comments that we were not able to get to during Emerald. Thanks @ssatyapal123 for your hard work. Thanks @gdasher for all your direction. Thanks @schrolla for letting me bounce ideas off you and offering advice.
