### ISSUE TITLE
Reporting module does not properly HTML encode characters show they show up looking like u0026 in the report

### ISSUE THREAD

**Issue by tkol2022** [cisagov/ScubaGear#216]
# 🐛 Summary #

When running ScubaGear against AAD I found that the HTML output report contained instances of the text "u0026" in the report inside some of the conditional access policy names. This should show as "&" instead.

## To reproduce ##

1. Create a conditional access policy with a special character such as & in it
2. Run the tool and examine the related policy outputs in the report

## Expected behavior ##

The report should show the "&" character or whatever character is used in the names of various tenant objects displayed by ScubaGear.

For example, if I have a CA policy named "Ted & Lars" the report should display the name as "Ted & Lars" but right now it would display "Ted u0026 Lars".

## Any helpful log output or screenshots ##

![image](https://user-images.githubusercontent.com/107076927/226767004-c945425f-bef4-4344-a752-dfb50a9b0c5c.png)
![image](https://user-images.githubusercontent.com/107076927/226767117-a171f0c6-24d3-460b-987c-78981f2f50f9.png)

**Comment by tkol2022** [comment]
### Reviewed 12/14
This is still valid and seems like a minor fix.

**Comment by Sloane4** [comment]
Closing because #604 seemed to resolve the issue
