### ISSUE TITLE
Get-PrivilegedUsers in the AAD Provider is collecting duplicate user role values.

### ISSUE THREAD

**Issue by buidav** [cisagov/ScubaGear#221]
# 🐛 Summary #

This does not affect the tool execution and is a minor JSON bug. Duplicate user roles under the `privileged_users` key are being picked up in the Provider JSON. Seems to be caused when the user is both an admin and part of a group.

## To reproduce ##

Run against any tenant with privileged users.
```
Invoke-SCuBA -ProductNames aad 
```
## Expected behavior ##

No duplicate roles in the roles field.

## Any helpful log output or screenshots ##
<img width="300" alt="duplicateRoles" src="https://user-images.githubusercontent.com/105074908/227019982-0d4e5407-c34b-48c2-b703-ddb097985ef0.PNG">
<img width="310" alt="duplicateRoles2" src="https://user-images.githubusercontent.com/105074908/227020019-637684b6-bf5b-49fb-a9b1-549be35ded74.PNG">

**Comment by tkol2022** [comment]
best example ever. Darth Vader
