### ISSUE TITLE
Document Instructions for adding AAD Conditional Access Policy Exclusions

### ISSUE THREAD

**Issue by ssatyapal123** [cisagov/ScubaGear#232]
# 💡 Summary #
Add instructions to enable users to specify specific user and group exclusions that are documented exemptions to select conditional access policies in the AAD baselines.
Define the yaml structure for CAP exclusions and provide examples.
## Motivation and context ##
CAP exclusions were introduced in the v.0.3 release, but detailed instructions are needed to help users configure them before running the tool.

This would be useful because most tenants are configured to allow CAP exclusions. Previously, the ScubaGear tool flagged as failures any user or group exclusions to these policies. Users need a way to define exemptions, such that their baseline policies are not marked as failures by the ScubaGear tool.

## Implementation notes ##

- This feature is implemented using the -ConfigFilePath option and a configuration file using  yaml notation.
- To run the tool using this option, type: _Invoke-SCuBA -ConfigFilePath .\sample-config-files\aad-config.yaml_

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Examples for each of the relevant conditional access policies
- [ ] Examples of yaml aliases and anchors
- [ ] Clear and easy to follow instructions

**Comment by tkol2022** [comment]
> Didn't realize we had this issue and I made a related issue: #344. Might be best to tackle them both at the same time.

Recommend to add anything missing from 344 to this issue and close 344. They look the same to me, or at least are trying to achieve the same purpose. @schrolla Thoughts?
