### ISSUE TITLE
Invoke-Rego does not validate OPA is present

### ISSUE THREAD

**Issue by crutchfield** [cisagov/ScubaGear#233]
# 🐛 Summary #

Invoke-Rego does not check to validate the OPA executable is present.  

## To reproduce ##

1. Invoke scuba with invalid path to OPA

## Expected behavior ##

Provide user a meaningful mssage that OPA is not install where indicated/expected. 

Consider refactoring Invoke-Rego to use a wraper function instead of & operator so it is more 'Testable'.  Update unit test with Mocked wrapper to validate OPA called with appropriate arguments.

**Comment by Sloane4** [comment]
addressed in PR #641
