### ISSUE TITLE
Question - Recommended new AAD baseline policies about the new centralized Authentication Methods page

### ISSUE THREAD

**Issue by tkol2022** [cisagov/ScubaGear#251]
# 💡 Summary #

Based on the worked performed for #234, #244 and review of numerous comments from individuals that provided formal feedback, I'm recommending the creation of 2 new baseline policies related to authentication methods for Azure AD. See issue #234 for the most relevant context. Proposed new policies are in the bullets below:

- New policy 1 - The Authentication Methods Manage Migration feature SHALL be set to Migration Complete
- New policy 2 - Non phishing-resistant authentication methods SHALL be disabled

### Policy 1 details 

By requiring Migration Complete, we ensure that the tenant has disabled the legacy authentication methods screen (which was not available via the API). This also ensures that the MFA and SSPR authentication methods are **both** managed from a central screen thereby reducing administrative complexity and increasing the security of MFA and SSPR with a single configuration.

*Policy 1 will need to be removed from baseline/ScubaGear in 2024 because Microsoft is deprecating the legacy MFA and SSPR authentication methods administration pages. At that point tenants will effectively be at the state of Migration Complete.

### Policy 2 details

Policy 2 is stating that the less secure methods are disabled on the new centralized Authentication Methods screen. The tenant will enforce that users cannot register or login with the less secure auth methods.

### Actions

- [ ] Get approval or denial from CISA regarding the proposed new policies
- [ ] Refine the language per CISA's direction
- [ ] Revise / Delete any existing MFA baseline policies that are impacted by the new policy

**Comment by tkol2022** [comment]
### ScubaGear Technical Implementation details

To implement these policies in ScubaGear, the [Get-MgPolicyAuthenticationMethodPolicy](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.identity.signins/get-mgpolicyauthenticationmethodpolicy?view=graph-powershell-beta) can be used. This cmdlet returns two fields relevant to the policies:

- PolicyMigrationState
- AuthenticationMethodConfigurations

![image](https://user-images.githubusercontent.com/107076927/231277762-a8f3df2e-7866-490c-813e-9fcbc0956e62.png)

**Comment by gdasher** [comment]
I'm supportive of both policies.  Language initially looks good, but we will re-review when the finalized drafts are ready.

**Comment by tkol2022** [comment]
I'm closing this one out in lieu of #329 which contains a review of all the new MFA policies in a single place.
