### ISSUE TITLE
Revise AAD baseline policy 2.14 based on feedback and prototyping

### ISSUE THREAD

**Issue by tkol2022** [cisagov/ScubaGear#256]
# 💡 Summary #

Modify Azure AD baseline policy 2.14 as per the instructions below. See issue #254 for details.

## Implementation notes ##

- [x] Change the first policy bullet to "Permanent active role assignments SHALL NOT be allowed for highly privileged roles except for break-glass accounts or service accounts that require perpetual access."
- [x] Remove the policy sentence "Active assignments SHALL have an expiration period." from the first policy bullet.
- [x] Add guidance that a conditional access policy can be created for service accounts (e.g. Azure AD Connect account) to restrict them to trusted source locations.
- [x] Modify the Implementation steps to align with the new policy.

**Comment by tkol2022** [comment]
@ssatyapal123 Wanted to provide some details on the changes in this issue to be as precise as possible and make it easier for you to decipher some of my earlier notes. There is a **fundamental change** to how this policy is interpreted by the Rego and therefore will also change the step-by-step implementation instructions in the baseline document too.

### We are changing the 1st policy bullet in the 2.14 baseline as per below

**Old policy**: "Permanent active role assignments SHALL NOT be allowed for highly privileged roles. Active assignments SHALL have an expiration period."

**New policy**: "Permanent active role assignments SHALL NOT be allowed for highly privileged roles except for break-glass accounts or service accounts that require perpetual access."

### Respective ScubaGear changes

- In ScubaGear, remove the checks for the PIM configuration settings "Allow permanent active assignment" and " Expire active assignments after 15 days". We will no longer be checking those configs.
- In ScubaGear, replace those checks with code that examines if there are any **permanent active** assignments (see screenshots below) to highly privileged roles? If there are, we will show a Fail in the report unless the user ID for those assignments are in a config file exclusion.

The screenshot below shows several users that have a permanent active assignment and therefore would produce a Fail in the report unless there a config file exclusion for each user in that list.

![image](https://github.com/cisagov/ScubaGear/assets/107076927/7ae686ef-1967-4c6a-bcff-f1bb45db76c2)

The screenshot below shows a user that has an active assignment that is NOT permanent and therefore would produce a Pass in the report. Notice that there is a specific End time for the assignment.

![image](https://github.com/cisagov/ScubaGear/assets/107076927/a2bec8b7-9277-418d-883c-639fb3c72978)


### Additional general changes
The following change applies to this policy and others.
All references to the recommended list of highly privileged roles, should point to a section at the front of the document instead of referring to the baseline statement "Highly Privileged User Accounts SHALL be Cloud-Only". We are moving the list of privileged roles to the front of the document because it makes more sense to have it in a central location.

**Comment by ssatyapal123** [comment]
Updates made to AAD policy 14.
@tkol2022 does it make sense to combine policies 2.14-2.16 into one group and call it "Highly Privileged User Provisioning" or something, as many of the implementation steps take place in the same PIM dialog boxes?
https://github.com/cisagov/ScubaGear/blob/203-adjudicate-aad-comments/baselines/aad.md#14-permanent-permissions

**Comment by tkol2022** [comment]
Yes, I like that idea! You can probably include 2.11, 2.12 and 2.13 as well because all of those are related to highly privileged user policies. If you decide to do that, then maybe name the section something like Highly Privileged User Management and Monitoring.

**Comment by ssatyapal123** [comment]
@tkol2022 I updated the grouping to include 10 policies in group number 11.
https://github.com/cisagov/ScubaGear/blob/203-adjudicate-aad-comments/baselines/aad.md#11-highly-privileged-user-management-and-monitoring

**Comment by tkol2022** [comment]
Nice. Looks good.

**Comment by tkol2022** [comment]
Closing since it was addressed in 379.
