### ISSUE TITLE
Update ScubaGear code for AAD baseline policy 2.14 based on feedback and prototyping

### ISSUE THREAD

**Issue by tkol2022** [cisagov/ScubaGear#257]
# 💡 Summary #

Modify Azure AD ScubaGear code for 2.14 as per the instructions below. See issue #256  and #254 for details.

## Implementation notes ##

- [ ] Remove the checks for the PIM settings "Allow permanent active assignment" and "Expire active assignments after 15 days".
- [ ] Replace those checks with code that examines if there are any permanent Active assignments. If there are, we show a Fail unless those assignments are in a config file exclusion. To clarify, we will not be checking the PIM setting for this check. Instead we check the list of permanent Active assignments.
- [ ] Make sure the name of the new policy in the report matches what is in the baseline document policy.
- [ ] Also show a list of the users currently "permanently" assigned to privileged roles. We currently hide this information which makes it harder for admins because they have to go look for it.

**Comment by Sloane4** [comment]
Updated to 7.4 & 7.5
