### ISSUE TITLE
ScubaGear with GCC set as environment falsely returns alert that Email Integration for Teams enabled 

### ISSUE THREAD

**Issue by jkozloff-loc** [cisagov/ScubaGear#259]
# 🐛 Summary #

We are running the latest version of ScubaGear against our GCC environment with a Global Administrator account. One of the reported failures is for Microsoft Teams with the following:

**Teams email integration SHALL be disabled**

However, Email Integration is not a supported method for GCC and setting this value through the GUI is hidden within Team Settings for GCC tenants.

## To reproduce ##

With a GCC (standard) tenant and either Global Administrator or Teams Administrator account
1. Open the associated Teams Admin Portal - https://admin.teams.microsoft.com/
2. Then navigate to Teams -> Team Settings
3. Note that the setting for Email Integration is not shown anywhere on the screen.

Per Microsoft, that is by design, as Email Integration is not supported in GCC; they hid the setting. 

When you run a ScubaGear report for environment = GCC, the policy for **Teams email integration SHALL be disabled** returns:

	1 Requirement not met: Email integration is enabled across domain: Global

## Expected behavior ##

If the environment for ScubaGear is GCC, GCCHigh, or DOD display the following text instead so it can be managed by manual reporting.

Cannot be checked automatically. See Microsoft Teams Secure Configuration Baseline policy 2.8 for instructions on manual check

## Any helpful log output or screenshots ##

Microsoft Teams Admin Portal GUI within GCC

![image](https://user-images.githubusercontent.com/130992298/232487926-0bc71de2-d6de-49fc-b4a6-648717a7760c.png)

ScubaGear Failure flag

![image](https://user-images.githubusercontent.com/130992298/232488052-e4ba938d-c4ef-41ae-be0c-027a97188234.png)

**Comment by adhilto** [comment]
@jkozloff-loc Thank you for raising this issue to our attention. I have been able to replicate the issue and have identified the heart of the problem.

We attempted to account for the lack of this feature in gov environments by checking if "GOV" is in what's returned by `$(Get-CsTenant).ServiceInstance`. This works for G3/G5, but we hadn't tested it in a GCC High environment. Turns out "GOV" isn't in the ServiceInstance name for GCC High. As such, this test assumed the feature was available, resulting in the false positive you described above. I'll start working on a patch for this.

**Comment by jkozloff-loc** [comment]
Hi @adhilto ,
Thank you for following up on this bug! I did want to note one thing. You mentioned that the issue is for GCC High, but in our case, we are just GCC and are seeing this issue. 

I ran the Get-CsTenant and here is the value returned for ServiceInstance:

MicrosoftCommunicationsOnline/GOV-1B-G3

Hope this helps!

Thank you again for this solution.

Best regards,
Jeff

**Comment by adhilto** [comment]
The plot thickens. Thanks for the added info, that is very good to know. Will work on a solution that can handle that case as well.
