### ISSUE TITLE
sharepoint connexion not authorized

### ISSUE THREAD

**Issue by hervecinetic** [cisagov/ScubaGear#26]
hello
I test new version V 0.2.0 it's ok for Teams report
but if I want report sharepoint I have an error.

information:
if I want to connect sharepoint online with powershell I need to connect admin center URL:
example: https://domianname-admin.sharepoint.com
not directely :  https://domianname.sharepoint.com 

When I run script I have this error:
![error-sharepoint-connexion](https://user-images.githubusercontent.com/120399887/208462031-bf362182-4f51-41cd-9db7-eaf4a6844697.png)

thanks

**Comment by ethanb-cisa** [comment]
Hi, sorry you're having an issue.

1. Can you verify that you are a `SharePoint Administrator` or higher permission (`Global Administrator`) 
2. This happens when you run `Invoke-SCuBA -ProductNames sharepoint`?

**Comment by hervecinetic** [comment]
Hello

Yes I am global admin and admin sharepoint
***@***.***

I run

***@***.***


And after login prompt
***@***.***

Regards

Hervé


De : Ethan ***@***.***>
Envoyé : lundi 19 décembre 2022 16:41
À : cisagov/ScubaGear ***@***.***>
Cc : Hervé DESSALLES ***@***.***>; Author ***@***.***>
Objet : Re: [cisagov/ScubaGear] sharepoint connexion not authorized (Issue #26)


Hi, sorry you're having an issue.

  1.  Can you verify that you are a SharePoint Administrator or higher permission (Global Administrator)
  2.  This happens when you run Invoke-SCuBA -ProductNames sharepoint?

**Comment by hervecinetic** [comment]
I am admin sharepoint and global admin


![admin-sharepoint-error connexion](https://user-images.githubusercontent.com/120399887/208466591-791327be-a54b-4c90-9997-287f9238a49a.png)

**Comment by hervecinetic** [comment]
hello
after Disconnect-SCuBATenant and rerun report sharepoint I have permission requested graph explorer
the report is ok

thanks

**Comment by ethanb-cisa** [comment]
Glad it was solved! I will close this issue.
