### ISSUE TITLE
Revise Teams policy 2.4 based on the feedback and internal testing

### ISSUE THREAD

**Issue by nanda-katikaneni** [cisagov/ScubaGear#260]
# 💡 Summary #

Modify M365 Teams baseline policy 2.4 as per the instructions below.

## Motivation and context ##

Based on the pilot and internal feedback, the existing policy has ambiguity and/or buttonology that can potentially change.

## Implementation notes ##

- [x] Ambiguity in baseline text. Recommend adding "in the Global (Org-wide default) meeting policy or in custom meeting policies if any exist."
- [x] Clarify external user access and "allow"restriction"; define "guest" 
- [x] The policy bullet uses "buttonology." Recommend changing the policy bullets to the following:
"Only the meeting organizer SHOULD be able to record live events in the global (org-wide default) live events policy.
Alternate live events policies MAY be created that allow agency-approved users the ability to record."

## Acceptance criteria ##

Updated policy has the changes noted in Implementation notes.

**Comment by ahuynhMITRE** [comment]
Closed when merged as part of PR #461
