### ISSUE TITLE
Add “SHALL” guidance to Force DLP scans on newly uploaded files into SharePoint/OneDrive

### ISSUE THREAD

**Issue by Dylan-MITRE** [cisagov/ScubaGear#262]
# 💡 Summary #

Add “SHALL” guidance to Force DLP scans on newly uploaded files into SharePoint/OneDrive. 

## Motivation and context ##

Issue: 
It can take 20 minutes for SharePoint index new uploads and apply DLP. There is a PowerShell setting you can enable that will prevent newly uploaded files from being shared externally until the DLP engine has had a chance to scane the file: Set-SPOTenant -MarkNewFilesSensitiveByDefault BlockExternalSharing

Reference: https://learn.microsoft.com/en-us/sharepoint/sensitive-by-default#mark-files-as-sensitive-by-default

## Implementation notes ##

Please provide details for implementation, such as:

- add an new policies to Force DLP scans on newly uploaded files into SharePoint/OneDrive. 
- code should be added to reflect the new baseline

## Acceptance criteria ##

How do we know when this work is done?

- [ ] baseline changes
- [ ] code added

**Comment by gdasher** [comment]
Given the 20 minute lag, I think there is too much operatinoal impact for SHALL.  Opne to SHOULD or leaving this one out.  Probably prefer to leave it out (and leave at agency discretion)

**Comment by Dylan-MITRE** [comment]
I am leaning towards more on dont fix it for now and maybe put this in the backlog for future consideration

**Comment by Dylan-MITRE** [comment]
> Question has been answered. @Dylan-MITRE Based on feedback either close this as won't fix or filter in as a SHOULD.


I am leaning towards more on dont fix it for now and maybe put this in the backlog for future consideration

**Comment by tkol2022** [comment]
Let's go ahead and close this one based in CISA's preference to leave it out of the baseline.
Nice suggestion @Dylan-MITRE  !!
