### ISSUE TITLE
Split OneDrive 2.3 into two policies

### ISSUE THREAD

**Issue by Dylan-MITRE** [cisagov/ScubaGear#264]
# 💡 Summary #

Split and clarify the current OneDrive 2.3 baseline v.0.1 policy "Link Permissions SHOULD Be Set to Enabled Anyone Links to View" into two separate policies to make it easier for readers to understand and for automation to report.

## Motivation and context ##

The current baseline policy is a solid best practice, but the wording does not make it clear that there are two separate settings needed to properly protect links: one to make the default sharing link only be to others within the organization (i.e., not anyone) and a second to make sure when a user does make a link available to anyone that the default permissions on that link are view only.
This would be useful because right now the baseline does reference the Microsoft best practice that includes both settings, but the implementation section 2.3.4 in the baseline itself only shows the setting changes to address the view only portion.

## Implementation notes ##

Recommended update would be to split this policy into two policies to address both the default link sharing type and the anyone link default permissions. Both policies would still include references to the same Microsoft best practices document, but the implementation details would differ.
The new policies would be something like the following:

2.3 Default Link Sharing Type SHOULD NOT Be Set to Anyone
If Anyone link sharing is enabled, the default when creating a link is set to Anyone. Providing a more secure default option can mitigate unintentional sharing with unauthenticated anonymous third parties. To do so, set the default sharing type to be limited to people within your organization instead.
The implementation details would then be as follows:
To set the default file and folder sharing link for the organization:
1.	Open the SharePoint admin center, and select Sharing.
2.	Under File and folder links, select Only people in your organization or Specific people (only the people the user specifies).
3.	Select Save

2.4 Anyone link permissions SHOULD be Set to View Only
The implementation section would include instructions
1.	Open the SharePoint admin center.
2.	In the left-hand navigation pane, expand Policies, then select Sharing.
3.	Under Advanced settings for Anyone links, set the Files permissions to View.
5.	Under Advanced settings for Anyone links, set the Folders permissions to View.

## Acceptance criteria ##

How do we know when this work is done?

Updated policy has the changes noted in Implementation notes.

**Comment by tkol2022** [comment]
I checked the Emerald branch and it appears that this work has been incorporated into the baseline. Please check and close this if appropriate.

The new policies in the baseline that seem to align with this issue are below:

MS.SHAREPOINT.2.1v1
File and folder default sharing scope SHALL be set to Specific People (only the people the user specifies).

MS.SHAREPOINT.3.2v1
The allowable file and folder permissions for anyone links SHALL be set to View only.
