### ISSUE TITLE
AAD 2.10 Browser Persistence Policy Deprecation

### ISSUE THREAD

**Issue by ssatyapal123** [cisagov/ScubaGear#269]
# 💡 Summary #

Based on feedback from pilot agencies, AAD Policy 2.10 "Browser Sessions SHALL not be Persistent" is not being met. This policy aligns with NIST SP 800-63B. However, most agencies are using compensatory controls (e.g., corporate managed devices, strong authentication) making this policy unnecessary.

## Motivation and context ##

Improve the baseline policies by removing policies that are widely considered unnecessary due to the existence of policies that offer the same protection.

Removing this policy would be useful because it would improve usability without compromising security for Federal agencies.

## Implementation notes ##

- Baseline documentation would need updating

## Acceptance criteria ##

How do we know when this work is done?
- [ ] Documentation is updated and the existing 2.10 is listed as deprecated

**Comment by ssatyapal123** [comment]
Removed policy 2.10 from the baseline (see branch in GitHub: https://github.com/cisagov/ScubaGear/blob/203-adjudicate-aad-comments/baselines/aad.md)

For now, leaving the subsequent numbering as-is to make it easier to resolve issues, but at the end of all updates, will renumber all the policies to remove any gaps.

**Comment by tkol2022** [comment]
The code change for this was incorporated into PR #408 so there is no need for a separate fix branch for this.
