### ISSUE TITLE
Add the Quiet Parameter to Invoke-SCuBA

### ISSUE THREAD

**Issue by buidav** [cisagov/ScubaGear#272]
# 💡 Summary #

`Invoke-RunRego` currently has the quiet parameter to stop the tool from automatically opening the html report in a browser. 
For use cases when the json/report folder needs to be automatically moved to another location, we should backport the `Quiet` parameter to `Invoke-SCuBA` to omit opening the report.

<img width="443" alt="quiet" src="https://user-images.githubusercontent.com/105074908/233484188-658f5ac4-10cb-48fa-979a-1f285bd49c07.PNG">

## Motivation and context ##

This is to assist automation on other tasks for SCuBA
 
## Implementation notes & Acceptance criteria

Add quiet parameter to `Invoke-SCuBA` and so that we are able to omit the report from opening during a standard run.

**Comment by jacdavi** [comment]
+1 for this. It's actually necessary when running ScubaGear on [`servercore`](https://hub.docker.com/_/microsoft-windows-servercore). The image doesn't have a way to open the HTML which causes a fatal error.

```
Fatal Error involving the Report Creation. 
            Ending ScubaGear execution. See the exception message for more 
details: No application is associated with the specified file for this 
operation
```
