### ISSUE TITLE
Question - Proposed new AAD policy to protect MFA registration

### ISSUE THREAD

**Issue by tkol2022** [cisagov/ScubaGear#273]
# 💡 Summary #

We received a recommendation from Microsoft to create a new baseline policy to protect the MFA registration process via a conditional access policy. Microsoft's Detection and Response Team also presented lessons learned to Scuba which includes the same recommendation. Since we already have several conditional access policies in the AAD baseline already, the scope of this issue is to perform hands-on prototyping with a new policy that would require MFA registration from "trusted locations" or "managed devices" and see what the impacts are to the user and to the sys admin / organization. We will also explore a similar conditional access policy to protect registering a device (laptop, etc.) with AAD.

See comments 19 and 31 in the spreadsheet.

[Mandiant recommends "Organizations can restrict the registration of MFA devices to only trusted locations, such as the internal network, or trusted devices" when describing APT 29 activity]( https://www.mandiant.com/resources/blog/apt29-continues-targeting-microsoft). 

[This link provides an example for a conditional access policy that requires users to be in a trusted network location, do multifactor authentication or use Temporary Access Pass credentials](https://learn.microsoft.com/en-us/azure/active-directory/conditional-access/howto-conditional-access-policy-registration)

Microsoft's Detection and Response Team (DART) presented M365 security recommendations from the trenches. Microsoft DART recommends restricting MFA registration from a managed device. 

## Implementation details ##
Test multiple scenarios of performing MFA registration with and without a managed device. See separate comment below for details.
When performing the tests below, take note of any "chicken before the egg" scenarios where the test user is not able to successfully perform their MFA registration due to any existing conditional access policies that we already have in the baseline (e.g. requiring a managed device or some other condition).

**Comment by tkol2022** [comment]
# Prototyping Details

## Scenario 1 overview
Scenario 1 below tests registering MFA devices and joining machines to Azure AD with our existing policy 2.17 that requires the user to be on a managed device when accessing the tenant. No new policies are tested in this scenario.

## Scenario 1 - MFA registration with our existing policy 2.17 that requires a managed device but no specific CA policy restricting the registration process
	Include specific users (for test)
	Cloud apps or actions > All cloud apps
	Grant > Grant access > Require device to be marked as compliant or Require Hybrid Azure AD joined device

## Scenario 1 Test Results
I was able to perform MFA registration from an unmanaged device even though the user was within scope of our existing CA policy 2.17 requiring a managed device to access the tenant. Once I got past the registration process itself I could not get access to the tenant (as expected).
This demonstrates that the AAD CA policy 2.17 requiring a managed device does not specifically restrict the MFA registration process. MFA registration can be performed from any device even if existing policy 2.17 is implemented.

## Scenarios 2, 3 and 4 overview
Scenarios 2, 3 and 4 test registering MFA devices with new CA policies restricting the registration process but without the existing policy 2.17.
Scenarios 2 and 3 are the strictest and therefore offer the most security, but are less flexible than scenario 4.
The term "trusted location" refers to an IP address range that has been marked as "trusted" in the Conditional Access Named Locations page. In practice this might refer to a set of on-premises IP addresses or a block of addresses from a Zero Trust provider.

## Scenario 2 - very strict - New MFA registration CA policy requiring Trusted Location without existing policy 2.17
	Include specific users (for test)
	Cloud apps or actions > User actions > Register security information
	Conditions > Locations > Include > Any location and Exclude > All trusted locations
	Grant > Block access

The CA policy is configured to Block - there are no exceptions - the user must come from a trusted location - temporary access pass is not supported.

## Scenario 2 Test Results
The policy worked as expected. On a device that is not coming from a trusted location, I was unable to perform the MFA registration. Once I switched to a device on a trusted IP, I was then able to register an MFA device.
I also tested a second scenario. Once the user registered an MFA device, I then logged in as the user from a device that is not on a trusted IP and tried to go to Profile > View Account > Security Info to see if I could register a new MFA device from the untrusted IP and I was not able to do that. This demonstrates that once the MFA registration is secured by the CA policy, this restricts registration no matter which security registration page (there are multiple) the user tries to access.

## Scenario 3 - very strict - New MFA registration CA policy requiring a managed device without existing policy 2.17
	Include specific users (for test)
	Cloud apps or actions > User actions > Register security information
	Grant > Grant access > Require device to be marked as compliant or Require Hybrid Azure AD joined device

The CA policy is configured to Grant access but requires the user to be on a managed device.

## Scenario 3 Test Results
The policy worked as expected. On an unmanaged device I received an error blocking the registration of a new MFA device. Once I logged onto a machine that was Hybrid Azure AD joined, the system allowed me to perform MFA registration.

## Scenario 4 - less restrictive - New MFA registration CA policy requiring MFA or temporary access pass without existing policy 2.17
	Include specific users (for test)
	Cloud apps or actions > User actions > Register security information
	Conditions > Locations > Include > Any location and Exclude > All trusted locations
	Grant > Grant access > Require multifactor authentication

This policy is similar to scenario 2 because it allows registration from trusted locations, but it also allows registration outside trusted locations by using a "temporary access pass" which is a short term access code that admins can provision to users. 

Scenario 4 is less restrictive (and more flexible) compared to 2 and 3 alone because a user can still register an MFA device outside the trusted location (or not on a managed device) using a temporary access pass. This scenario makes more sense for organizations that cannot force all users to register MFA from a specific set of source IP addresses (i.e. there is no single "trusted network") and cannot force users to register MFA from a managed device at this time. 

The CA policy is configured to Grant Access > Require multifactor authentication. The temporary access pass meets the multifactor requirement. Trusted locations are excluded in the Conditions section, which means if the user comes from a trusted location, they don't need a temporary access pass to register MFA.

## Scenario 4 Test Results
On a device that is not a trusted IP, I went to https://aka.ms/mysecurityinfo, entered the username and then the temporary access pass and I was able to register a new MFA device, despite the fact that I wasn't on a trusted network. Also, with scenario 2 I made sure that I was able to register an MFA device when on a trusted network (to ensure the CA exclusion was working).

## Scenario 5 - combining trusted locations with managed devices (no temporary access pass) - New MFA registration CA policy requiring a Trusted Location or a Managed Device
	Include specific users (for test)
	Cloud apps or actions > User actions > Register security information
	Conditions > Locations > Include > Any location and Exclude > All trusted locations
	Grant > Grant access > Require device to be marked as compliant or Require Hybrid Azure AD joined device

Scenario 5 combines scenarios 2 and 3 into a single policy to provide another flexible option but stricter than scenario 4 which allows for temporary access pass from anywhere. The user is allowed to register an MFA device only from a trusted location or from a managed device.

## Scenario 5 Test Results
The policy worked as expected. I was only able to register from a trusted location or from a managed device.

## Scenario 6 overview
Scenario 6 tests registering MFA devices with new CA policies restricting the registration process in conjunction with the existing policy 2.17

## Scenario 6 - new & existing policies together - New MFA registration CA policy requiring Trusted Location or Managed Device along WITH existing policy 2.17
	Include specific users (for test)
	Cloud apps or actions > User actions > Register security information
	Conditions > Locations > Include > Any location and Exclude > All trusted locations
	Grant > Grant access > Require device to be marked as compliant or Require Hybrid Azure AD joined device

	Include specific users (for test)
	Cloud apps or actions > All cloud apps
	Grant > Grant access > Require device to be marked as compliant or Require Hybrid Azure AD joined device

Scenario 6 combines our existing policy 2.17 (which requires a managed device to access the tenant) with a new policy (based on scenario 5) that requires a trusted location or managed device to register MFA. This scenario secures the MFA registration gap that existing policy 2.17 does not address by itself (see summary below for details).

## Scenario 6 Test Results
The policy worked as expected. No constraints or check before the egg scenarios observed. I tested several combinations of environmental conditions (with or without managed device, with or without trusted location) and the system behaved as I anticipated.

## Summary
The key aspect learned from this exploration is that existing AAD policy 2.17 alone (which requires a managed device), protects accessing the tenant (i.e. getting to the apps) but does not protect the MFA registration process. Therefore it makes sense to create a new policy to protect the MFA registration process, especially since this is a known attack vector and current gap in our policies.

I recommend creating a new MFA registration policy that supports coming from a trusted location, coming from a managed device or using a temporary access pass.

**Comment by tkol2022** [comment]
## Question to CISA
Based on testing to understand the feasibility and constraints of the proposed policy, I recommend a new baseline policy to protect MFA registration. See previous comment for details.

- Does CISA agree with this recommendation?
- If yes, any specific direction on the policy?

**Comment by gdasher** [comment]
I think in general yes.  the issue is that "trusted location" is not a zero trust based policy.  So I would recommend leaving that out.  Policy woudl be SHOULD and "managed device".  You can add a security consideration about trusted location but we shouldn't recommend IP based policies.

**Comment by tkol2022** [comment]
Issues #323, #324 were created to update the baseline and ScubaGear.
