### ISSUE TITLE
AAD 2.9 Sign-In Frequency Policy Deprecation

### ISSUE THREAD

**Issue by ssatyapal123** [cisagov/ScubaGear#274]
# 💡 Summary #

Based on feedback from pilot agencies (comment 8), AAD Policy 2.9 "Sign-In Frequency SHALL be configured to 12 hours" is not being met. This policy aligns with NIST SP 800-63B. However, it comes at a price to usability and is considered unnecessary for most users. However, it may have a use for sensitive applications or privileged users, or users coming from personal devices.

## Question for CISA - Question Answered - Remove Policy and Address in AAD 2.14 ##

Although most pilot agencies failed this policy, it may be appropriate for special cases. For example, privileged user access and access to sensitive applications could be required to have a sign-in frequency of 12 hours.

This would be useful because it doesn't ignore the NIST guidance but applies it where it makes the most sense.

## Scope of baseline document changes

- [ ] Modify AAD policy 2.9 to remove it from the baseline per this issue.

**Comment by gdasher** [comment]
I think that by default privileged access to the console at least already has some limit without us setting a policy--you should check that though. 

I certainly also support a limit with PIM--elevations limited to time duration X, but I think we already have that in 2.14 (although it is fairly long--15 days--and is just embedded in the implementation versus the policy statement).  I would suggest revisiting that versus this change.

  My suggestion for this policy is to just remove it entirely (along with the "persistent cookies" policy).

**Comment by ssatyapal123** [comment]
Thanks Grant, agree with your suggestion to remove the policy and adjust PIM elevation time durations for select privileged accounts.
Regarding the privilege access console timeout, in Azure, each user can set their own inactivity timeout period (see: https://learn.microsoft.com/en-us/azure/azure-portal/set-preferences).

**Signing out**

_The inactivity timeout setting helps to protect resources from unauthorized access if you forget to secure your workstation. After you've been idle for a while, you're automatically signed out of your Azure portal session. As an individual, you can change the timeout setting for yourself. If you're an admin, you can set it at the directory level for all your users in the directory._

As there is already a setting for Azure users, it could be confusing to introduce another one in Conditional Access which I imagine overrides this setting. My setting is set to Never which may be the default.

The Azure Active Directory (Azure AD) default configuration for user sign-in frequency is a rolling window of 90 days.  (See: https://learn.microsoft.com/en-us/azure/active-directory/conditional-access/howto-conditional-access-session-lifetime)

**Comment by ssatyapal123** [comment]
Removed Policy 2.9 from the aad baseline markdown. (see: https://github.com/cisagov/ScubaGear/blob/203-adjudicate-aad-comments/baselines/aad.md)
