### ISSUE TITLE
Teams Policy 2.6 - update to clarify the support for Skype

### ISSUE THREAD

**Issue by nanda-katikaneni** [cisagov/ScubaGear#279]
# 💡 Summary #

Teams Policy 2.6 states "Microsoft officially retired Skype for Business Online on July 31, 2021, and it is no longer supported". As OPM has highlighted Skype for business support is been extended to 2025; check to see if the policy / rego is scoped to cover Skype online and Skype for business and make any necessary updates. 

## Motivation and context ##

Policy statement update based on new end of support timeline for Skype for Business Online. Based on the policy update, it may require changes to Rego policy, in which case a separate issue will be added. 

## Implementation notes ##

Update the policy statement to provide new end of life support for Skype for Business Online and if this require a change in pass/fail criteria.

## Acceptance criteria ##

Changes suggested in implementation notes above.

**Comment by ahuynhMITRE** [comment]
Closed when merged as part of PR #397
