### ISSUE TITLE
Improve handling of complex mail flow and DKIM/DMARC/SPF

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#28]
I was investigating the DKIM related issues with Agency 1, which seem to be do mostly to their more complex mail flow configuration.

Agency 1 mail flow is more complex than just office365 to the internet.  They route their mail back through what looks like an on-prem Forcepoint email gateway, which is what actually signs their mail as seen by recipient.  This is based on me looking at some inbound email from people at Agency 1.  This uses selector agency1seg2048a._domainkey.agency1.gov. and it seems to work as expected.

However, EXO is also configured with DKIM signing of email being sent to the forcepoint gateway.  They have multiple domains in EXO, some of which have dkim "disabled" and others have it "enabled".  The actual mail samples I saw seem to use DKIM signing using a a selector associated with the domain "agency1365.onmicrosoft.com", which is marked as _enabled_ in the config.  This is apparently what microsoft [does](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/email-authentication-dkim-configure?view=o365-worldwide) when the custom domain dkim policy is not enabled (as in this example).  This mail is purely internal to Agency 1 infrastructure between O365 and their on-prem email gateway (which also appears to validate DKIM).

We probably at least need to add some documentation indicating this behavior for situations with more complicated mail flow.  In theory, we could detect mail routing configs that send outbound email not directly to the destination and use that to influence our messages.

**Comment by ethanb-cisa** [comment]
See my comment on #41
