### ISSUE TITLE
Defender 2.2 - Clarify confidence level determination for DLP policies

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#280]
# 💡 Summary #

Add a clarifying statement to the Defender 2.2 policy introduction to make it clear to readers that the confidence level associated with supported information types (SITs) such as SSN, credit card, etc. is up to the organization to determine and is not part of the baseline policy recommendation.

## Motivation and context ##

The current Defender 2.2 policy states that DLP policies should include checks for PII and sensitive information, however, neither the policy item nor its implementation steps mention confidence levels associated with those SITs.  While Microsoft includes a recommended confidence level the policy leaves it up to interpretation whether or not the recommendation is meant to be the default, if the organization should tune the level as desired, or if another specific setting for each level is recommended.

Clarifying policy on confidence levels associated with the SITs would benefit the reader and provide additional guidance for tenant owners configuring DLP policies.

## Implementation notes ##

Clarifying language should be inserted into the policy item description regarding SIT confidence levels and what the recommended approach may be.  The primary options are:

1. Confidence levels are organizationally defined, when in doubt use vendor defaults
2. Always use vendor provided defaults
3. Use baseline recommended defaults (these would need to be created for at least 3 SITs and potentially up to 40+)

Based on the chosen recommendation, update the policy language and implementation steps accordingly.

## Acceptance criteria ##

- [x] Baseline recommendation for setting confidence levels for SITs used in DLP policies is determined
- [x] Defender 2.2 policy language is updated to reflect the chosen recommendation

**Comment by gdasher** [comment]
Makes sense.  Please add clarification.
