### ISSUE TITLE
Defender 2.2 - Add DLP custom policy to utilize restricted app groups to prevent access to sensitive info

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#283]
# 💡 Summary #

Add policy language and implementation steps to create a policy action to prevent restrict app and app group access to sensitive files on devices using Defender Endpoint protection.

## Motivation and context ##

The current Defender SCB policy 2.2 requires enabling data loss prevention (DLP) and does include configuration of restricted apps in the DLP Endpoint settings area.  The implementation notes, however, do not include creating a policy action to restrict access to sensitive information based on those restricted apps and app groups.

Since restricted apps are already defined in the implementation, it makes sense to utilize them to limit access to sensitive information in the policies.  Otherwise the creation of restricted app groups has no purpose relative to the existing baselines.

## Implementation notes ##

Assuming inclusion of the restricted apps and app groups action is determined to be the right course of action, then the changes would be to add the following:

- Adjust the first policy bullet to include the Devices location as follows:
  - The custom policy SHOULD be applied in Exchange, OneDrive, Teams Chat, and Device
- Add a new policy bullet that reads as follows:
  -  The custom policy SHOULD include an action to block access to sensitive information by restricted apps
- Update the implementation steps to include instructions for configuring the Devices location and restricted apps block action

## Acceptance criteria ##

- [x] Determination on inclusion of devices action in custom policy statements has been made
- [x] If included, Defender baseline policy 2.2 had been updated with the changes outlined in the implementation notes

**Comment by gdasher** [comment]
Makes sense.  Please implement as specified.
