### ISSUE TITLE
Fix EXO deprecated alert policies in MS.EXO.16.1

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#29]
<img width="855" alt="Defender2 9" src="https://user-images.githubusercontent.com/105074908/207478160-01f293b1-41df-47f1-aecb-a3a5afedcd8f.PNG">

Defender 2.9 was showing as a fail in the report and highlighted 2 policies. 
- "Malware campaign detected after delivery" 
- "Unusual increase in email reported as phish"

Both of these prebuilt alert policies have disappeared from the Alert Policy list and thus from current Provider exports.
I looked back at an older Provider JSON and found that policies were still there a little over month ago.

<img width="679" alt="OctoberJson" src="https://user-images.githubusercontent.com/105074908/207478669-aa830bb4-9d7a-46c9-a3a4-3975312e9710.PNG">

The names of these policies are listed in EXO 2.16, so this will require both a baseline policy update and a Rego code change.

**Comment by tkol2022** [comment]
Related #235
