### ISSUE TITLE
Revise AAD 2.11.1 implementation step to match Microsoft terminology

### ISSUE THREAD

**Issue by tkol2022** [cisagov/ScubaGear#292]
# 💡 Summary #

- In AAD baseline policy 2.11.1 implementation Policy bullet 2, step 5, related to Identity Secure Score, change "Use limited administrative roles" to "Use least privileged administrative roles" to match the terms used in Microsoft's product.

- Upon further review of other comments, it turns out that we don't currently have a policy 2 bullet, so maybe we need to create one to match up with the implementation instructions?
- In Implementation policy bullet 2, condense the instructions.

GitHub issue #282 also proposes a new policy to this section, so keep that in mind when drafting the new policy bullets.

**Comment by tkol2022** [comment]
If this ends up needing any code changes, make sure to open a related ScubaGear update issue.

**Comment by ssatyapal123** [comment]
Fixed the language to match Microsoft but didn't add the second policy bullet as yet. @tkol2022 Do we want to change the code to check the Identity Score and show a fail if it is not at the max score?

**Comment by tkol2022** [comment]
Good idea. I don't think we can fail if the Identity Score is not the max because this policy is specifically about the "Use least privileged administrative roles" item in the score, not the whole identity score which contains a number of other policies. Maybe ScubaGear could check the status value for the least privileged admin roles item and ensure it is "Completed"? I'm okay with adding that. If you find that it is possible using a Graph cmdlet, then go ahead and create an issue for it.

**Comment by ssatyapal123** [comment]
I found a Graph reference that could work:
https://learn.microsoft.com/en-us/graph/api/resources/securescore?view=graph-rest-1.0
Will open an issue 
https://learn.microsoft.com/en-us/graph/api/resources/controlscore?view=graph-rest-1.0

I will open an issue to look into this further.

**Comment by tkol2022** [comment]
https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.security/get-mgsecuritysecurescore?view=graph-powershell-beta

**Comment by tkol2022** [comment]
Closing since it was addressed in 379.
