### ISSUE TITLE
Revise AAD 2.7.4 Implementation based on feedback

### ISSUE THREAD

**Issue by tkol2022** [cisagov/ScubaGear#294]
# 💡 Summary #

Revise AAD 2.7 Implementation section per the new content below. Microsoft moved where the Admin Consent settings are located.

## Implementation notes ##

For the Implementation section, change the implementation starting at step 7 as per below:

7. Click Save.
8. Navigate to the Admin consent settings page.
9. Under Admin consent requests -> Users can request admin consent to apps they are unable to consent to, select Yes.
10. Under Who can review admin consent requests​, select the group created in step two that is responsible for reviewing and adjudicating app requests.
11. Click Save.

**Comment by ssatyapal123** [comment]
Updates made:
https://github.com/cisagov/ScubaGear/blob/203-adjudicate-aad-comments/baselines/aad.md#7-consenting-to-third-party-applications
