### ISSUE TITLE
AAD 2.4 update Microsoft Authenticator references and implementation

### ISSUE THREAD

**Issue by tkol2022** [cisagov/ScubaGear#295]
# 💡 Summary #

Microsoft made numerous changes to the AAD Authentication Methods page w/r/t to settings specific to the MS Authenticator Push notifications such as number matching and additional context data. The scope of this issue is to update the baseline policy and implementation section to match the current state of the authentication methods page.

We also received a comment that [Microsoft authenticator number matching will be automatically enabled](https://learn.microsoft.com/en-us/azure/active-directory/authentication/how-to-mfa-number-match#enable-number-matching-in-the-portal) for authentication push requests. "To protect the ecosystem and mitigate these threats, Microsoft will enable number matching for all tenants starting May 8, 2023. **After protection is enabled by default, users can't opt out of number matching in Microsoft Authenticator push notifications**." Based on this, it looks like there won't be any need to explicitly configure number matching.

## Implementation notes

- [x] Remove references to Number Matching from the baseline section 2.4 policies and implementation.
- [x] Revise the MS Authenticator policies to match the current features on the Authentication Methods page
- [x] Perform hands-on prototyping #313 to understand how the new features work in practice to understand any impacts to the baseline

## Current baseline section (which is outdated now)
![image](https://user-images.githubusercontent.com/107076927/235729999-cdc9355b-65c9-4593-be5a-cb707af0817f.png)

## Screenshots (new version of MS Authenticator settings on Authentication Methods page)
![image](https://user-images.githubusercontent.com/107076927/235730427-e163c740-22f2-480a-9212-794758b8c716.png)
![image](https://user-images.githubusercontent.com/107076927/235730612-979f1fa4-fd87-4c18-a20a-7a31aa3d957b.png)

**Comment by tkol2022** [comment]
This issue is tied to new policy 3 in issue #329.

**Comment by ssatyapal123** [comment]
@tkol2022, I updated the baseline policies and implementations but have am not sure I have the implementation reference steps right for policy 7. https://github.com/cisagov/ScubaGear/blob/203-adjudicate-aad-comments/baselines/aad.md#4-enforce-strong-mfa-and-secure-the-registration-process

**Comment by tkol2022** [comment]
I don't think we can reference a Microsoft page for this one because their examples do not fit this specific configuration scenario. Instead create instructions for making a conditional access policy that follows the template below

	Include All users
	Cloud apps or actions > User actions > Register security information
	Grant > Grant access > Require device to be marked as compliant or Require Hybrid Azure AD joined device

**Comment by ssatyapal123** [comment]
@tkol2022  Thanks Ted for the clarification! I found a link that reflects most of the steps and added text regarding the last step.
https://learn.microsoft.com/en-us/azure/active-directory/conditional-access/howto-conditional-access-policy-registration

**Comment by tkol2022** [comment]
Closing since this was addressed via #379.
