### ISSUE TITLE
Question - AAD suggestion to remove restricting directory visibility for guest users

### ISSUE THREAD

**Issue by tkol2022** [cisagov/ScubaGear#296]
# 💡 Summary #

We received a comment on the "Guest users have limited access to properties and memberships of directory objects" configuration for AAD policy 2.18. Although the comment was more about including another option as permissible, I'm proposing that we consider removing this configuration from the baseline as I'm not sure how much value it provides. It seems more like security by obscurity and I would prefer to focus on other more impactful policies that we already have and new ones that were proposed.

## Question to CISA ##

- Do you agree that we can remove the policy "Guest users SHOULD have limited access to Azure AD directory objects." and its associated implementation?
- State your rationale.

**Comment by gdasher** [comment]
I'm not sure I agree it is "security by obscurity".  IIUC, what this does is limit which attributes on the resource tenants director object a guest user in that tenant can see by default?  This seems sensible.  What was the concern with keeping this?  It is listed as should and is thus already not mandatory.

**Comment by tkol2022** [comment]
@gdasher To answer your questions.

- To foster better interagency collaboration, guest access may be required so that agencies can access one another's Teams and Sharepoint assets.
- By limiting what guest users can see in the directory, it is not clear what impact that has on the end-user in the cross-agency collaboration context.

Given that we have higher priority items to adjudicate, I will close this one.
