### ISSUE TITLE
Recommended new Power Platform baseline policy - Restrict the creation of Power Pages to administrators only.

### ISSUE THREAD

**Issue by buidav** [cisagov/ScubaGear#311]
# 💡 Summary #
Microsoft in their review of Power Platform recommended adding a new Power Platform baseline policy that restricts the creation of [Power Pages (websites) to admin users](https://learn.microsoft.com/en-us/power-apps/maker/portals/control-portal-creation) 
This will restrict the creation of the Apps to users to the following roles.
- Global Admin,
- Power Platform Admin
- Dynamic 365 Admin

This control currently can only be implemented via PowerShell i.e no GUI. This setting can be checked via ScubaGear as the cmdlet that retrieves this setting is already invoked in the Power Platform Provider.
```
Set-TenantSettings -RequestBody @{ "disablePortalsCreationByNonAdminUsers" = $false }
```
## Question for CISA ##
- Should we add this new policy to the Power Platform baseline?
- Are there use cases where non-administrative users would want to create Power Pages?

**Comment by gdasher** [comment]
This seems sensible, though I'm not sure we have enough data on operational impact to make a decision.  I suggest we include it as a SHOULD control.

**Comment by gdasher** [comment]
at the SHOULD level
