### ISSUE TITLE
Agency Pilot: AAD 2.1 Legacy Authentication False positive

### ISSUE THREAD

**Issue by ahuynhMITRE** [cisagov/ScubaGear#316]
AAD 2.1 "Legacy authentication SHALL be blocked" produced a false positive for an agency pilot. The agency has legacy authentication blocked but only for locations outside of the US. For this they configured the "locations" and "client apps" sections within the conditions for a conditional access policy. 

Please email Andrew Huynh for the provider json for further investigation.

![image](https://user-images.githubusercontent.com/113476170/236235205-cd8c5b3d-072f-4282-842e-e60b9abb5f33.png)

P.S. the results was found using the Scubagear module version 0.2.1

**Comment by ahuynhMITRE** [comment]
tied to #92

**Comment by tkol2022** [comment]
@ahuynhMITRE Since this appears to be a real-world manifestation of the bug described in #92 and not a separate bug, do we need this separate issue? Can we take the description of this issue and put it into #92, then close this one?

**Comment by ahuynhMITRE** [comment]
closing due to consolidation of issue into #86
