### ISSUE TITLE
AAD- Markdown document alignment issues

### ISSUE THREAD

**Issue by crutchfield** [cisagov/ScubaGear#318]
# 🐛 Summary #

There are several alignment issues between the aad markdown (i.e., secure baseline) and the software implementation (i.e., Rego).

## Expected behavior ##

No Rego implementation 
- MS.AAD.5.2v1	
- MS.AAD.5.3v1
- MS.AAD.12.2v1

Policy Description 
- MS.AAD.15.1.v1 - Terminate with period at end of line
- MS.AAD.17.1v1 - Starts with hyphen
- MS.AAD.14.1v1 - Terminate with period at end of line
- MS.AAD.12.2v1 - Terminate with period at end of line
- MS.AAD.8.1.v1 - Starts with hyphen
- MS.AAD.5.4v1 - Using right quote (i.e., &#8217) instead of apostrophe (i.e., '&#x27)
- MS.AAD.5.2v1 - Does not contain criticality (i.., SHALL, SHOULD, MAY) in description

**Comment by ahuynhMITRE** [comment]
Updated the following in the 212 branch and added note of change alignment to this issue:

MS.AAD.15.1.v1 - Updated
MS.AAD.17.1v1 - Removed hyphen
MS.AAD.14.1v1 - Updated
MS.AAD.8.1.v1 - Removed hyphen
MS.AAD.5.4v1 - Updated
MS.AAD.5.2v1 - Added criticality

**Comment by tkol2022** [comment]
@crutchfield @ahuynhMITRE  Can you please opine on which items are still left to be addressed? From the notes it looks like some work was done on this issue.

**Comment by crutchfield** [comment]
> 

Looks like MS.AAD.12.2v1 (No rego implementation) is the last remaining issue.

**Comment by tkol2022** [comment]
MS.AAD.12.2v1 is not a policy. It is a reference of the list of highly privileged roles. This list is referenced in policy 12 and numerous other policies. Therefore there will not be a Rego policy for this.
 @ssatyapal123 Can you please add the following updates to one of your other issues?

- [ ] Move the reference list of highly privileged roles to the top of the AAD baseline document. Maybe in the terms section.
- [ ] Change all references to this list to refer to the front of the document.

**Comment by tkol2022** [comment]
@crutchfield See my latest note. If there are no planned future pull requests for this issue and the work has already been completed somewhere else, kindly close this issue. Thank you.

**Comment by crutchfield** [comment]
All work has been complete or moved to other issues.
