### ISSUE TITLE
Teams- Markdown document alignment issues

### ISSUE THREAD

**Issue by crutchfield** [cisagov/ScubaGear#319]
# 🐛 Summary #

There are several alignment issues between the teams markdown (i.e., secure baseline) and the software implementation (i.e., Rego).

## Expected behavior ##

MS.TEAMS.1.1v1 - End policy description with period.
MS.TEAMS.2.1v1 - End policy description with period.
MS.TEAMS.3..3v1 - No Rego (May statement)
MS.TEAMS.3,4v1 - No Rego (Should statement)
MS.TEAMS.3.5v1 - No Rego (May statement)
MS.TEAMS.9.2v1 - No Rego (May Statement)
MS.TEAMS9.3v1 - Using unicode right single quoatation mark instead of ASCI Apostrophe
MS.TEAMS.11.3v1 - No Rego (Should statement)

**Comment by nanda-katikaneni** [comment]
The updated baseline document addresses:
MS.TEAMS.3,4v1 - No Rego (Should statement) --> deleted
MS.TEAMS.3.5v1 - No Rego (May statement) --> deleted
