### ISSUE TITLE
Exchange - Markdown document alignment issues

### ISSUE THREAD

**Issue by crutchfield** [cisagov/ScubaGear#320]
# 🐛 Summary #

There are several alignment issues between the defender markdown (i.e., secure baseline) and the software implementation (i.e., Rego).

## Expected behavior ##

Expect a one-to-one mapping between secure baseline and Rego implementation.

Markdown file name does not align with product names.  exchange vs. exo

MS.EXCHANGE 4.1 - 4.4 Start with hyphen
MS.EXCHANGE.4.2v1-- Non-standard characters (Right/Left Double Quotation Mark)
MS.EXCHANGE.6.1v1 --  Description starts with hyphen
MS.EXCHANGE.6.2v1 -- Description starts with hyphen
MS.EXCHANGE.12.1v1 -- Description starts with hyphen
MS.EXCHANGE.12.2v1 -- Description starts with hyphen
MS.EXCHANGE.12.3v1 -- Description starts with hyphen
MS.EXCHANGE>9.1v1 -- Non-standard characters (left single quote not apostrophe)
MS.EXCHANGE.12.3v1 -- Policy end with period violation (."). Gramatically correct. :)
MS.EXCHANGE.16.2v1 -- Description starts with hyphen

**Comment by ahuynhMITRE** [comment]
Updated the following in the 212 branch and added note of change alignment to this issue:
MS.EXCHANGE 4.1 - 4.4, removed hypens
MS.EXCHANGE.4.2v1-- Removed (Right/Left Double Quotation Mark)
MS.EXCHANGE.6.1v1 -- Removed hyphen
MS.EXCHANGE.6.2v1 -- Removed hyphen
MS.EXCHANGE.12.1v1 -- Removed hyphen
MS.EXCHANGE.12.2v1 -- Removed hyphen
MS.EXCHANGE.12.3v1 -- Removed hyphen
MS.EXCHANGE>9.1v1 -- Removed Non-standard characters (left single quote not apostrophe)
MS.EXCHANGE.12.3v1 -- Removed Policy end with period violation (."). Gramatically correct. :)
MS.EXCHANGE.16.2v1 -- Removed hyphen

**Comment by crutchfield** [comment]
Verified in Emerald branch 
MS.EXCHANGE 4.1 - 4.4 Start with hyphen
MS.EXCHANGE.4.2v1-- Non-standard characters (Right/Left Double Quotation Mark)
MS.EXCHANGE.6.1v1 -- Description starts with hyphen
MS.EXCHANGE.6.2v1 -- Description starts with hyphen
MS.EXCHANGE.12.1v1 -- Description starts with hyphen
MS.EXCHANGE.12.2v1 -- Description starts with hyphen
MS.EXCHANGE.12.3v1 -- Description starts with hyphen
MS.EXCHANGE>9.1v1 -- Non-standard characters (left single quote not apostrophe)
MS.EXCHANGE.12.3v1 -- Policy end with period violation (."). Gramatically correct. :)
MS.EXCHANGE.16.2v1 -- Description starts with hyphen
