### ISSUE TITLE
Onedrive- Markdown document alignment issues

### ISSUE THREAD

**Issue by crutchfield** [cisagov/ScubaGear#321]
# 🐛 Summary #

There are several alignment issues between the onedrive markdown (i.e., secure baseline) and the software implementation (i.e., Rego).

## Expected behavior ##

Expect a one-to-one mapping between secure baseline and Rego implementation.

MS.ONEDRIVE.1.2v1 - Rego missing?
MS.ONEDRIVE.1.2v1 - Duplicate (maps to two policies)
MS.ONEDRIVE.2.2v1 - No Rego implementation

**Comment by ahuynhMITRE** [comment]
Updated the following in the 212 branch and added note of change alignment to this issue:

MS.ONEDRIVE.1.2v1 - Updated
MS.ONEDRIVE.1.2v1 - Updated
MS.ONEDRIVE.2.2v1 - Updated

**Comment by crutchfield** [comment]
Verified in Emerald branch 
MS.ONEDRIVE.1.2v1 - Rego missing?
MS.ONEDRIVE.1.2v1 - Duplicate (maps to two policies)
(OBE) MS.ONEDRIVE.2.2v1 - No Rego implementation
