### ISSUE TITLE
AAD policy 2.2 add recommendation to block risky service principals

### ISSUE THREAD

**Issue by tkol2022** [cisagov/ScubaGear#322]
# 💡 Summary #

We received a recommendation to create a new AAD conditional access policy to block risky service principals (aka workload identities). [CISA directed us to include a recommendation](https://github.com/cisagov/ScubaGear/issues/270) in the baseline but do not mandate this as an official policy because it requires an additional license above G5/E5.

Justification: This can help mitigate scenarios where hackers use AAD applications to access the tenant for nefarious purposes.

## Implementation notes ##

- [x] Modify AAD section 2.2 High Risk Users SHALL be Blocked. Add a recommendation to create a conditional access policy that blocks Medium and High risk workload identities. Provide [this MS link as a reference](https://learn.microsoft.com/en-us/azure/active-directory/conditional-access/workload-identity).

**Comment by tkol2022** [comment]
@schrolla Great question. CISA "I would consider adding it to security considerations on the policy about blocking High Risk as a non-normative note."
I personally consider this a very important policy because abusing service principals is a known common attack technique and it gives the adversary a chance to authenticate without password/MFA, but the constraint is the additional license, which most organizations may not have. Would love to hear your thoughts?

**Comment by tkol2022** [comment]
@adhilto asked the question, "Would this have the potential to lock-out our ScubaGear service principals?"
Yes, it could lock out any principal that is marked as risky based on the MS detection algorithm. [See this link for details](https://learn.microsoft.com/en-us/azure/active-directory/identity-protection/concept-identity-protection-risks) on the factors which contribute to "risk".  So if someone used a ScubaGear service principal (e.g. using stolen credentials) in an anomalous way, it could lock-out that principal. Keep in mind that when we say a "service principal", we are referring to an identity that is specific to a given tenant.

**Comment by tkol2022** [comment]
We discussed this topic at the stand-up. Specific feedback was provided by @adhilto and @buidav.
The consensus was that, if we were to add this as a new baseline policy, the policy would be a SHOULD. If this ScubaGear check does not pass, we would display a "Warning" (as we do for all SHOULD statements) and we would potentially display a message letting the user know that they do not have the required license. Of course the license message would only show up in the scenario that the tenant does not have the license.
This approach is consistent to how we handle other scenarios where the policy does not pass and the tenant is missing a license.

### Question to CISA
@gdasher Are you comfortable just mentioning this feature as a sentence or two in the policy description? In other words, no new policy.

**Comment by tkol2022** [comment]
@gdasher Re-pinging on this. See most recent comments and the last question which was sparked by group discussion at the stand-up.

**Comment by ssatyapal123** [comment]
Here's a suggested policy description updated in case this ends up as the consensus for this issue:
## 2. High Risk Users

Azure AD Identity Protection uses various signals to detect the risk
level for each user and determine if an account has likely been
compromised. In addition to high risk users, high risk workload identies
may be mitigated by creating a conditional access policy that blocks medium
and high risk work load identities.
Follow [these instructions](https://learn.microsoft.com/en-us/azure/active-directory/conditional-access/workload-identity) to apply conditional access for workload identities.

**Comment by tkol2022** [comment]
@ssatyapal123 This looks good! Thank you.
