### ISSUE TITLE
AAD new ScubaGear check to secure MFA registration

### ISSUE THREAD

**Issue by tkol2022** [cisagov/ScubaGear#324]
# 💡 Summary #

Create a new ScubaGear policy check that corresponds to the new baseline policy protecting MFA registration #323.

## Implementation notes ##

- [ ] Create a new policy in the report that corresponds to the baseline policy.
- [ ] Implement the ScubaGear Rego code for the new policy.

**Comment by crutchfield** [comment]
Closed with #416
