### ISSUE TITLE
Sharepoint -- Markdown document alignment issues

### ISSUE THREAD

**Issue by crutchfield** [cisagov/ScubaGear#325]
# 🐛 Summary #

What's wrong? Please be specific.

There are several alignment issues between the sharepoint markdown (i.e., secure baseline) and the software implementation (i.e., Rego).

## Expected behavior ##

Expect a one-to-one mapping between secure baseline and Rego implementation.

MS.SHAREPOINT.1.1v1 -- Non-standard character, Double left quotation. 
MS.SHAREPOINT.1.2v1 -- Not implemented in rego?  Non-standard character.Double left quotation. 
MS.SHAREPOINT.4.1v1 -- Non-standard characters. Left/right single quotations. 
MS.SHAREPOINT.4.2v1 -- No sperate rego implementation appears to be combined with MS.SHAREPOINT.4.1v1
MS.SHAREPOINT.5.1v1 -- Current Rego has variations for OneDrive and Self-Service sites.

**Comment by ahuynhMITRE** [comment]
Updated the following in the 212 branch and added note of change alignment to this issue:
- MS.SHAREPOINT.1.1v1 -- Removed Double left quotation.
- MS.SHAREPOINT.1.2v1 -- Removed Double left quotation 
- MS.SHAREPOINT.3.1v1 -- Removed Left/right single quotations.

**Comment by crutchfield** [comment]
Verified in emerald branch:
(ok) MS.SHAREPOINT.1.1v1 -- Non-standard character, Double left quotation.
(ok - added not implemented in automation of baseline) MS.SHAREPOINT.1.2v1 -- Not implemented in rego? Non-standard character.Double left quotation.
(ok) MS.SHAREPOINT.4.1v1 -- Non-standard characters. Left/right single quotations.

Still need to resolve the following: 
MS.SHAREPOINT.4.2v1 -- No sperate rego implementation appears to be combined with MS.SHAREPOINT.4.1v1
MS.SHAREPOINT.5.1v1 -- Current Rego has variations for OneDrive and Self-Service sites.

**Comment by crutchfield** [comment]
Review of re-write of SharePoint/One Drive secure baseline will cover these concerns.
