### ISSUE TITLE
PowerPlatform -- Markdown document alignment issues

### ISSUE THREAD

**Issue by crutchfield** [cisagov/ScubaGear#326]
# 🐛 Summary #

There are several alignment issues between the PowerPlatform markdown (i.e., secure baseline) and the software implementation (i.e., Rego).

## Expected behavior ##

Expect a one-to-one mapping between secure baseline and Rego implementation.
MS.POWERPLATFORM.2.1v1 - MS.POWERPLATFORM.2.3v1  Start with hyphen
MS.POWERPLATFORM.2.3v1 - Not terminated with period
MS.POWERPLATFORM.3.3v1 - "May" policy not implemented.

**Comment by ahuynhMITRE** [comment]
Updated the following in the 212 branch and added note of change alignment to this issue:
- Removed hyphens for MS.POWERPLATFORM.2.1v1 - MS.POWERPLATFORM.2.3v1

- For "MS.POWERPLATFORM.2.3v1 - Not terminated with period", added a period at the end of the list of connectors but unsure if this will resolve the issue.

**Comment by crutchfield** [comment]
Verified resolved in emerald branch.  
MS.POWERPLATFORM.2.1v1 - MS.POWERPLATFORM.2.3v1 Start with hyphen
MS.POWERPLATFORM.2.3v1 - Not terminated with period

I implemened "MS.POWERPLATFORM.3.3v1 - "May" policy not implemented." as 'not implemented' in automating baseline.
