### ISSUE TITLE
Refactor Rego Helper Functions

### ISSUE THREAD

**Issue by crutchfield** [cisagov/ScubaGear#328]
# 💡 Summary #

Some helper functions (e.g., ReportDetailsBoolean) are redundant across product rego files.  These shoukd be refactord to a utilities file and reused to reduce maintenance costs.

## Motivation and context ##

Technical debt: Reduce maintenance costs

## Implementation notes ##

See Rego/Utils/ReportUtils.rego as an example.

## Acceptance criteria ##

- [ ] No \<product\>Config.rego has redundant functions

**Comment by Sloane4** [comment]
Link #342

**Comment by Sloane4** [comment]
being addressed in PR #642
