### ISSUE TITLE
Update AAD 2.4 MFA policies per feedback and discussion

### ISSUE THREAD

**Issue by tkol2022** [cisagov/ScubaGear#329]
# 💡 Summary #

This issue provides a draft update to the AAD MFA policies in the baseline, based on feedback, testing and recent discussions with CISA.

## Question to CISA ##

Please review the draft policies below and provide feedback. Since this specific section of the AAD baseline is revised quite a bit for improvements, we want to ensure there is agreement before making the changes to the baseline document and ScubaGear. This will replace the existing policy group named "2.4 Phishing-Resistant Multifactor Authentication SHALL Be Required for All Users". Numerous other GitHub issues were executed leading up to this one.

## Our Strategy ##

Here are the tenets of our strategy when architecting these revisions:

- Ensure policies align with OMB or other mandates.
- Include recommendations from open-source intelligence reports based on real-world M365 incident response engagements.
- Include new M365 features that provide security configuration and risk assessment value to the end user.
- Include feedback from baseline reviewers.
- Place all the MFA policies (including new ones) in a single baseline section to keep things organized.

## Draft New MFA Policy Section (Please review this)

**New policy group name**: "**Enforce strong MFA and Secure the Registration Process**"

*The items prefixed with "Comment:" are not part of the baseline - those are for information purposes in this GitHub issue. Policy numbers below are just for reference. Each item will be assigned an official baseline policy ID based on the new format when the baseline is updated.

**Policy 1 - Phishing-resistant MFA SHALL be enforced for all user**s.
At this time, Azure AD supports the three phishing-resistant methods listed below:
Azure AD Certificate-Based Authentication (CBA) - supports Federal PIV cards
FIDO2 Security Key
Windows Hello for Business

Comment: ScubaGear will check this by looking for a conditional access policy containing an Authentication Strength that only allows the three methods listed above. Notice that Federated PIV cards have been removed from the list because A) there is no way to check that PIV authentication was used during Federated login even with the authentication strength feature and B) implementation of CBA will help decouple agency tenants from security breaches that affect on-premises ADFS and signing keys.

**Policy 2 - If Phishing-resistant MFA is not implemented yet, then an alternative MFA method SHALL be enforced for all users**.
Comment: This is a "fallback" policy that is only applicable when an agency cannot implement phishing-resistant MFA for all its users yet due to technical or business constraints. This policy is only checked if Policy 1 fails because if Policy 1 passes there is no need for this policy. This policy is the same as the one we currently have named "MFA SHALL be required for all users" with a wording update and is checked in ScubaGear by looking for a conditional access policy that requires MFA (but does not specify the type) to access the tenant - therefore the existing Rego code can be re-used.

**Policy 3 - If Phishing-resistant MFA is not implemented yet and Microsoft Authenticator is enabled, it SHALL be configured to show the user context information when logging in via the app**.
At this time, Azure AD supports the context information application name and geographic location. Number matching is enabled by default and cannot be disabled.

**Policy 4 - The Authentication Methods Manage Migration feature SHALL be set to Migration Complete**.
Justification: By configuring the Manage Migration feature to Migration Complete, we ensure that the tenant has disabled the legacy authentication methods screen (which was not available via the API to be checked by ScubaGear). This also ensures that the MFA and SSPR authentication methods are both managed from a central screen thereby reducing administrative complexity and reducing the chances of security misconfigurations.

Comment: Policy 4 will be removed from the baseline/ScubaGear in 2024 because Microsoft is fully deprecating the legacy MFA and SSPR authentication methods administration pages at that time. At that point tenants will effectively be at the state of Migration Complete automatically.

**Policy 5 - The authentication methods SMS, Voice Call and Email OTP SHALL be disabled**.
Comment: This policy will only be checked if the tenant has their Manage Migration feature set to Migration Complete because the configuration data is not available from the legacy authentication methods page.

**Policy 6 - Phishing-resistant MFA SHALL be required for Highly Privileged Roles**.
Comment: This will be implemented and assessed using authentication strength just like policy bullet 1 above, except that this policy is scoped to privileged roles. This policy replaces existing policy 2.13 Multifactor Authentication SHALL Be Required for Highly Privileged Roles.

**Policy 7 - Managed Devices SHOULD be required to register MFA**.
Justification: This can help mitigate scenarios where hackers steal unused account credentials and then register their own MFA devices to access the tenant by meeting the MFA requirement.

Technical implementation:
	Include All users
	Cloud apps or actions > User actions > Register security information
	Grant > Grant access > Require device to be marked as compliant or Require Hybrid Azure AD joined device

**Comment by tkol2022** [comment]
To get the MS Authenticator configuration data from the tenant and see examples of the settings in practice, reference issue #313.

**Comment by ssatyapal123** [comment]
Thanks Ted, it looks great. It's nice to see them all in a group. Here are a few initial comments:

- For policies 1, 2, 3, 6, 7, recommend adding "when ALWAYS" to emphasize there are no conditions under which MFA would not apply (based on recommendation from John Craddock: https://www.youtube.com/watch?v=CLoou-n197k&t=341s)
- Policy 3 is a bit long and I remember Ethan had asked they be short and succinct.  I understand why it reads that way, so as to keep the policies unique with a unique ID. Would it make sense to have a separate group for Non-Phishing-resistant MFA? Just a thought. See this image from the YouTube link for example CAPs:

![image](https://github.com/cisagov/ScubaGear/assets/78565245/98f76446-cb6d-4e83-ae68-48d9ec4620ed)

**Comment by gdasher** [comment]
I think we need to add more guidance around federated ADFS auth.  I'm not sure we can make a SHALL to not use it given that its totally ubiquitous today.  As much as I want that to be the case, I think its a bridge too far.

While I want to agree with the idea of setting the requirement with cloud native auth, the reality is that most agencies won't do that currently (since CBA is so new--even the most advanced ones are just starting to look at migration).  To account for that, I would like to ensure we have language in the implementation considerations for policy 1 and 2 that talks about this situation.  We can state that it is:

a) Federated PIV auth IS permitted by the plain text of the policy, but not preferred (versus other methods implemented in the cloud).  That is, update our graphic to show it a cut below the others.
b) That it is impossible to check via the tool and will show up as red (ie, keep the rego implementation exactly as you have described it)
b) That, if implemented, requires enforcing PIV usage on-prem via [User Based Enforcement](https://playbooks.idmanagement.gov/piv/network/group/).


The other policies LGTM.

**Comment by ssatyapal123** [comment]
\@gdasher Thank you!  I updated the figure and working on the text as well now.

![Image](https://github.com/cisagov/ScubaGear/assets/78565245/e91957b5-8419-4b4e-8e4a-8895c52e94ce)

**Comment by tkol2022** [comment]
For policy 3 related to MS Authenticator refer to #295 for details and screenshots.

**Comment by tkol2022** [comment]
Closing since this was addressed via #379
