### ISSUE TITLE
AAD 2.11 - Update Rego code to check for a maximum allowed Global Admins of 8 instead of 4

### ISSUE THREAD

**Issue by ssatyapal123** [cisagov/ScubaGear#332]
# 💡 Summary #
This issue addresses the feedback from the agency pilots that Policy 2.11 is unrealistic, with most agencies failing as they had more than four Global Admins. The current Policy requirement is for the number of Global admins to be between 2 and 4. The average from the pilots (after removing outliers) was approximately 8 Global admins. Therefore, this issue is to make a code to change to allow for a maximum of 8 Global admins (including "breakglass" accounts.)

## Motivation and context ##
Make ScubaGear more relevant to Agencies by setting the maximum Global Admins to an achievable target.

## Implementation notes ##
The Rego code in AADConfig.rego for Policy 11 requires the following changes (see bolded text):

#################
# Baseline 2.11 #
##################
# Baseline 2.11: Policy 1
#--
GlobalAdmins[User.DisplayName] {
    some id
    User := input.privileged_users[id]
    "Global Administrator" in User.roles
}

tests[{
    "Requirement" : "A minimum of two users and a maximum of **eight** users SHALL be provisioned with the Global Administrator role",
    "Control" : "AAD 2.11",
    "Criticality" : "Shall",
    "Commandlet" : ["Get-MgSubscribedSku", "Get-PrivilegedUser"],
    "ActualValue" : GlobalAdmins,
    "ReportDetails" : ReportFullDetailsArray(GlobalAdmins, DescriptionString),
    "RequirementMet" : Status
}] {
    DescriptionString := "global admin(s) found"
    Conditions := [count(GlobalAdmins) < **9**, count(GlobalAdmins) >= 2]
    Status := count([Condition | Condition = Conditions[_]; Condition == false]) == 0
}
#--

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Rerun AAD policy 2.11 to ensure that a maximum of up to 8 global admins will reflect a pass.

**Comment by tkol2022** [comment]
@ssatyapal123 The code change for this was incorporated into PR #408 so there is no need for a separate fix branch for this. I will assign you a new issue.
