### ISSUE TITLE
Explicility state criticality in product markdown 

### ISSUE THREAD

**Issue by crutchfield** [cisagov/ScubaGear#341]
# 💡 Summary #
The criticality of a control/policy is generally embedded in the description.  An explicity statement of criticiality would allow for further automation.  

## Motivation and context ##

Better aligns product markdown (i.e., secure baseline) with software baseline via automation, 

## Implementation notes ##

Please provide details for implementation, such as:

- Update markdown with criticality for each policy
- Parse markdown to get criticality
- Use provided criticality instead of hard coded in rego files. 

## Acceptance criteria ##

How do we know when this work is done?

- [ ] All criticality is explicitly stated in markdown
  - [ ] AAD
  - [ ] Defender
  - [ ] Exchange
  - [ ] OnedriveSharePoint
  - [ ] PowerBI
  - [ ] PowerPlatform
  - [ ] Teams
- [ ] Rego uses provided criticality (No hardcoded criticality).

**Comment by nanda-katikaneni** [comment]
Need feedback from Grant. 
Suggestion for Emerald Release: make Baseline document changes to add an additional field for each policy.
Rego changes can be done as part of Flipper through a separate issue.
