### ISSUE TITLE
Refactor ReportDetailsArray 

### ISSUE THREAD

**Issue by crutchfield** [cisagov/ScubaGear#342]
# 💡 Summary #

Several products use a ReportDetailsArray function in the rego code.   The functions shoul dbe refactored out to a common utils package. 

## Motivation and context ##

Why does this work belong in this project?

This would be useful because it will reduce maintenance costs.

## Implementation notes ##

Refactor ReportDetailsArray in products rego code and move to Rego/Utils/ReportUtils.rego.
Update Rego to used refactored functions
Update Rego tests ti used refactored test as appropriate

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Code inspection shows refactored functions.
- [ ] ALl Unit tests pass

**Comment by Sloane4** [comment]
being addressed in PR #642

**Comment by Sloane4** [comment]
being addressed in PR #642
