### ISSUE TITLE
AAD 2.10 ScubaGear Change to Deprecate Browser Persistence Policy

### ISSUE THREAD

**Issue by ssatyapal123** [cisagov/ScubaGear#346]
# 💡 Summary #

What is the work, as a high-level summary?
Based on feedback from pilot agencies, AAD Policy 2.10 "Browser Sessions SHALL not be Persistent" is not being met. This policy aligns with NIST SP 800-63B. However, most agencies are using compensatory controls (e.g., corporate managed devices, strong authentication) making this policy unnecessary. (related baseline update issue: #269)

## Motivation and context ##

Why does this work belong in this project?

Improve the baseline policies by removing policies that are widely considered unnecessary due to the existence of policies that offer the same protection.

Removing this policy would be useful because it would improve usability without compromising security for Federal agencies.

## Implementation notes ##

Please provide details for implementation, such as:

- Policy 2.10 will no longer be checked by ScubaGear

## Acceptance criteria ##

How do we know when this work is done?

- [ ]  Verify that removing this policy doesn't break implementation of the other policies

**Comment by tkol2022** [comment]
The code change for this was incorporated into PR #408 so there is no need for a separate fix branch for this.
