### ISSUE TITLE
AAD 2.14 bugs (in implementation instructions and tool)

### ISSUE THREAD

**Issue by gdasher** [cisagov/ScubaGear#347]
# 🐛 Summary #

In an agency environment using AAD PIM, we encountered several bugs with the implementation of AAD 2.14.

## To reproduce ##

1. Run ScubaGear on Agency environment
2. Review results of AAD 2.14

## Expected behavior ##

The agency is using Privileged Access Groups to manage AAD PIM.  This means that PIM is done wirth respect to whether the user joins the group or not, but the group has a permanent assignment to the role.  The tool flags this as being managed outside of PIM.

Additionally, the tool and implementaton guide requires that assignments are active for max 15 days.  This is likely too short as it would require renewing break glass membership and Privileged Access Group membership biweekly, which is not realistic.  This should be relaxed to a more realistic value.

## Any helpful log output or screenshots ##

Please contact me offline for detailed logs.

**Comment by tkol2022** [comment]
We are changing policy 2.14 in Emerald. See #254 and #256 (which contains the text of the new policy) for details.
I think that might impact this issue.

**Comment by gdasher** [comment]
Yes I think those issues address several of these points.  The privileged access groups appears to still need a tool fix.  We can rescope this based upon the work done in those two issues.

**Comment by ssatyapal123** [comment]
After reviewing the issues above, below is a summary of findings:
- Policy 2.14 fails for permanent assignments of "Global Administrator" in all cases (breakglass accounts, allowable exclusions) #256 bullet one addresses this bug.
- Believe one question remaining is the use of Groups for PIM.  Section 1.2 (Assumptions") suggests using a group named "emergency users", however, the CIS does not suggest using a group, but creating generic "emergency accounts". **Question for this issue:** Should the baselines be modified to describe PIM for groups? Currently, the use of groups to access privileged roles is not well defined in the policy and doesn't address the just-in-time aspect of group membership. There is a new feature in preview for assigning JIT membership or ownership of groups. See https://learn.microsoft.com/en-us/azure/active-directory/privileged-identity-management/groups-assign-member-owner. As this is still in Preview, should this issue be in Emerald or later?

**Comment by gdasher** [comment]
On the groups for PIM feature:

* Not suggesting we recommend using the feature as a baseline since its in preview, but I do think it would be helpful to update the rego to not flag it as a policy violation if being used
* CISA OCIO is using it, I believe per a recommendation from Microsoft.  I'm not exactly sure why--I am trying to find out.
* On timeline, if it can't be had in emerald I think its ok--I would just request we document that there can be false positive violations for this control when using PIM for Groups.

**Comment by tkol2022** [comment]
I'm currently testing the PIM for Groups feature to determine how it specifically impacts each of the Azure AD policies related to PIM and will follow-up with a separate comment for that. This comment is to provide a reference for how the PIM for Groups feature works and its relationship to role assignments within the context of the highly privileges roles we include in the security baseline. In the example below I demonstrate how to bring a group into management by PIM, how to assign a user to a PIM group as eligible and how to assign the PIM group to privileged roles as eligible. Then I show how when the test users logs in, once he activates his group membership, he then sees two new privileges roles which he can then activate.

In Azure AD, I created Ted's PIM Test Group
In PIM Manage > Groups, I clicked Discover Groups and brought Ted's PIM Test Group into management under PIM
![image](https://github.com/cisagov/ScubaGear/assets/107076927/3b6ef714-c9b6-4b18-96e2-eae1804cffb8)

In PIM Manage > Groups, I clicked Ted's PIM Test Group and then Manage > Assignments > Eligible Assignments, I assigned test user Alex.
![image](https://github.com/cisagov/ScubaGear/assets/107076927/729be781-baca-48c4-bb6f-fa3b6623d16f)

In PIM Manage > Azure AD Roles > Manage > Assignments > Eligible Assignments, I assigned Ted's PIM Test Group to the Exchange Administrator and Sharepoint Administrator highly privileges roles.
![image](https://github.com/cisagov/ScubaGear/assets/107076927/4728ff66-fdde-4548-9940-b569ad4a1a91)

I logged in as Alex and took a look at his available role assignments.
![image](https://github.com/cisagov/ScubaGear/assets/107076927/e99c922f-61fb-420f-b51b-a1c281f24ec1)

I then activated Alex's membership in Ted's PIM Test Group
Once I activated his group membership, when I clicked on his My Roles page, I could see the Exchange Administrator and Sharepoint Administrator as eligible assignments (they were not there before I activated his group membership)
![image](https://github.com/cisagov/ScubaGear/assets/107076927/ca865eca-e79a-4c39-88c8-162e43dc4235)

**Comment by gdasher** [comment]
Thanks.  There is also a use case where the the group has a permanent active assignment to the role, but no permanent membership, using PIM to transiently join the group.  You may want to note that use case as well (versus this you note case which is almost like a double-level PIM)

**Comment by tkol2022** [comment]
Please see #376 for a detailed impact analysis on five Azure AD policies (and ScubaGear code) that I believe may be impacted by the PIM for Groups feature. This includes the case mentioned by @gdasher where " the group has a permanent active assignment to the role, but no permanent membership, using PIM to transiently join the group."

**Comment by tkol2022** [comment]
This is a response to the two comments left when this issue was originally opened. I want to be sure we adjudicate them.

> The agency is using Privileged Access Groups to manage AAD PIM. This means that PIM is done with respect to whether the user joins the group or not, but the group has a permanent assignment to the role. The tool flags this as being managed outside of PIM.

@gdasher Can you clarify what you mean by "the tool flags this as being managed outside of PIM"? Currently the tool will only flag entries in the PIM "Active" assignments API as "SHALL NOT occur outside of a PAM system" when the active assignment entry has a Start Time of null and and End Time of Permanent. This occurs for example if an admin uses the Microsoft 365 Admin Center to directly assign a user or a group to a role instead of using the PIM assignment portal. Maybe we can update the instructions so that if an agency is using PIM for Groups, they make the permanent active assignment of the group to a role using the PIM for Roles portal instead of making the assignment externally (via the M365 Admin Center or cmdlet)? I think this will ensure that the active assignment entry will have a defined Start Time (will not be null) and thus the agency won't fail this specific policy check.

 
> Additionally, the tool and implementation guide requires that assignments are active for max 15 days. This is likely too short as it would require renewing break glass membership and Privileged Access Group membership biweekly, which is not realistic. This should be relaxed to a more realistic value.

We are getting rid of the 15 days check because the policy is no longer going to be checking for the PIM configuration setting "Allow permanent active assignment", therefore the check of # of days is OBE.

**Comment by tkol2022** [comment]
> Per parking lot discussion, adjust this issue as appropriate (scope, split, etc) to at least address as a note in current ScubaGear implementation of the issue with PIM for Groups.

@ssatyapal123 I'm thinking that we might want to put a note in the policy items impacted by PIM for Groups and say something like "This policy will be augmented in the next release to include functionality provided by the PIM for Groups feature." See #376 for a list of the impacted policies.
It might be good to put a warning in the README file as well? Open to ideas.
