### ISSUE TITLE
Update ScubaGear AAD 2.18 guest user access restrictions per feedback received

### ISSUE THREAD

**Issue by tkol2022** [cisagov/ScubaGear#349]
# 💡 Summary #

Update ScubaGear Azure AD policy check for 2.18 guest user access restrictions to allow both "limited" access and "restricted" access. Both settings are acceptable. See #348 for details.

## Acceptance criteria ##

How do we know when this work is done?

- [x] Rego code and test cases are updated and unit tested
- [x] Updates are tested in all test tenants

**Comment by adhilto** [comment]
This has actually been implemented in the Rego for some time. Easy win 😄
