### ISSUE TITLE
Finalize standard front matter and other content that will be included in all baselines

### ISSUE THREAD

**Issue by tkol2022** [cisagov/ScubaGear#352]
# 💡 Summary #

We received comments about the applicability of the security baselines to non-government organizations. We also received suggestions to define SHALL versus SHOULD and other changes that affect the content at the front matter of all baseline documents.

The scope of this issue is to **finalize the standard content and then update the Azure AD baseline**.
Once this standard content has been reviewed and finalized, we will then create a separate issue to update all the baseline documents.

## Implementation notes ##

- [ ] Finalize the content explaining the applicability of the baselines. See below.

CISA views its configuration guides as risk management through technical controls. The SCuBA project created a baseline tailored to the federal government’s threats and risk appetite with the knowledge that every organization has different threat models and risk appetites. Non-governmental organizations may find value in applying these baselines to reduce risks.

The information in this document is being provided “as is” for INFORMATIONAL PURPOSES ONLY. CISA does not endorse any commercial product or service, including any subjects of analysis. Any reference to specific commercial entities or commercial products, processes, or services by service mark, trademark, manufacturer, or otherwise, does not constitute or imply endorsement, recommendation, or favoritism by CISA.

- [x] Finalize the definition of SHALL versus SHOULD.
- [x] Update the baselines to reference the hybrid identity solutions architecture document.
- [x] Update the Acknowledgements section to include the language below.

The M365 security baselines were informed by materials produced by the following organizations and others:
Center for Internet Security
Internet Engineering Task Force
Mandiant
Microsoft
U.S. Defense Information Systems Agency
U.S. National Institute of Standards (NIST)
U.S. Office of Management and Budget (OMB)

- [ ] Include the language below at the beginning of each baseline per @ahuynhMITRE email.

The Secure Cloud Business Applications (SCuBA) project provides guidance and capabilities to secure agencies’ cloud business application environments and protect federal information that is created, accessed, shared, and stored in those environments. The SCuBA Secure Configuration Baselines (SCB) for Google Workspace (GWS) / Microsoft 365 (M365) will help secure federal civilian executive branch (FCEB) information assets stored within GWS/M365 cloud environments through consistent, effective, modern, and manageable security configurations.

**Comment by tkol2022** [comment]
@gdasher Can you kindly provide definitions for SHALL versus SHOULD that you would like to include in the baseline? Also, where would you like the reference to the hybrid solutions document, what should that say and what URL should that reference?
Thanks!

**Comment by adhilto** [comment]
Or did they mean _SHOULD_ incorporate? :smile:

**Comment by tkol2022** [comment]
@gdasher Can you please provide a sentence or two on what you want included regarding the Hybrid Identity document?

Do you want that at the top of the AAD baseline? In other baselines as well or just AAD?

**Comment by tkol2022** [comment]
@gdasher pinging again. See previous comment.

**Comment by ahuynhMITRE** [comment]
current status is that the front-matter and acknowledgements have been submitted to CISA for review!

**Comment by ahuynhMITRE** [comment]
front matter and acknowledgements have been approved by CISA and updated in the example markdown
