### ISSUE TITLE
Baseline Implementation Section Style Guide

### ISSUE THREAD

**Issue by Dylan-MITRE** [cisagov/ScubaGear#361]
# 💡 Summary #

Came up a style guide for baseline implementation section

## Motivation and context ##

Inconsistency for implementation section for baseline, recommended to came up with a style guide to keep the baseline language consistent 

## Acceptance criteria ##

How do we know when this work is done?

- [x] came up with style guide for the Implementation Section

**Comment by ahuynhMITRE** [comment]
For consistency across the baseline products the style guide for the implementation will be the following:

- [ ] One implementation section per policy group
- [ ] Each policy will have its own implementation steps
- [ ] Each policy implementation will begin with the Policy ID followed by ", to [VERB] _____ follow the instructions below:"
- EXAMPLE: MS.AAD.1.1v1, to block legacy authentication follow the instructions below:

NOTE: the above checklist will be added to #212 as a final check to ensure the implementation sections are consistent 

With the following updates the implementation section, it will look like the following:

Policies
MS.PRODUCT.1.1v1
Blah blah blah

#### MS.PRODUCT.1.2v1
Blah blah blah

#### MS.PRODUCT.1.3v1
blah blah blah

Implementation
MS.PRODUCT.1.1v1, to block XXX follow the instructions below:

MS.PRODUCT.1.2v1, to enable XXX follow the instructions below:

MS.PRODUCT.1.3v1, to restrict XXX follow the instructions below:

**Comment by ahuynhMITRE** [comment]
Tagging the baselines POCs below for awareness on the way forward in regards to the the implementation section:
@Dylan-MITRE @schrolla @tkol2022 @adhilto @buidav @amart241 @nanda-katikaneni @ssatyapal123 @Sloane4

**Comment by adhilto** [comment]
Will the implementation sections still be moved to a wiki? Or will they be in-line in the baseline docs themselves?

**Comment by ahuynhMITRE** [comment]
@adhilto current plan is still to migrate them to a wiki but having one implementation section per policy group will help with that lift and shift and minimize human and structural errors.
