### ISSUE TITLE
Teams Policy 3 (MS.TEAMS.3.1v1) - 'Implementation' steps need to be revised 

### ISSUE THREAD

**Issue by nanda-katikaneni** [cisagov/ScubaGear#363]
# 💡 Summary #

Modify M365 Teams baseline policy 3 as per the instructions below.

Motivation and context
Based on the pilot and internal feedback, the existing  implementation steps are ambiguous and needs a revision.

Implementation notes
The Implementation section step #4, suggest adding a recommendation for what it SHOULD be set to. Possible language for this: "... ensure Automatically admit people is NOT set to Everyone. Automatically admit people" SHOULD be set to "People in my organization", though other options MAY be used if needed.
 
Acceptance criteria
Updated policy has the changes noted in Implementation notes.

**Comment by ahuynhMITRE** [comment]
Closed when merged as part of PR #461
