### ISSUE TITLE
Inconsistent section ordering in baseline documents

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#371]
# 🐛 Summary #
Some of the sections are not ordered the same across the different product baseline policy documents.  Specifically, the `Assumptions` and `Resources` sections are ordering is reversed in PowerBI and SharePoint compared to the others.  The order of these sections across the baselines is as follows:

| Baseline | Ordering |
| ------------- | ------------- |
| AzureAD | Assumptions then Resources |
| Defender | Assumptions then Resources|
| Exchange | Assumptions then Resources|
| OneDrive |Assumptions then Resources |
| PowerBI | Resources then Assumptions|
| PowerPlatform | Assumptions then Resources |
| SharePoint | Resources then Assumptions |
| Teams | Assumptions then Resources |

## To reproduce ##

1. View each baseline and notice the `Assumptions` and `Resources` section ordering

## Expected behavior ##

The expectation is that the baselines have the same structure and ordering of sections to make it easier for readers to follow any of them and find relevant sections easily.  The specific ordering matters less than consistency in the ordering.

**Comment by ahuynhMITRE** [comment]
Suggestion to update markdowns to be ordered Assumptions then Resources due to the majority of the baselines being ordered in this fashion. Also a suggestion to add this to #212 since it can be viewed as a structural adjudication task.
