### ISSUE TITLE
Update automated functional testing orchestrator to be data driven

### ISSUE THREAD

**Issue by tkol2022** [cisagov/ScubaGear#377]
# 💡 Summary #

Following the Hackathon I had worked on an automated functional test script using Pester that validates ScubaGear policy outputs. The script sets the test tenant to non-compliant and compliant states using Powershell cmdlets and then executes ScubaGear. It checks the output JSON to ensure that the results of each policy check are as expected (i.e. if the tenant is in a compliant state the output should be Pass and vice-versa). The script currently automates the functional testing of the existing Sharepoint baseline. It has been used to perform functional validations of Sharepoint bug fixes in a prior release.

The scope of this issue is to update the design/code of the test orchestrator so that it is data-driven and therefore reduce code duplication. By data-driven we mean that test cases can be coded in generic code blocks and then passes a series of distinct input values, then the test will run once for each of those input values. Each input value represents a distinct test case and expected output (Pass or Fail).

We also flirted with the idea of having the Pester validation tests be driven by data in input files separate from the Pester code.

The goal of this is so that we can use automated functional testing as much as possible during the Emerald release test cycle. We may start with a few products during this release as time permits and then expand the automation coverage to more products during the next release. We also will be working on this issue in conjunction with issues already assigned to Emerald to minimize schedule impacts.

## Implementation notes ##

- [ ] Update the design / code as per the explanation above. Use the existing Sharepoint tests as a starting point since they are already coded.
- [ ] Test the code to ensure that it produces accurate results.

**Comment by crutchfield** [comment]
@tkol2022  I did made changes to demonstrate a data driven approach.  I also briefed to the team and provided writeup on data to collect during Emerald test pahse for each product.  Do we want to close this and open new PR for automating ONeDrive/SharePoint functional testing.

**Comment by crutchfield** [comment]
Prototyped data driven approach.  Presented test plan template (in YAML format) to team for review.  Closing this issue.  Opened #419 & #420 to automate AAD adn SharePoint/OneDrive respectively.
