### ISSUE TITLE
Teams Policy MS.TEAMS.3.1v1 requires clarification

### ISSUE THREAD

**Issue by crutchfield** [cisagov/ScubaGear#382]
# 🐛 Summary #

The policy is not clear on how to treat global vs. custom policies.  Rego implementation only checks against global - not against and custom policies.  The baseline itself may require some clarification to make it match what the Rego code is assessing OR the Rego code needs to be updated to accurately assess the baseline policies as written.

## To reproduce ##

1. Select a custom meeting policy
2. Set "People dialing in can bypass the lobby" to "on"
3. Set "Who can bypass the lobby" to "Everyone" 

## Expected behavior ##

The expected behavior is that if a Teams administrator creates a custom policy that allows "Everyone" to bypass the lobby or allows dial in users to bypass the lobby, that ScubaGear will report MS.TEAMS.3.1v1 as failing and report which policies (Global and/or custom policy names) are failing.

**Comment by crutchfield** [comment]
@schrolla I assigned to you to add any clarifications.

**Comment by nanda-katikaneni** [comment]
Teams policies 3.xv1 are being rewritten to clarify this setting for global/custom policies. 

The current (as-is) policies are written in a round about way: there are three policies that define the secure configuration. Then fourth and fifth policies are provided to define the scope. Think this is confusing and not consistent with other product policies. See below: sub-policies 3.1, 3.2, 3.3 define what is the config:

MS.TEAMS.3.1v1: Anonymous users, including dial-in users, SHOULD NOT be admitted automatically.
MS.TEAMS.3.2v1: Internal users SHOULD be admitted automatically.
MS.TEAMS.3.3v1: B2B guest users MAY be admitted automatically.

Then a separate 3.4 policy is defined to specify that above three should be at global; and 3.5 to specify the conditions for custom policies.
MS.TEAMS.3.4v1: MS.TEAMS.3.1.1, MS.TEAMS.3.2.1, and MS.TEAMS.3.3.1 SHOULD be applied in the Global (Org-wide default) meeting policy.
MS.TEAMS.3.5v1: Custom meeting policies MAY be created that allow more flexibility for specific users.

The modified (to-be) policy will look like this:
MS.TEAMS.3.1v1: Anonymous users, including dial-in users, SHOULD NOT be admitted automatically in the Global (Org-wide) policy. 
MS.TEAMS.3.2v1: Internal users SHOULD be admitted automatically in the Global (Org-wide) policy.
MS.TEAMS.3.3v1: B2B guest users MAY be admitted automatically n the Global (Org-wide) policy.
Then conditions for the custom policy:
MS.TEAMS.3.4v1: Custom meeting policies MAY be created that allow more flexibility for specific users (with language that indicates this should not be the default global config). 

Comment/discuss if the proposed change (being worked in a dev branch that is yet to be merged into emerald) is enough or we have to go beyond above clarification.

**Comment by nanda-katikaneni** [comment]
MS.TEAMS.3.xv1 has been updated through PR #462. Closing.
