### ISSUE TITLE
Teams third party apps restriction not producing accurate results in certain scenarios

### ISSUE THREAD

**Issue by tkol2022** [cisagov/ScubaGear#383]
# 🐛 Summary #

The ScubaGear MS Teams policy 2.8 or MS.TEAMS.8.2v1 "Agencies SHOULD NOT allow installation of all third-party apps or custom apps, but MAY allow specific apps as needed" **produces a Fail (non-compliant) in certain scenarios when it should produce a Pass**.

_Note: This issue describes the problem for the "third-party apps" setting but I believe the same problem could occur for the "custom apps" setting as well. You should test that and incorporate the fix if needed._

_Also, the terminology regarding the different settings screens can be confusing. Apparently there are two separate screens: the **Org-wide app settings** screen and the **Global (Org-wide default) policy settings** screen. Read the expected behavior for details on the two screens._

## To reproduce ##

1. Go to Teams Admin portal > Teams apps > Permission policies
2. Open the Global (Org-wide default) policy
3. Change the Third-party apps option to Allow all apps (you might need to press Save at this step to reproduce the behavior - not sure)
4. Click the Org-wide app settings button at the top (I noticed in commercial tenants you need to navigate to Teams apps > Manage apps to see the Org-wide app settings button).
5. Under Third-party apps set the configuration to Off
6. Click save on the Org-wide app settings screen
7. Click save again on the Global (Org-wide default) policy page
8. Open Teams as a test user and you will see that you cannot install third-party apps
9. Run ScubaGear and you will see that the code produces a fail (Warning) in the report

## Expected behavior ##

The **Org-wide app settings** for Teams take priority over the **Global (Org-wide default) policy settings**. Therefore since the Org-wide app setting is set to Off (i.e. block third party apps), then it does not matter what the data value is for the Global (Org-wide default) policy setting. Teams will enforce the blocking of third party apps. I verified via hands-on testing.

Since this is the case, I would expect ScubaGear to produce a Pass (requirement met = true) in this scenario.

## Potential Problem in the Code ##

I think what might be happening is that the code is not looking at the Org-wide app setting. It is only looking at the Global (Org-wide default) policy setting.

## Screenshots ##

See below - The installation of third-party apps is disabled in the Org-wide app setting and therefore overrides the Global (Org-wide default) policy setting
![image](https://github.com/cisagov/ScubaGear/assets/107076927/e859716c-c31f-49c3-9e83-6a3302f189a8)

See below - Teams is enforcing the "no third-party apps" restriction because all of the third party apps that were previously installed disappeared and I was unable to install any more.
![image](https://github.com/cisagov/ScubaGear/assets/107076927/f585a423-9d3c-4329-9d43-18b15b46b290)

See below - This was the value set in the Global (Org-wide default) policy setting before I disabled third party apps in the Org-wide app setting. The code is only looking at this setting's value now and I think this could be the problem.
![Teams third party apps bug 2](https://github.com/cisagov/ScubaGear/assets/107076927/37facd2a-c9b7-4c63-b282-5ea75d62eb7d)

See the incorrect policy result below
![image](https://github.com/cisagov/ScubaGear/assets/107076927/aec2dd6c-a629-4f82-a020-cd260f2a6424)

**Comment by tkol2022** [comment]
I noticed in commercial tenants that you need to navigate to Teams apps > Manage apps to see the Org-wide app settings button.

![image](https://github.com/cisagov/ScubaGear/assets/107076927/79827098-9fdb-47b0-b727-a62333173029)

**Comment by ahuynhMITRE** [comment]
Closed when merged as part of PR #397
