### ISSUE TITLE
Add support for custom DKIM selectors (Agency 2 Pilot: EXO 2.3; Investigate DKIM failures)

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#39]
Agency 2 manages their DKIM policy outside of EXO but could still verify they meet the policy via DNS lookups. We should investigate why they failed.

**Comment by gdasher** [comment]
DKIM analysis is based on pulling configuration from the tenant and from DNS.  Further, the selectors are hard coded to the selectors used by M365 itself (selector1, selector2).  This doesn't handle the case of agencies using 3p DNS gateways.

I believe the proper solution is to use the config file and allow agencies to further configure things, specifying expected non-default selectors when domains leverage mail routing before sending to m365.

**Comment by gdasher** [comment]
Discussed as a group.  Consensus is proposed solution is reasonable.  Pending resources.
