### ISSUE TITLE
Update AAD ScubaGear code to align to revised baseline

### ISSUE THREAD

**Issue by tkol2022** [cisagov/ScubaGear#395]
# 💡 Summary #

We made significant structural changes to the AAD baseline during Emerald. The ScubaGear code needs to be revised to align with the new baseline document.

Note: This issue does not include writing code for new policies or adjusting the algorithm of any existing policies to match the new policy logic in the baseline document. Those will be handled in separate issues. This work is only to align the structure (policy IDs, group titles, etc.) with the baseline document.

## Implementation notes ##

- [ ] Review the new AAD baseline
- [ ] Update code to place the policies into their appropriate new groups
- [ ] Renumber the policies to match the baseline
- [ ] Delete any policies in the code that are no longer in the baseline document

**Comment by tkol2022** [comment]
This issue is blocked until I release a stable version of the new AAD baseline document. See email for details.

**Comment by Sloane4** [comment]
@tkol2022 is this unblocked now or am I supposed to wait for #379 to merge in?

**Comment by tkol2022** [comment]
Still blocked. I'm working with @nanda-katikaneni to get it merged in today.
