### ISSUE TITLE
AAD Check Password Expiration

### ISSUE THREAD

**Issue by adhilto** [cisagov/ScubaGear#398]
# 💡 Summary #
We currently have MS.AAD.8.1v1 ("User passwords SHALL NOT expire") marked as not implementable, but it can be checked via `Get-MgDomain.`

## Motivation and context ##
We marked it as not implementable because as far as we knew, the only way to check this programmatically was deprecated. However, yesterday someone commented on a [thread ](https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1416#issuecomment-1603501851)I had opened about a year ago with the Graph commandlet we need to do this.

## Implementation notes ##
![image](https://github.com/cisagov/ScubaGear/assets/106177711/415dbd72-c912-4552-a2f5-15b653937396)
![image](https://github.com/cisagov/ScubaGear/assets/106177711/554efe04-0498-4887-affe-7dce6105177f)
![image](https://github.com/cisagov/ScubaGear/assets/106177711/1cfcf2c4-0325-4d5f-b2f3-8c46709bdf08)
![image](https://github.com/cisagov/ScubaGear/assets/106177711/89f614e2-4cda-4e1d-b1e6-3bc9a8eea4a5)

## Acceptance criteria ##

How do we know when this work is done?

- [ ] The report output by ScubaGear correctly reflects whether or not passwords expire in the user's tenant.

**Comment by mitchelbaker-cisa** [comment]
Updated policy number is [MS.AAD.6.1v1](https://github.com/cisagov/ScubaGear/blob/main/baselines/aad.md#msaad61v1)
