### ISSUE TITLE
Azure AD Baseline / PIM Alerting > add link to MS PIM Alert documentation

### ISSUE THREAD

**Issue by vco-s** [cisagov/ScubaGear#4]
Hello,

About [Azure AD PIM Monitoring section](https://github.com/cisagov/ScubaGear/blob/main/baselines/aad.md#2162-resources), I suggest to add a link to the MS documentation related to PIM alerts: https://learn.microsoft.com/en-us/azure/active-directory/privileged-identity-management/pim-how-to-configure-security-alerts

**Comment by ethanb-cisa** [comment]
Thanks for your feedback! We will review this suggestion for inclusion in the next release of the baselines. 

Please open a new issue if you have more feedback.

**Comment by ethanb-cisa** [comment]
Closing all `baseline-document` issues to make it easier to track outstanding code issues. If we have questions on your feedback, we'll re-open this issue.
