### ISSUE TITLE
Implement new AAD Rego policy MS.AAD.3.4v1 Manage Migration feature SHALL be set to Migration Complete

### ISSUE THREAD

**Issue by tkol2022** [cisagov/ScubaGear#411]
# 💡 Summary #

Implement a new Rego policy check for MS.AAD.3.4v1 The Authentication Methods Manage Migration feature SHALL be set to Migration Complete.

## Warning: Do not alter this setting in any of the tenants for unit testing purposes. This configuration setting can lock out users from the tenant. Coordinate with @tkol2022 for a list of tenants that have this setting configured.

Implementation details:

- Review the [respective instructions in the baseline document](https://github.com/cisagov/ScubaGear/blob/emerald/baselines/aad.md#msaad34v1-instructions) as a reference
- [Review this comment](https://github.com/cisagov/ScubaGear/issues/251#issuecomment-1504032220) to see the Cmdlet and fields to be used to implement this policy check.

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Test with all value variations of the Managed Migration setting to ensure a Pass or Fail are produced as expected.
- [ ] Test against all tenants.

**Comment by crutchfield** [comment]
Closed with PR #445
