### ISSUE TITLE
Update ScubaGear Rego check for MS.AAD.3.6v1 MFA required for Highly Privileged Roles to check for phishing-resistant MFA

### ISSUE THREAD

**Issue by tkol2022** [cisagov/ScubaGear#413]
# 💡 Summary #

Update the existing Rego code for MS.AAD.3.6v1 MFA for highly privileged roles to check for a conditional access policy that requires a phishing-resistant MFA method.

- There is already code that checks for MFA. For the most part that should stay the same, but the logic needs to be updated to check for Authentication Strength > Phishing-resistant MFA. See the [conditional access policy template in the baseline instructions](https://github.com/cisagov/ScubaGear/blob/emerald/baselines/aad.md#msaad36v1-instructions) as a reference.

dependsOn #433 

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Test to ensure that the code produces a Pass or Fail as expected for various Compliant/NonCompliant states of conditional access policies.
- [ ] Test against all tenants.

**Comment by crutchfield** [comment]
Closed with #441
