### ISSUE TITLE
Possible breakout of implementation steps to a wiki 

### ISSUE THREAD

**Issue by ahuynhMITRE** [cisagov/ScubaGear#422]
# 💡 Summary #

It was under the assumption that SCB updates would be expected to undergo the CISA publication and review process for publication so a suggestion for the emerald release was to breakout the implementation steps into a wiki allowing the development team to update ad hoc. 

## Motivation and context ##

If implementation step updates require going through the CISA publication and review process, the breakout to a wiki may be able to eliminate this process for products that are continually changing. 

## Implementation notes ##

- [ ] CREATE new wiki for each M365 SCB with the following:
- Group Name
- Policy ID
- Links to associated Microsoft / External article
- Implementation Steps
- [ ] REMOVE All steps in implementation section
- [ ] ADD link to newly created Wiki to the implementation section 

## Acceptance criteria ##

How do we know when this work is done?

See implementation notes above.

**Comment by tkol2022** [comment]
This issue seems OBE at quick glance.

**Comment by ahuynhMITRE** [comment]
closing due to issue is OBE
