### ISSUE TITLE
Standardize the structure and language for the mirrored Defender policies in Teams and EXO

### ISSUE THREAD

**Issue by buidav** [cisagov/ScubaGear#435]
# 💡 Summary #

Defender has multiple mirrored policies in EXO and Teams.

EXO Policy Groups 8 - 11 and 14-17
Teams Policy Groups 11 - 13

## Motivation and context ##

Update the language for the policies for the emerald release.

## Implementation notes ##
- Update the language for policies that were removed due to the switch to Preset Security Policies.
- Update the language for policies that were unaffected by the switch to Preset Security Policies.

## Acceptance criteria ##

- [x] EXO Policies have been updated
- [x] Teams Policies have been updated

**Comment by ahuynhMITRE** [comment]
moved to blocked atm to wait for Defender's merge into emerald then will add and retest structure in exo and teams.

**Comment by nanda-katikaneni** [comment]
@ahuynhMITRE - think this issue is now fixed and can be closed.

**Comment by ahuynhMITRE** [comment]
> @ahuynhMITRE - think this issue is now fixed and can be closed.

updated a few links that will be put into the PR for criticality. Will close once PR is in.
