### ISSUE TITLE
Testing ScubaGear code Changes Without Modifying the M365 Tenant

### ISSUE THREAD

**Issue by tkol2022** [cisagov/ScubaGear#442]
# 💡 Summary #

When we make code changes to ScubaGear, we need to perform a functional test of those changes against a set of M365 test tenants. The functional test usually involves modifying an M365 test tenant to a compliant state (i.e. should produce a Pass in the report) and a non-compliant state (i.e. should produce a Fail).

Some M365 configurations cannot be altered in the test tenant because: A) they might degrade the security of that tenant and/or B) they might lock out users from the tenant. A good example is the AAD conditional access policy that requires a managed device to access the tenant - it might not be feasible to turn that policy "on" since it has the potential to lock out testers.

**This issue introduces a step-by-step alternative for performing functional tests of these types of policies that doesn't require modification to the tenant**. This process is only applicable in scenarios where it doesn't make sense to alter the test tenant for reasons such as the ones described above.

**Comment by tkol2022** [comment]
## Overview
This testing process uses a special ScubaGear function named **Invoke-RunCached** to execute the tool with a local file copy of the M365 tenant's configurations (i.e. ProviderSettingsExport.json). As a tester, instead of directly modifying the tenant to configure a specific state you are testing, you will modify the local file to the configuration state and then direct ScubaGear to use the local file instead of retrieving the settings from the tenant. Below is a high-level, sequential overview of this process.

1. Execute ScubaGear normally (i.e. Invoke-SCuBA) one time to generate a fresh ProviderSettingsExport.json file. It is important to generate a **brand-new fresh copy of the tenant settings** file when you start testing code enhancements or if you are testing a pull request of someone else's code. This is because of two reasons:
   A. We want ScubaGear to execute the latest Powershell provider export function (e.g. Export-AADProvider) and generate a JSON file that contains the output of all newly added cmdlets and other Powershell code changes.
   B. We want to get the latest API results from Microsoft's cloud services. We learned from experience that these results can change over time (e.g. field deprecations)

2. Make a copy of the ProviderSettingsExport.json file and then modify the JSON to configure a specific state you are testing. For example, you might want to create a conditional access policy in the file to test a specific AAD MFA policy.
3. Execute ScubaGear with **Invoke-RunCached** and direct ScubaGear to skip connecting to the tenant and downloading the configuration by passing "**-ExportProvider $false**". You will also direct ScubaGear to look for a local copy of the tenant configuration file by passing the "**-OutPath**" parameter.
4. Examine the output report and ensure that the result of the policy evaluation (Pass or Fail) matches what you expect based on your specific functional test. Also examine other characteristics of the output (such as the message in the report Details column) to ensure they match what you expect for your test.

**Comment by tkol2022** [comment]
## Detailed Technical Process
This section describes the detailed step-by-step process including a full example with ScubaGear command line. You will need to adjust the parameters to reflect your specific environment (.e.g. working folder, product you are testing, etc.). The commands shown below are executed in Powershell.

_In the example below, I am performing a functional test of the AAD policy MS.AAD.3.8v1 "Managed Devices SHOULD be required to register MFA" which expects an AAD Conditional Access policy in the tenant matching a specific set of characteristics. The example functional test is for [pull request 416](https://github.com/cisagov/ScubaGear/pull/416) which implements the code for issue 324 and has a repo named "324-ManagedDeviceRequiredMFARegistration"._

1. If necessary, download the ScubaGear pull request code that you are testing from GitHub. If you are developing you might skip this step if you already have the latest code locally on your machine. Note: some testers prefer to download the code into a local GitHub repo (if that is the case, then replace this step with the necessary git commands).

Open a browser to the pull request page, click on the associated repository, then click Code > Download Zip. Unzip to a local directory of your choice.

![image](https://github.com/cisagov/ScubaGear/assets/107076927/4842b450-1ccc-4432-8a62-c480044fa545)

2. Create a working folder that will be used for the functional testing process. I prefer C:\Users\tkolovos\Downloads\Testing but it doesn't matter. In this folder we will store the provider JSON files that will be modified and the output of ScubaGear (i.e. the report files).

`mkdir C:\Users\tkolovos\Downloads\Testing`

3. Create a working subfolder that will be used to store a local copy of the tenant configurations for specific tests. This folder will be used to store modified copies of the provider export JSON file that reflect specific test case scenarios you are evaluating.

`mkdir C:\Users\tkolovos\Downloads\Testing\ManageDeviceForMFARegistration`

4. Navigate to the directory containing the code you are performing a functional test of (this is the code you downloaded in step 1).

`cd C:\Users\tkolovos\Downloads\ScubaGear-324-ManagedDeviceRequiredMFARegistration`

5. Import the ScubaGear module from the code version being tested.

`Import-Module -Name .\PowerShell\ScubaGear`

6. Execute ScubaGear to generate a fresh local copy of the provider json export file from the tenant.

`Invoke-SCuBA -ProductNames aad`

7. Copy the freshly generated provider json export file to the functional test working subfolder and name it ProviderSettingsExport-Compliant.json

```
cd M365BaselineConformance_2023_07_17_14_55_15
copy ProviderSettingsExport.json C:\Users\tkolovos\Downloads\Testing\ManageDeviceForMFARegistration\ProviderSettingsExport-Compliant.json
```

![image](https://github.com/cisagov/ScubaGear/assets/107076927/a15fa60f-f3f2-42b4-8024-22088c433913)

8. Open the ProviderSettingsExport-Compliant.json file in VSC and modify it to create a compliant configuration. In this example I created a conditional access policy in the JSON named "Live - Managed device required for MFA registration (test)" that matches the characteristics expected by the Scuba AAD policy. If you are testing conditional access policies make sure that the State property in the JSON is set to "enabled".

AAD Conditional Access Policy template:

	Include All users
	Cloud apps or actions > User actions > Register security information
	Grant > Grant access > Require device to be marked as compliant or Require Hybrid Azure AD joined device (for multiple controls at bottom of screen select Require one of the selected controls)

![image](https://github.com/cisagov/ScubaGear/assets/107076927/2e433dc3-a575-4ba9-aaa3-7c6ea54042a8)
![image](https://github.com/cisagov/ScubaGear/assets/107076927/d753563f-c31a-47ae-86b0-922a90cd7cba)
![image](https://github.com/cisagov/ScubaGear/assets/107076927/a4ba48b8-7063-42a3-b2e2-caa5fbfe4e7f)

**Comment by nanda-katikaneni** [comment]
This is a process to be followed by the dev team - closing.
