### ISSUE TITLE
Implement the new Teams policy MS.TEAMS.1.5v1 in Rego

### ISSUE THREAD

**Issue by nanda-katikaneni** [cisagov/ScubaGear#452]
# 🐛 Summary #

Teams baseline policies are being regrouped and reorganized. As part of this, a new sub policy has been created - the check for which is not implemented in the previous versions of ScubaGear. The policy is MS.TEAMS.1.5v1 (Dial-in users, SHOULD NOT be enabled to bypass the lobby). This sub policy is closely related to MS.TEAMS.1.3v1 and can be accomplished in one of two configurations - the earlier releases have been covering one of the config but not the other config check. New rego script has to be developed to explicitly cover the incomplete config check. 

## To reproduce ##

1. Sign in to the Microsoft Teams admin center. 
2. Select Meetings > Meeting policies.
3. Select the Global (Org-wide default) policy and Custom Policies
4. Under the Meeting join & lobby section, set 'Who can bypass the lobby' to 'People in my Org' or one of the other
5. Then set the 'People dialing in can bypass the lobby' to Off. <-- This is currently not explicitly checked and it is required per policy. 

## Expected behavior ##

The result for the config 'People dialing in can bypass the lobby' to Off should be called out in the report based on the config quoted in the reproduce steps.  

Add any screenshots of the problem here.

**Comment by crutchfield** [comment]
Adding this unit test case shows RuleOutput count does nto equal 1.  Any non-compliant meeting policy should fail 1.5 as a whole. 
 
`test_OneGoodOneBadPolicy_Incorrect if {
    PolicyId := "MS.TEAMS.1.5v1"

    Output := tests with input as {
        "meeting_policies": [
            {
                "Identity": "Tag:CustomPolicy",
                "AutoAdmittedUsers": "EveryoneInCompany",
                "AllowPSTNUsersToBypassLobby": true
            },
            {
                "Identity": "Tag:CustomPolicy",
                "AutoAdmittedUsers": "EveryoneInCompany",
                "AllowPSTNUsersToBypassLobby": false
            }
        ]
    }

    RuleOutput := [Result | Result = Output[_]; Result.PolicyId == PolicyId]

    count(RuleOutput) == 1
    not RuleOutput[0].RequirementMet
    RuleOutput[0].ReportDetails == "Requirement not met: Dial-in users are enabled to bypass the lobby"
}`

**Comment by nanda-katikaneni** [comment]
Fixed through PR #597
