### ISSUE TITLE
`SetUp.ps1` takes too long to install several modules

### ISSUE THREAD

**Issue by zbalkan** [cisagov/ScubaGear#467]
# 🐛 Summary #

`SetUp.ps1` takes too long to install several modules. Even when the modules are already installed, it takes time.

## To reproduce ##

1. Run `.\SetUp.ps1`
2. Run `.\SetUp.ps1`

## Expected behavior ##

It should take less time to install prerequisites.

**Comment by crutchfield** [comment]
@zbalkan We are pulling this into our internal development branch.  Thank you for all the feedback and help.

**Comment by zbalkan** [comment]
Hi, @crutchfield. Thanks for the information. I believe the related PR is also unnecessary at this point too. Asking for clarification.

**Comment by crutchfield** [comment]
> Hi, @crutchfield. Thanks for the information. I believe the related PR is also unnecessary at this point too. Asking for clarification.

@zbalkan Yes, the changes will flow through from our internal development branch to the main branch on our next release.  I do appriciate your help in making ScubaGear better.

**Comment by crutchfield** [comment]
Closed with #514
