### ISSUE TITLE
Integrate technical editor feedback into AAD baseline

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#484]
# 💡 Summary #

Review technical editor feedback on AAD baseline document and integrate suggestions into the baseline markdown.

## Motivation and context ##

Work belongs in emerald to ensure highest quality work and clear language prior to next release.

## Implementation notes ##

Technical editor feedback should be reviewed to:

- adjudicate comments and suggestions for action
- update baseline with spelling/grammar fixes
- incorporate comments with positive adjudication
- coordinate with technical editor for any comments/suggestions that are not implemented or are unclear

## Acceptance criteria ##

- [ ] Technical editor comments and suggestions have been addressed and integrated into the baseline

**Comment by ssatyapal123** [comment]
PR merged into emerald
