### ISSUE TITLE
Remove Suggestion to Enable Basic Auth

### ISSUE THREAD

**Issue by adhilto** [cisagov/ScubaGear#498]
# 🐛 Summary #

Update Readme to not instruct users to enable basic auth (https://github.com/cisagov/ScubaGear#errors-connecting-to-defender) for Defender. Instead, if they see that error, they should update to the latest Exchange online module. https://learn.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps#updates-for-the-exo-v3-module

EXO prior to version 3 required this. However, the latest version of Exchange (which is already enforced by https://github.com/cisagov/ScubaGear/blob/main/PowerShell/ScubaGear/RequiredVersions.ps1). does not. No need to instruct users to enable a less secure protocol.

## To reproduce ##
Run ScubaGear against the Defender baseline. Note that you no longer need to run https://github.com/cisagov/ScubaGear/blob/main/AllowBasicAuthentication.ps1.

**Comment by gdasher** [comment]
glad to see that security & compliance api no longer depends on remote powershell :)
