### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by DeanGross** [cisagov/ScubaGear#5]
# 🐛 Summary #

The instructions tell us to run the setup.ps1 file but nothing about what we need to do before this step. Are supposed to clone the repo, download some files, or something else.  A little bit of extra help for newbies would be helpful. 

## To reproduce ##

1. Do this
1. Then this

## Expected behavior ##

What did you expect to happen that didn't?

## Any helpful log output or screenshots ##

Paste the results here:

```console

```

Add any screenshots of the problem here.

**Comment by ethanb-cisa** [comment]
Thanks for your feedback! We will review this suggestion for inclusion in the next release.

In the meantime, if you want to use the code:

1. Go to the [releases page](https://github.com/cisagov/ScubaGear/releases).
2. Find the latest release (currently v0.1.0)
3. Click **Source Code (zip)**
4. Locate the downloaded file, right click it, and select **Extract All...** or use your preferred zip manager.
5. Open the new folder, hold **Shift** and then **Right Click**.
6. Select **Open PowerShell window here**
7. Follow the remaining steps in the README.

**Comment by ethanb-cisa** [comment]
Closed in #24
