### ISSUE TITLE
AAD 7.2 Missing Test Result (Rego Output) Error

### ISSUE THREAD

**Issue by buidav** [cisagov/ScubaGear#505]
# 🐛 Summary #

On the emerald branch, AAD 7.2 is throwing multiple errors. 

(Now dealt with in #514) One of these errors is because the `"Security.Events.Read.All"` scope is missing from the `$GraphScopes` array in `Connection.psm1`. 

The other error is being thrown on the GCC High tenant. The Security Score we are looking for doesn't exist in GCC High. The rego is not handling this case and is not outputting correctly to handle this case. 

Added the scope in just for this screenshot.
<img width="374" alt="Screenshot 2023-08-30 073114" src="https://github.com/cisagov/ScubaGear/assets/105074908/d1d64fb0-3cc8-464f-8b01-5d4798b12856">

## To reproduce ##

On the emerald branch, run `Invoke-SCuBA -ProductNames aad` against a  GCC High tenant

## Expected behavior ##

AAD 7.2 to have Rego output for GCC High. 

## Any helpful log output or screenshots ##
<img width="490" alt="securescoreerror" src="https://github.com/cisagov/ScubaGear/assets/105074908/9ff90c66-8b3d-4cc9-bc3f-72b2caa94068">

<img width="755" alt="7 2 report error" src="https://github.com/cisagov/ScubaGear/assets/105074908/5efe326e-24a1-4f22-ad30-d90551c24a84">
>

**Comment by tkol2022** [comment]
SecurityEvents.Read.All is going to be taken care of in [PR 514](https://github.com/cisagov/ScubaGear/pull/514/files#diff-d584d43c876f1742033e510eef8e4dddeb395ea8ac2ceb2a5656e385ace6bde6) so we should remove it from the scope of this issue. This issue can be about fixing the GCC High problem.

**Comment by ssatyapal123** [comment]
@buidav  Thanks for catching this.
I tried running it on cisaent and it was still showing as a pass but I am wondering if this is an issue with my powershell session and if it is storing the graphscopes somehow. (Need to refresh on how to check if that is the case in the command line.)

I have been having trouble logging into the GCC High. I am able to log in with the browser and have set up my MFA a while back. But when I run the tool I get this error:

![image](https://github.com/cisagov/ScubaGear/assets/78565245/3d0d3b74-e52a-4e56-8f30-18c93d7509bb)

**Comment by tkol2022** [comment]
I'm fairly confident that this issue is OBE. We removed the secure score cmdlet from the codebase and right now AAD 7.2 simply shows a not implemented. @buidav please confirm that you are able to run the tool and then close this if you agree it is OBE.



![Image](https://github.com/cisagov/ScubaGear/assets/107076927/1eb127f1-efdd-4651-8aef-1716c8628aa5)
