### ISSUE TITLE
Teams policy 5.1 needs to be implemented in the Rego code

### ISSUE THREAD

**Issue by ahuynhMITRE** [cisagov/ScubaGear#506]
# 💡 Summary #

As part of recent Teams SCB updates, policy MS.TEAMS.5.1v1 has been updated The earlier policy was checking for the agency to   allow all apps published by Microsoft. In the new Teams SCB's, this has been updated to only allow installation of Microsoft Apps approved by the agency. This issue is to update the code to be consistent with the new policy.

## Motivation and context ##

This is to make the Rego code align with the current SCB policy.

## Implementation notes ##

Update the rego code for existing MS.TEAMS.5.1v1 to now check the Global (org-wide default) policy to be set to "Allow Specific apps and block all others". The following more restrictive options should also produce a "PASS" results, "Block all apps"

## Acceptance criteria ##

- [ ] The ScubaGear report for Teams should have new language aligning to new MS.TEAMS.5.1v1 policy.
- [ ] MS.TEAMS.5.1v1 should produce a pass for the following criteria:
  - [ ] Microsoft apps permissions set to "Allow Specific apps and block all others" and "Block all apps"

**Comment by Dylan-MITRE** [comment]
done as #588 is merged
