### ISSUE TITLE
Update the report module to handle policies with a list of items

### ISSUE THREAD

**Issue by buidav** [cisagov/ScubaGear#526]
# 💡 Summary #
<img width="515" alt="update HTML" src="https://github.com/cisagov/ScubaGear/assets/105074908/75e7934b-e930-45e9-b754-1b92347e90e7">

With the emerald release we are parsing the baseline markdown documents which has policies that contain bulleted lists.
The above image is what is currently happening to those bulleted lists when they appear in the report. 

Goal of this issue is to update the `Createreport.psm1` module to better display these lists. 

## Motivation and context ##
To make the Policy requirement readable in the report when there is a bulleted list.

## Implementation notes ##
- Updates to `CreateReport.psm1`
- Possible updates to the reporter `*.js` and `*.css` files.

## Acceptance criteria ##

A human can read the requirement of a policy with a list of items in the ScubaGear report.

**Comment by twneale** [comment]
Is this already fixed in the flipper branch? The bullets are showing up formatted in the exo report I just generated. 

![Image](https://github.com/cisagov/ScubaGear/assets/70850/c685ab0b-f9cd-46e1-bed8-94727c4674d0)

**Comment by mitchelbaker-cisa** [comment]
Looking into this a bit further the `overflow-wrap: break-word` CSS property is applied to each \<td> tag, which formats each bullet point to the next line. 

![Image](https://github.com/cisagov/ScubaGear/assets/149098823/e8b30987-7107-4f1a-9455-6f22e92c1932)

Another issue here is markdown formatting to bold text, (** bold text **) which should be formatted to \<strong> bold text \</strong>
