### ISSUE TITLE
Ensure that Microsoft's renaming of Azure AD does not impact ScubaGear license check code and documentation

### ISSUE THREAD

**Issue by tkol2022** [cisagov/ScubaGear#553]
# 💡 Summary #

According to Microsoft earlier this week, "[The rename of Azure Active Directory (Azure AD) to Microsoft Entra ID](https://techcommunity.microsoft.com/t5/microsoft-entra-azure-ad-blog/azure-ad-rename-rollout-and-resources/ba-p/2520432) is now rolling across content and product experiences".

The scope of this issue is to test ScubaGear to ensure that the renaming does not affect the code we have for AAD that relies on the license name AAD_PREMIUM_P2 which is short for Azure AD Premium P2. We may also have documentation referencing the old license name that needs be updated.

## Motivation and context ##

This is useful because if Microsoft changed the underlying license code name, our AAD code which checks if the user has the respective license, wouldn't work and ScubaGear could produce errors or incorrect outputs.

## Implementation notes ##

- [x] Run ScubaGear in different test tenants and check the provider JSON to ensure that the **license code** is still AAD_PREMIUM_P2 and that the code produces the expected output based on the tenant type (E3 vs. E5). As long as the license code is still AAD_PREMIUM_P2 in the JSON, the Rego will continue to produce the correct results and does not need modification.
- [x] Check the Azure portal user to license assignment page to see what the new "**display**" name of the Azure AD Premium P2 license is. Document it here
- [x] If the license display name has changed, then check ScubaGear, including the README to see if we need to update any of our report messages or documentation to match the new display name.
- [x] I checked the AAD baseline document and we need to modify all License Requirements sections that refence "AAD P2 license".

## Acceptance criteria ##

How do we know when this work is done?

- [x] All of the actions above have been completed and the ScubaGear code / README have been updated.

**Comment by tkol2022** [comment]
### New license name
Based on the Azure portal, the new license name that can be assigned to users is "Microsoft Entra ID P2".

**Comment by nanda-katikaneni** [comment]
Closed through #584 merge.
