### ISSUE TITLE
Test Current Release on Mac

### ISSUE THREAD

**Issue by amart241** [cisagov/ScubaGear#557]
# 💡 Summary #

What is the work, as a high-level summary?
Making sure that admins using MacOS will not encounter any issues
## Motivation and context ##

Why does this work belong in this project?
it maximizes compatibility of our tool
This would be useful because...
some admins are using M365 but also using MacOS
## Implementation notes ##

Please provide details for implementation, such as:

## Acceptance criteria ##

How do we know when this work is done?
When it is running smoothly on MacOS with minimal interruptions from normal behavior

**Comment by petersonjdNIH** [comment]
I've made early progress on getting ScubaGear working on macOS. Getting everything in place by `brew` is a good first step. PowerShell being the main one.

I made it as far as running `Import-Module` successfully. I'm currently stuck at this step:

```powershell
PS /Users/joel.peterson/Downloads/ScubaGear-1.2.0/PowerShell/ScubaGear> Initialize-SCuBA            OperationStopped: The type initializer for 'ScubaConfig' threw an exception.
PS /Users/joel.peterson/Downloads/ScubaGear-1.2.0/PowerShell/ScubaGear>
```

**Comment by james-garriss** [comment]
I can confirm what you're seeing.  Unfortunately at this time, ScubaGear is Windows-only.  Some of the underlying libraries from Microsoft require PowerShell 5, which is tied to Windows.  Until Microsoft upgrades them to use PowerShell 7, there's not much we can do to make ScubaGear cross-platform.  Sorry!

I've added some info to the documentation, and once merged, this should be clearer.

**Comment by james-garriss** [comment]
Closing this issue, as it's not solvable at this time.  :-(
