### ISSUE TITLE
Add CONTRIBUTING and RELEASE documentation

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#56]
As pointed out in the public repo, we don't have a CONTRIBUTING.md file yet which will contain instructions for users that want to contribute to the project. Review similar coding efforts at CISA to re-use their language.  Have the contributing file reference other documentation, such as the RELEASE file.

**Comment by mitchelbaker-cisa** [comment]
Example [CONTRIBUTING.md](https://github.com/cisagov/LME/blob/main/CONTRIBUTING.md) from LME we recently added. In other words, "Thanks for thinking about contributing to the project! This is how we handle new issues and PRs."
