### ISSUE TITLE
MS.AAD.7.6v1 criticality in ScubaGear report does not match the baseline policy

### ISSUE THREAD

**Issue by tkol2022** [cisagov/ScubaGear#573]
# 🐛 Summary #

Policy MS.AAD.7.6v1 shows the criticality of Should in the ScubaGear report Criticality column, but it is supposed to be a Shall based on the policy.

## Any helpful log output or screenshots ##

![image](https://github.com/cisagov/ScubaGear/assets/107076927/b4c570bc-7582-4bbd-93a6-f322e5c93945)

**Comment by tkol2022** [comment]
@ahuynhMITRE Can you please have Elaine and Mark check the rest of AAD to make sure that the criticalities in the Criticality column match up with the policies? Also do the same for the other products. Thank you!

**Comment by ahuynhMITRE** [comment]
> @ahuynhMITRE Looks like the code fix for this has been made. Is this ready for a quick PR and merge based on the single line/word change?

just double checking through the rest of the rego for all other products! PR will be up and ready soon!

**Comment by tkol2022** [comment]
The AAD 7.6 criticality is fixed in my open PR #584 so no need to do anything about that. If you find any mismatches in any of the other products, then a new PR might be necessary.

![image](https://github.com/cisagov/ScubaGear/assets/107076927/5e1aac43-3013-4188-8ac4-be0ad291b6cb)

**Comment by ahuynhMITRE** [comment]
> The AAD 7.6 criticality is fixed in my open PR #584 so no need to do anything about that. If you find any mismatches in any of the other products, then a new PR might be necessary.
> 
> ![image](https://user-images.githubusercontent.com/107076927/276303163-5e1aac43-3013-4188-8ac4-be0ad291b6cb.png)

I will close this issue then and create a new one if any arise!
