### ISSUE TITLE
How to execute the Automated Functional Test orchestrator

### ISSUE THREAD

**Issue by tkol2022** [cisagov/ScubaGear#592]
# 💡 Summary #

This issue describes how to execute the automated functional test orchestrator against an M365 tenant.

**Comment by tkol2022** [comment]
## AAD Testing Instructions
Here are the instructions for running the functional test orchestrator with the AAD test plan YAML files.

### Setting up the tenant for testing conditional access policies in the functional test plan
Several of the test cases in the functional test plan associated with conditional access rely on some dependencies in the tenant that you must setup ahead of time. Please refer to issue #591 for instructions.

### Running the orchestrator with the respective YAML files

- **All tenants** - You will execute the aad.testplan.yaml tests against all tenants regardless of tenant type.
- **G5/E5 tenants** - You will also execute the aad.g5.testplan.yaml but only if the tenant is G5/E5.
- **G3/E3 tenants** - You will also execute the aad.g3.testplan.yaml but only if the tenant is G3/E3.

### Example execution against a G5/E5 tenant
Modify the container parameter values in **-Data** to match your tenant accordingly. The example below assumes you are running in **interactive mode**.

- Execute the **All tenants** YAML file
```
$TestContainers = @()

$TestContainers += New-PesterContainer -Path "Testing/Functional/Products" -Data @{ TenantDomain = "MyG5tenant.onmicrosoft.com"; TenantDisplayName = "My G5 tenant"; ProductName = "aad"; M365Environment = "gcc" }

$PesterConfig = @{
	Run = @{
		Container = $TestContainers
	}
	Output = @{
		Verbosity = 'Detailed'
	}
}

$Config = New-PesterConfiguration -Hashtable $PesterConfig 

Invoke-Pester -Configuration $Config
```

- Execute the **G5/E5** YAML file
To execute the G5/E5 specific tests notice that you must add the **Variant** variable to the **-Data** parameter in the test container. To execute against a G3/E3 tenant you simply need to change the value of the Variant variable value to "g3".

```
$TestContainers = @()

$TestContainers += New-PesterContainer -Path "Testing/Functional/Products" -Data @{ Variant="g5"; TenantDomain = "MyG5tenant.onmicrosoft.com"; TenantDisplayName = "My G5 tenant"; ProductName = "aad"; M365Environment = "gcc" }

$PesterConfig = @{
	Run = @{
		Container = $TestContainers
	}
	Output = @{
		Verbosity = 'Detailed'
	}
}

$Config = New-PesterConfiguration -Hashtable $PesterConfig 

Invoke-Pester -Configuration $Config

```

**Comment by tkol2022** [comment]
### Running the test orchestrator with a service principal
To use a **service principal** add the **Thumbprint** parameter (matches the thumbprint of a local client certificate installed on your test machine) and **AppId** parameter (matches the Application ID of the service principal in the AAD Enterprise Applications portal page).

An example execution of the AAD All tenants YAML with a service principal against a G5 tenant is provided below:

```
$TestContainers = @()

$TestContainers += New-PesterContainer -Path "Testing/Functional/Products" -Data @{ Thumbprint = "D17F58D66DC5750EF78F25FF04CCE88DE730BCA6"; AppId = "1947b06c-46a9-4ff2-80c8-27261e58868b"; TenantDomain = "MyG5tenant.onmicrosoft.com"; TenantDisplayName = "My G5 tenant"; ProductName = "aad"; M365Environment = "gcc" }

$PesterConfig = @{
	Run = @{
		Container = $TestContainers
	}
	Output = @{
		Verbosity = 'Detailed'
	}
}

$Config = New-PesterConfiguration -Hashtable $PesterConfig 

Invoke-Pester -Configuration $Config
```

**Comment by tkol2022** [comment]
## Other Products
To execute the functional test orchestrator against other products, you must simply modify the -Data parameter **ProductName** for the Pester test container. An example for Exchange Online is provided below.

```
$TestContainers = @()

$TestContainers += New-PesterContainer -Path "Testing/Functional/Products" -Data @{ Variant="g5"; TenantDomain = "MyG5tenant.onmicrosoft.com"; TenantDisplayName = "My G5 tenant"; ProductName = "exo"; M365Environment = "gcc" }


```

**Comment by tkol2022** [comment]
### How to handle when you get the error message "This version of ChromeDriver only supports Chrome version X"
Sometimes, when running the test orchestrator, if your Chrome browser has been updated since you setup your Selenium environment you may receive the error message in the screenshot below.

![image](https://github.com/cisagov/ScubaGear/assets/107076927/347a3e56-9090-4303-823b-f0ede9e0598f)

To resolve this, first kill any ChromeDriver.exe processes running by using the Task Manager. If you do not successfully kill that process you might receive an error message such as the one below.

![image](https://github.com/cisagov/ScubaGear/assets/107076927/86d66865-14de-42f6-be74-f3e180bf1f24)

Then execute the commands below to update the Selenium Chrome driver.

```
import-module Selenium

$WebDriversPath = Join-Path -Path (Get-Module Selenium).ModuleBase -ChildPath "assemblies"

.\Testing\Functional\SmokeTest\UpdateSelenium.ps1 -webDriversPath $WebDriversPath
```

![image](https://github.com/cisagov/ScubaGear/assets/107076927/7b8c1a11-92d1-4b27-8c79-c3e5ece81e2e)

**Comment by tkol2022** [comment]
### Error messages related to authentication when running with a service principal
If you are trying to run the test orchestrator as a service principal and your client certificate has NOT been uploaded into the Azure AD registered applications Certificates and Secrets page, you may receive an error similar to the one below (this is specific to the AAD product - other products may give slightly different errors). Contact the system admin to upload your certificate file.

![image](https://github.com/cisagov/ScubaGear/assets/107076927/e34f864e-1fbe-461b-84e7-0adfca5bea71)

**Comment by tkol2022** [comment]
## Setup script
Execute the attached Powershell script in your ScubaGear folder to setup the Pester and Selenium dependencies on your machine.
You will execute this one time initially to get your computer setup. For Selenium you will need to update that every time your Chrome browser gets updated via a patch. Refer to the [separate comment](https://github.com/cisagov/ScubaGear/issues/592#issuecomment-1765066357) above for those instructions.

[SetupAutoFunctionalTest.zip](https://github.com/cisagov/ScubaGear/files/13167469/SetupAutoFunctionalTest.zip)

**Comment by tkol2022** [comment]
## Execution script
This is a utility script to help you execute the automated functional test orchestrator.
Place this script in a folder named **FunctionalTesting** that is at the same level in your directory tree as ScubaGear.
Then execute the script like this:

`..\FunctionalTesting\RunFunctionalTest.ps1`

![image](https://github.com/cisagov/ScubaGear/assets/107076927/9e43254d-5c96-49f2-8507-ab45289f58b0)
![image](https://github.com/cisagov/ScubaGear/assets/107076927/506ff765-2065-47b3-8b5b-cb60dc4796bb)

[RunFunctionalTest.zip](https://github.com/cisagov/ScubaGear/files/13167533/RunFunctionalTest.zip)

**Comment by james-garriss** [comment]
It seems like this should be documentation added to the repo itself instead of an issue.  It could be added as Markdown files and automatically converted to Word, PDF, or HTML as desired.  I can help with this, if you want.
