### ISSUE TITLE
Defender baseline section 1 is missing license requirements

### ISSUE THREAD

**Issue by tkol2022** [cisagov/ScubaGear#598]
# 🐛 Summary #

Upon review of the Defender Rego code I discovered that a few of the policies 1.1, 1.3 and 1.5 rely on the Get-ATPProtectionPolicyRule cmdlet which requires the Defender for Office Plan 1 license. This needs to be reflected in the baseline license requirements section.

![image](https://github.com/cisagov/ScubaGear/assets/107076927/47621b8b-1569-45c1-bae2-392b1c2aadcf)
![image](https://github.com/cisagov/ScubaGear/assets/107076927/aaee7178-51b6-4dfd-93fa-a294f1e6a1dc)
![image](https://github.com/cisagov/ScubaGear/assets/107076927/c77ee29f-d7a5-4b46-99cb-aeda3cbd63b6)

**Comment by nanda-katikaneni** [comment]
Closed through #621
