### ISSUE TITLE
Cannot connect to multiple tenants

### ISSUE THREAD

**Issue by MBstatsara** [cisagov/ScubaGear#6]
# 🐛 Summary #

We have ran this on our test tenant, and then against a dev environment.
When we get the report from the dev environment it is listing users and settings from the test setup.
Even after a reboot, and deleting the scuba folder and running again from a new location.

## To reproduce ##

1. Run Scuba against tenant 1
2. Run Scuba against tenant 2
3. Review reports and you will see details from tenant 1 in tenant 2.

## Expected behavior ##

Would have expected a sign in to occur for each tenant. - which seemed to occur
This reports data from tenant 1 only.
Tenant 2 is then requested a powershell app to setup, and then reports data from tenant 2 only.
See issues for getting the initial domain.

## Any helpful log output or screenshots ##

![image](https://user-images.githubusercontent.com/97956753/198305131-5735db3a-1b0d-4b46-9ddd-4e3239b0ead3.png)

**Comment by stugster** [comment]
We are seeing this bug too, with the same process. Tested on our own tenancy and it worked perfectly. Tested on a client tenancy after this and go the same error.

The solution for us was to run:
Disconnect-MgGraph
in powershell prior to running .\RunSCuBA.ps1 to disconnect the Graph connector and re-prompt for Consent.

**Comment by ethanb-cisa** [comment]
Thanks for the feedback. We're investigating better authentication handling, especially for users with multiple tenants, for future releases. 

I'd recommend running `Disconnect-MgGraph` and then opening a new PowerShell window if you want to run against a different tenant.

**Comment by jonathanbourke** [comment]
> We are seeing this bug too, with the same process. Tested on our own tenancy and it worked perfectly. Tested on a client tenancy after this and go the same error.
> 
> The solution for us was to run: Disconnect-MgGraph in powershell prior to running .\RunSCuBA.ps1 to disconnect the Graph connector and re-prompt for Consent.

Yep, that worked for me. Many thanks.

**Comment by ethanb-cisa** [comment]
Closed in #24. The `Disconnect-SCuBATenant` and `-DisconnectOnExit` should improve this use case. Use either to fully disconnect your current session from any existing tenants. 

We are exploring how to improve multi-tenant handling going forward, too. There are some limitations in the different MS modules.
