### ISSUE TITLE
Refactor common code for SensitiveRules in Defender code

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#600]
There is a lot of repeating code, the only difference I can find is the check for `IsAdvancedRule` & regex on a raw string to get the content names. Recommend combining the repeating code.

_Originally posted by @Sloane4 in https://github.com/cisagov/ScubaGear/pull/574#discussion_r1360887853_

**Comment by Sloane4** [comment]
Being addressed in #663
