### ISSUE TITLE
Refactor repeative DLP location tests in Defender code

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#601]
This is a lot of repetitive code, recommend moving the key value (i.e.  TeamsLocation, OneDriveLocation, etc) & the comparison string (line 572,560,etc) as variables to be passed in.

_Originally posted by @Sloane4 in https://github.com/cisagov/ScubaGear/pull/574#discussion_r1360893411_

**Comment by Sloane4** [comment]
addressed in #663
