### ISSUE TITLE
Defender MS.DEFENDER.4.4v1 implementation instructions incomplete

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#603]
# 🐛 Summary #

The Defender baseline includes MS.DEFENDER.4.4v1 which recommends configuring user notifications when detecting sensitive information for data loss prevention (DLP).  The implementation instructions require toggling user notifications to `On`.  For notification in M365 services, however, no notification will be provided unless the additional `Notify users in Office 365 service with a policy tip` item is checked in addition to the toggle.

## To reproduce ##

1. Configure a DLP policy with a rule according to the MS.DEFENDER.4.1v1 instructions referenced by MS.DEFENDER.4.4v1.
2. Run `Invoke-Scuba -p defender`
3. Review the report which will indicate that MS.DEFENDER.4.4v1 failed and the rule configured in step 1 does not notify users.

## Expected behavior ##

Expected result is that the implementation instructions, as written, will result in a pass with the assessment tool.

While testing DLP policies and enabling the Notify users toggle, the report still returned a fail result for the rule indicated.  Further review of the rego assessment showed that it was looking for a list of users to be notified which was an empty set when the toggle is on but the check box for Office 365 is not set.

## Any helpful log output or screenshots ##

The setting according to the current implementation instructions which does not instruct users to check the `Notify users in Office 365 service with a policy tip`.
![Screenshot 2023-10-17 at 11 10 18 AM](https://github.com/cisagov/ScubaGear/assets/108814318/3dbb8456-1cdc-4b0e-b35e-710357391aaf)

**Comment by nanda-katikaneni** [comment]
Fixed through #628
