### ISSUE TITLE
Add config file support to the Functional Test Orchestrator script

### ISSUE THREAD

**Issue by buidav** [cisagov/ScubaGear#608]
# 💡 Summary #

The current functional test orchestrator doesn't allow for config file support. 
Since, the config file is now necessary for certain policy checks, especially in Defender & AAD, this is a must have add on. 

## Motivation and context ##
Functional test cases in AAD, Defender where config file use is necessary are not being checked due to the limitations of the current functional test orchestrator script. 

## Implementation notes ##
Modifications to `Testing/Functional/Products/Products.Tests.ps1` to support config files. 

## Acceptance criteria ##

Testing/Functional/Products/Products.Tests.ps1 -ScubaConfig "" 
is an option.

**Comment by crutchfield** [comment]
We have an initial config file capability that was added for Defender.  It was added under #583 
It was implemented on a per test case basis so it is a property of a given test case. 

![image](https://github.com/cisagov/ScubaGear/assets/7025068/e9bc0f7b-1092-4509-98e8-f5c15252c26a)
