### ISSUE TITLE
Investigate how to better handle multiple tenant authentication

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#61]
Running the tool in a powershell session/desktop with multiple logged in/cached accounts is buggy. 

We should investigate how to improve that UX. Preferably the user only logs in once, or provides a UPN to use that we can pass to the providers.

**Comment by TjebbeVQ** [comment]
Can confirm, running back to back on different tenants, it will always use the first authenticated tenant even when logging in with a totally seperate tenant's account.
