### ISSUE TITLE
Address Rego Linter (Regal) Rules

### ISSUE THREAD

**Issue by buidav** [cisagov/ScubaGear#615]
# 💡 Summary #

This issue is to address follow ups from #594 along with any other Linter rules we wish to follow. 

[First follow up to address:](https://github.com/cisagov/ScubaGear/pull/594#discussion_r1357495909)
1. line length
2. identically named tests
3. constant condition* (see the original comment chain for more context)

[Second follow up to address:](https://github.com/cisagov/ScubaGear/pull/594#discussion_r1368599553)
```
   # https://docs.styra.com/regal/rules/testing/test-outside-test-package
    test-outside-test-package:
      # This is just a style preference
      level: ignore
```
"gdasher I think we should think about having this on as a warning or error. While it is more style (the program will still run when ignored), I think it is good practice. It would cause us to need to refactor some things, but the size should be small."

[Third follow up ](https://github.com/cisagov/ScubaGear/pull/594#discussion_r1368606840)
```
      level: ignore
    # https://docs.styra.com/regal/rules/style/prefer-some-in-iteration
    prefer-some-in-iteration:
      level: ignore
```
" Right now a lot of our code does not use some in iteration, but I have notice that there are some cases where some in is the only way the code will work correctly vs var := input_var[_], do you know of any cases where the opposite is true. If not, i would not be against turning it on because I think it will decrease the amount of miss-typing = instead of :="

## Motivation and context ##

Follow up of #559 

## Implementation notes ##
We will have to break this issue up into smaller issues. 
Addressing everything in just one PR could be done but we prefer not to these days ;).  

## Acceptance criteria ##
The follow ups above are addressed.

**Comment by Sloane4** [comment]
I would also like to add a warning to this rule
```
rule-length:
      level: ignore
    # https://docs.styra.com/regal/rules/style/todo-comment
```
