### ISSUE TITLE
Sharepoint 2.2 Rego does not implement all the conditions in the baseline policy and therefore can produce an inaccurate report

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#62]
### Issue 1
The Sharepoint 2.2 baseline implementation requires three configurations but only one is checked by the Rego code, therefore producing an inaccurate report. See the baseline document's implementation section and policy bullet. The three configurations are listed below:

- Set the Sharepoint external sharing slider to New and Existing Guests
- Limit external sharing by domain (**this is not implemented**)
- Allow only users in specific security groups to share externally (**this is not implemented**)

I verified that the report can produce a false "compliant" score for this policy by testing in the MITRE E5 tenant while the tenant was misconfigured.

Current Rego code shows that only one configuration is checked:

![image](https://user-images.githubusercontent.com/107076927/200894487-7e4430f8-e682-4c4f-95cb-fd697d38f567.png)

### Issue 2
The Rego "Requirement" field for this policy needs to be updated to align with the baseline. Currently the baseline policy bullet is wrong but Andrew is correcting it. The corrected policy bullet will read "External Sharing SHOULD be Set to New and Existing Guests and Managed Through Approved Domains and/or Security Groups Per Interagency Collaboration Needs."
Don't forget to update the unit tests for this policy since a name change will break the tests.

**Comment by adhilto** [comment]
Piggy-backing off of this issue, though it may merit its own issue. Currently the report displays a failure if something more strict than "New and Existing Guests" is selected. From the review this morning, it sounds like we don't want to show a failure in cases like this. Would also recommend clarifying the baseline text to say that being more script is acceptable.

Personal thought after taking a closer look at this issue, I might recommend splitting this bullet point into separate bullets. As right now the single bullet requires three different things, splitting it might make it readable.

Tagging @ethanb-cisa for awareness.

**Comment by ethanb-cisa** [comment]
Made a comment in baseline comment tracker (124) so we can adjudicate this with the team.

**Comment by Sloane4** [comment]
Scope creep, but adding the changes to keep update for file in 1 location & reduce chances for merge conflicts.

**2.1**
- Removing count because this is a singular tenant setting

**2.4**
- Add EmailAttestationRequired to implement baseline condition
- EmailAttestationReAuthDays to implement baseline condition

**2.5**
- Removing count because this is a singular tenant setting
