### ISSUE TITLE
Improved error handling in the CreateReport module

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#65]
**As a** user, **I want** clear indications that report generation has failed **so that** I understand when a report should not be considered accurate or should be disregarded or regenerated.

Currently, certain failures in the Rego section of the ScubaGear tool can result in incomplete test results being created.  If no test results are present, then the only indication is a blank or incomplete table in the product report.  For users, especially new ones, this may not be noticed and result in incorrect conclusions drawn about their tenant's conformance to the baselines.  As such, recommend that the reporting module (and any other modules as needed) be updated to allow for detection and reporting of such a condition.  Ideally, failing the product report overall and providing feedback on the failure to the user.  This can be done on a per product basis rather than failing report generation entirely.

**Comment by adhilto** [comment]
See https://github.com/cisagov/ScubaGear/issues/209 for more details

**Comment by crutchfield** [comment]
Modified create report to look for test results for all controls in baseline (that are not deleted).  If a test result is missing then a bug is reported in both User HTML report and via Write-Error.
