### ISSUE TITLE
Add ConfigFilePath Option to the Invoke-RunCached Option for running ScubaGear

### ISSUE THREAD

**Issue by ssatyapal123** [cisagov/ScubaGear#653]
# 💡 Summary #

The Invoke-RunCached module for running ScubaGear does not have all the same parameter options as the Invoke-SCuBA module. In particular, the -ConfigFilePath option is not available for this module:

```
-ConfigFilePath <FileInfo>
        Local file path to a JSON or YAML formatted configuration file.
        Configuration file parameters can be used in place of command-line
        parameters. Additional parameters and variables not available on the
        command line can also be included in the file that will be provided to the
        tool for use in specific tests.
```

## Motivation and context ##

The `-ConfigFilePath` option should be enabled for both methods for running ScubaGear to simplify the testing process. In addition, this option enables tenant users to specify both the standard SCuBAGear set of parameters to run but also includes examples of custom variables for use and reference in Rego policy assessments against the AAD and Defender baselines.

This would be useful because some policies cannot be fully tested using the Invoke-SCuBA tool as implementing the policies could lock up the tenant (e.g., requiring all users to use phishing-resistant MFA). The configuration file option enables testing these policies using the local ProviderSettingsExport.json settings rather than the live tenant settings.

## Implementation notes ##

- Specify custom parameters in the local JSON and YAML formatted configuration files that match the exclusions in the local ProviderSettingsExport.json and run Invoke-RunCached -ConfigFilePath <local config file> to verify the exclusions show as a pass in the output report.

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Verify Invoke-RunCached works for both standard and custom parameters specified in the local config file

**Comment by ssatyapal123** [comment]
Per discussions today, here is a use case in the command line yaml config file:

Aad:
All AAD specific variables go here
  MS.AAD.1.1v1: &CommonExclusions
    CapExclusions:
      Users:
        - fc29f4a8-2b27-4d1e-898e-cfacb98bd8f8
      Groups:
        - 08adb07a-956f-450e-b41c-81e92e3db2c4
        - 8454f405-3b29-4102-b888-315c4e3de2d0
  MS.AAD.2.1v1:  *CommonExclusions
  MS.AAD.2.3v1:  *CommonExclusions
###   MS.AAD.3.1v1:  *CommonExclusions
  MS.AAD.3.2v1:  *CommonExclusions

The "MS.AAD.3.1v1" field would work if the policy is enabled for "All users" on the tenant and exclusions are as provided in this file. However, right now this policy is failing on our test tenants because we don't want to lock out the tenant. So, the one thought was to use the "RunCached option" to check the box for this.

Agree with Crutch regarding finding a simpler option per "TMTOWTDI" philosophy ;-)

**Comment by Dylan-MITRE** [comment]
This issue is obsolete, close this one and created new issue #836
