### ISSUE TITLE
Add Topics to ScubaGear description for discovery

### ISSUE THREAD

**Issue by buidav** [cisagov/ScubaGear#691]
# 💡 Summary #

Not sure how many people use this feature on GitHub but for discoverability purposes let's add a few topics to the about page. 

## Motivation and context ##

To help ScubaGear's discoverability among GitHub users looking for repositories by topic 

## Implementation notes ##

> [!Important] 
> this requires a user with `maintain` permissions and above

On the main repo page. Click on the Gear Icon next to About. The gear doesn't appear if the user doesn't have sufficient permissions <img width="740" alt="about" src="https://github.com/cisagov/ScubaGear/assets/105074908/d0f50b02-c367-499c-ba15-9c6de1484049">

Add topics we want in a comma separated list.
<img width="393" alt="repo topics" src="https://github.com/cisagov/ScubaGear/assets/105074908/daef78f5-ecab-4505-98cf-9ebc2acf87da">

Topics we be listed like this. Example from the LME repo below.
<img width="203" alt="aboutTopics" src="https://github.com/cisagov/ScubaGear/assets/105074908/704adb77-52c8-4094-b938-876d5779ff40">

## Acceptance criteria ##
Topics such as `powershell`, `open-policy-agent`, `microsoft 365` plus more are added to ScubaGear's repo topics

**Comment by mitchelbaker-cisa** [comment]
The topics listed look good. Looking through https://github.com/topics/open-source consider adding `community`/`contributions` to garner outside contributions?
