### ISSUE TITLE
Azure Government and GCC High Support

### ISSUE THREAD

**Issue by benatsb** [cisagov/ScubaGear#7]
# 💡 Summary #

Added some logic and a new parameter to support targeting Azure Government and GCC High cloud environments. Added examples and details to the readme.

## Motivation and context ##

We almost exclusively with clients in Azure Government and GCC High. Targeting the various services with different connection strings require some tedious checking. Once past the connection strings there are various differences between Commercial Azure/M365 and GCC High. 

You can change a parameter and target your cloud environment or further expand to the other Azure Clouds (ie DOD). 

## Implementation notes ##

Forked repository could pull into this repo. However, many files were edited to make sure the cloud environment identity is carried through the modules. A review needs to take place.

https://github.com/sentinelblue/ScubaGear

## Acceptance criteria ##

How do we know when this work is done?

- Validated against a GCC High tenant. I validated against our tenant in GCC High/Azure Gov.
- How to handle errors that occur to configuration differences in GCC High and Commercial? The Teams provider throws some errors due to missing properties on the 'Get-CsTenant' cmdlt. It appears these values aren't populated in my tenant or not populated in GCC High.

**Comment by gdasher** [comment]
Thanks.  In an upcoming release, we plan to add the endpoint routing support for GCC High and DoD's various environments, as well as do further testing against GCC High.

**Comment by benatsb** [comment]
Awesome! I work in GCC High land 24/7, so if you have any questions or if there are any ways I can help, I'd love to.

**Comment by gdasher** [comment]
Re-opening this to track until the support lands

**Comment by ethanb-cisa** [comment]
Closed in #24 . Let us know if you run into issues.
