### ISSUE TITLE
Orchestrator Script can check for Maximum PowerShell Version

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#70]
The twin issue of #11. 
See the discussion there for details on how to implement.

Products that are confirmed to not work on PowerShell version 6+
SPO
OneDrive
Power Platform.

Files to change:
Orchestrator.psm1.

**Comment by nanda-katikaneni** [comment]
@schrolla @buidav - assume this issue is fixed through other items or are there any remaining things to fix? (wanted to confirm before closing).
