### ISSUE TITLE
EXO provider produces an error when running in a E3 tenant

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#72]
Test:
Testing the EXO automation using the Main branch - test the conformance of a Microsoft 365 tenant with E3 license and P2 

Issue:
Several of the Cmdlets in the EXO provider fail due to: "The term [Cmdlet name] is not recognized as the name of a cmdlet, function, script file, or operable program."

The following Cmdlets are affected: Get-OrganizationConfig, Get-RemoteDomain, Get-DkimSigningConfig,..etc. Detailed error message is attached.

Background:
This issue seems similar to #277 (and a previously fixed #193)
See EXO-Test-Fail-E3.txt results in original issue #288

**Comment by nanda-katikaneni** [comment]
Retested EXO with main branch on a E3 tenant - the issue reported in the original description is not there anymore. I will add more notes from my test to a related issue #41 - closing this issue.
