### ISSUE TITLE
Workflow trigger twice of same logical event

### ISSUE THREAD

**Issue by crutchfield** [cisagov/ScubaGear#736]
# 🐛 Summary #

Run_PowerShell_Test workflow executes twice when Pushing a change to a PR in review.  

## To reproduce ##

1. Have branch in review for PR
2. Push a PowerShell change to branch

## Expected behavior ##

Expect workflow to only run once (ignore extra trigger)

## Any helpful log output or screenshots ##

![image](https://github.com/cisagov/ScubaGear/assets/7025068/8db097e4-bc93-4f14-a8d4-48d751249ab3)

**Comment by tkol2022** [comment]
### Reviewed 12/14
I set the size to small since it seems like an easy fix. @crutchfield needs to verify and update the size if necessary.
Assuming the size is small, I put the priority as high since it is inefficient to run the tests twice.

**Comment by crutchfield** [comment]
> ### Reviewed 12/14
> I set the size to small since it seems like an easy fix. @crutchfield needs to verify and update the size if necessary. Assuming the size is small, I put the priority as high since it is inefficient to run the tests twice.

I think size is good.  Not saying [this](https://stackoverflow.com/questions/59086443/is-it-possible-to-trigger-a-github-workflow-only-once-for-a-pull-request) is answer but suggests it is small.

**Comment by james-garriss** [comment]
This was addressed by me several months ago.  Look in the workflows for this comment (# This condition prevents duplicate runs.), and you will see the fix.
See #805.
