### ISSUE TITLE
Report on ignored policies

### ISSUE THREAD

**Issue by crutchfield** [cisagov/ScubaGear#740]
# 💡 Summary #

As a user, I want to be able to direct ScubaGear to ignore evaluating and reporting on compliance with a given policy. I want ScubaGear to report the policy is not being evaluated for compliance and show my provided rationale.

## Motivation and context ##

The user in a realistic operational environment may choose to accept risk of non-compliance with a given policy. Our tool should support the user as they manage these risks.

This would be useful because it will allow the user to get a report of a document choice to ignore compliance with a given policy.

## Implementation notes ##

Details for implementation:

- An ignored policy is reported as such with a provided rationale

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Any policy specified to be ignored for a given reason is reported as such

**Comment by tkol2022** [comment]
Not sure why but the description for #739 seems identical with this one except that 739 has some additional scope. If this is true, then close this issue as a duplicate.
