### ISSUE TITLE
TCO to review and update (if necessary) M365 Workshop slides for AAD

### ISSUE THREAD

**Issue by ahuynhMITRE** [cisagov/ScubaGear#753]
# 💡 Summary #

SCuBA will hosting workshops to cover M365's SCBs and the team is requesting the TCOs to review and update the slides to match the current language approved in the v1.0 version.

## Motivation and context ##

JCDC, OCC, and CISA front office reviews may discover changes to the language of the policies and the rationale sections. In order for the workshops to stay synced with the latest version of the SCBs, TCOs are expected to review and update the workshop slides to match version 1.0.

## Implementation notes ##

Please provide details for implementation, such as:

- Review latest SCB released by CISA front office
- Review M365 Workshop slides provided by @mheller93766. HSSEDI Linked below. For those who do not have access to the HSSEDI environment @mheller93766 has provided the slides via email 
  - ​[ 3. M365 SCB Workshops Material](https://hssedi.sharepoint.us/:f:/r/sites/hssedi-CISACapacityBuilding/Shared%20Documents/SCUBA/M365/M365%20Pilot,%20CI%20Pilots,%20and%20Workshops%20Collaborative%20Workspace/3.%20M365%20SCB%20Workshops%20Material?csf=1&web=1&e=ZjAI1F)
- Ensure the language of the policies and the rationales are synced with the latest version of the SCB

## Acceptance criteria ##

How do we know when this work is done?

- [x] M365 Workshop Slides and SCB policy and rationale languages have been reviewed and synced by the TCO

**Comment by ahuynhMITRE** [comment]
currently blocked due to awaiting final version from CISA front office

**Comment by ahuynhMITRE** [comment]
Please have this completed by Jan 12th to meet CISA's review deadline.

**Comment by tkol2022** [comment]
@ahuynhMITRE @mheller93766 Reviewed the slides. Added "Entra ID" to the title slide.
The only pending item that I have is that I recommend that you add the name of each product to its respective slide master so that the product name shows up in the footer of each presentation slide. This way the audience can know which baseline is being presented. Right now after the agenda slide there is no indication of which baseline is being discussed.
