### ISSUE TITLE
Implement ScubaGear policy check for MS.AAD.7.2v1

### ISSUE THREAD

**Issue by tkol2022** [cisagov/ScubaGear#760]
# 💡 Summary #

The policy MS.AAD.7.2v1 "Privileged users SHALL be provisioned with finer-grained roles instead of Global Administrator" is currently a manual check in ScubaGear. The scope of this issue is to implement a ScubaGear policy check based on a new least privilege formula that we [designed and tested in Flipper](https://github.com/cisagov/ScubaGear/issues/548#issuecomment-1852406542).

## Acceptance criteria ##

How do we know when this work is done?

- [x] Changes to AAD provider and Rego are complete and tested by the developer.
- [x] Unit tests have been modified and pass.
- [x] Functional tests have been modified and pass.

**Comment by ssatyapal123** [comment]
@adhilto Ted suggested reaching out to you about a reportutils question. If there's someone else I can bug please let me know :-)
I'm trying to implement MS.AAD.7.2 to calculate and report a custom secure core. It's a simple calculation: Total Number of users with Global Admin privileges/Total Number of privileged users without Global Admin.
My question is how to report out the secure score calculation which is a static value to the report (i.e., I don't need to call a cmdlet like in many of the examples or print out an array of values)

Note: I'm having another error dividing in rego so I can't get the ratio to work, but for now would love to understand how to print and maybe we can use count(GlobalAdmins) just as an example until I figure out how to divide in rego.
Here's my code snippet. Hope this makes at least some sense..

# MS.AAD.7.2v1
#--
GlobalAdmins[User.DisplayName] {
    some id
    User := input.privileged_users[id]
    "Global Administrator" in User.roles
}

notGlobalAdmins[User.DisplayName] {
    some id
    User := input.privileged_users[id]
    not "Global Administrator" in User.roles
}
# Custom calculation now implemented for 7.2v1 using the formula SecureScore = Number of Global Aminds/Number of privileged users who are not Global Admins
tests[{
    "PolicyId" : "MS.AAD.7.2v1",
    "Criticality" : "Shall",
    "Commandlet" : [],
    "ActualValue" : "",
    "ReportDetails" : ReportDetailsString(Status, "Custom secure score"),
    "RequirementMet" : Status
}] {
    Status := count(GlobalAdmins) <= count(notGlobalAdmins) #this is equivalent to ratio check #global admins/#notglobaladmins<= 1
}
