### ISSUE TITLE
Config file default values are duplicated in Invoke-SCuBA parameters and ScubaConfig

### ISSUE THREAD

**Issue by kennethpalmer** [cisagov/ScubaGear#767]
# 💡 Summary #

The Invoke-SCuBA function parameter defaults and ScubaConfig parameter defaults should be shared and defined in one place

## Motivation and context ##

Invoke-SCuBA parameter defaults are specified in 2 places

1. The parameters section of the Invoke-SCuBA function
2. The SetParameterDefaults method of the SCuBA config object

This would be useful because maintenance of this code is complicated by the default values
residing in two places.

## Implementation notes ##

Please provide details for implementation, such as:

- an example for how this would be used
- what this would look like
- how this would act
- any related work, including links to related issues

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Criterion

**Comment by kennethpalmer** [comment]
Not all of the defaults are identical.  
The default value for OPAPath in Invoke-SCuBA is `$env:USERPROFILE -ChildPath ".scubagear\Tools`
The default value in ScubaConfig.psm1:SetParameterDefaults is `$PSScriptRoot\..\..\..\..`

The OPAPath one looks like an installed instance for the host
The ScubaConfig one is at the top level directory of the ScubaConfigRepo

**Comment by crutchfield** [comment]
Blocked till #894  merged
