### ISSUE TITLE
Remove Obsolete helper scripts

### ISSUE THREAD

**Issue by HeathWalker** [cisagov/ScubaGear#772]
# 🐛 Summary #

When running .\RunSCUBA.ps1 getting the following error....

PS C:\tmp\ScubaGear-1.0.0\utils> .\RunSCuBA.ps1
Invoke-SCuBA : Cannot validate argument on parameter 'ProductNames'. The argument "onedrive" does not belong to the set 
"teams,exo,defender,aad,powerplatform,sharepoint,*" specified by the ValidateSet attribute. Supply an argument that is in the set and then try the command again.
At C:\tmp\ScubaGear-1.0.0\utils\RunSCuBA.ps1:33 char:18
+     Invoke-SCuBA @SCuBAParams
+                  ~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-SCuBA], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Invoke-SCuBA
 

Add any screenshots of the problem here.

**Comment by gdasher** [comment]
Thanks for the report.  The RunScuba script is a relic at this point and we should just remove it.  Please follow the instructions on the [README](https://github.com/cisagov/ScubaGear/blob/main/README.md) page on how to run ScubaGear.

**Comment by adhilto** [comment]
Piggybacking off of this issue, there a couple of other relics we should remove as well:
- [ ] utils/RunSCuBA.ps1
- [ ] utils/RegoCachedProviderTesting.ps1
- [ ] Testing/Functional/RegoCachedProviderTesting.ps1
