### ISSUE TITLE
Refactor the ReportDetails* functions

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#78]
The family of ReportDetails* rego functions have grown out of hand.

We have `ReportDetailsBoolean`, `ReportDetailsString`, `ReportDetailsArray`, and at one point on my defender fixes branch we also needed `ReportDetailsLicense` and `ReportDetailsStringLicense`, and if we wanted to complete the family we would also need a `ReportDetailsArrayLicense` function.

We need a method of generating these report details strings that is more extendable and graceful. I came up with an approach in the defender fixes branch that cuts the number of needed functions in half and can be more easily extended if the need arose. I ran the approach by @Sloane4 and she agrees it's the right direction to go. The basic idea is to create a few granular functions that can be wrapped around each other as needed to achieve all the needed functionality.

I applied that method to defender already, but some adaption will be needed to apply it to the other products. Ideally we'd be able to create a "util" file of sorts that can house all the helper functions that all the products need to reduce code duplication.

- [ ] Refactor the ReportDetails* functions
- [ ] Create a util file to house common helper functions (looks like this can be done via `import` statements, see troubleshooting [here](https://github.com/open-policy-agent/opa/issues/2811))

**Comment by Sloane4** [comment]
being addressed in PR #642
