### ISSUE TITLE
Invoke-RunCached Broken

### ISSUE THREAD

**Issue by adhilto** [cisagov/ScubaGear#784]
# 🐛 Summary #
https://github.com/cisagov/ScubaGear/pull/704, which moves the location of the Rego folder, broke `Invoke-RunCached`.

The fix is easy enough, remove line 1302:
https://github.com/cisagov/ScubaGear/blob/5e846859342246bb525645d0c8651b806af6dc2c/PowerShell/ScubaGear/Modules/Orchestrator.psm1#L1302

## To reproduce ##
1. Pull the latest on the flipper branch
2. `Import-Module .\PowerShell\ScubaGear`
3. `Invoke-RunCached -p exo` (product doesn't matter, just an example)

## Expected behavior ##
Expected the EXO baseline to be evaluated.

## Any helpful log output or screenshots ##

Paste the results here:
```
Get-Item : Cannot find path '[redacted]\ScubaGear\Rego\EXOConfig.rego' because it does not exist.
At [redacted\]\ScubaGear\PowerShell\ScubaGear\Modules\RunRego\RunRego.psm1:43 char:27
+         $RegoFileObject = Get-Item $RegoFile
+                           ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: ([redacted]...\EXOConfig.rego:String) [Get-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand
```

**Comment by mitchelbaker-cisa** [comment]
For what it's worth, seeing the Get-Item error along with this one as well:
```
Invoke-RunRego : Error with the AAD Rego invocation. See the exception message for more details:  Error calling the OPA executable: Cannot bind argument to parameter 'Path' because it is null.
At C:\Users\mitchelbaker\Documents\Github\ScubaGear\PowerShell\ScubaGear\Modules\Orchestrator.psm1:317 char:31
+             $ProdRegoFailed = Invoke-RunRego @RegoParams
+                               ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-RunRego
```

**Comment by Dylan-MITRE** [comment]
I am doing something for Invoke-RunCached anyway,  so i can just have this fixed in the PR as well

**Comment by Dylan-MITRE** [comment]
close as #789 is merged
