### ISSUE TITLE
Evaluate generating BaselineTitles.json directly from the Baseline Markdown documents

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#79]
<img width="920" alt="BaselineTitles" src="https://user-images.githubusercontent.com/105074908/192852788-9651e6c9-fb88-426d-b55d-fdc5a554d945.PNG">

This is the manually created JSON that maps the Rego JSON output to the HTML Report.
Every change to the titles/policy numbers in the Baseline docs we have to manually modify this JSON to reflect the changes in the Report.

This issue is for exploring generating this JSON dynamically from the Baseline Markdown docs.
[Current markdown docx branch](https://github.com/cisagov/ScubaGear/tree/markdown-docx)

**Comment by adhilto** [comment]
Will track this issue in https://github.com/cisagov/ScubaGear/issues/228.
