### ISSUE TITLE
Getting multiple product results when any number of products are assigned to the ProductNames variable.

### ISSUE THREAD

**Issue by skirkpatrickms** [cisagov/ScubaGear#8]
# 🐛 Summary #

What's wrong? Please be specific.

When inputting the variable $ProductNames and setting the variable to any number of products, the script runs against all products.  

1.
Set parameters
$LogIn = $true 
$ProductNames = @("aad") 
$Endpoint = "" 
$OutPath = "./Reports" 
$OPAPath = "./" 

2
Run  .\RunSCuBA.ps1

## Expected behavior ##

What did you expect to happen that didn't?

The scripts will only log into aad and give results for aad.  However, all products are logged into and results are given for each.  

Add any screenshots of the problem here.

Below is the output from the results of selecting just aad to be tested.

Baseline Conformance Reports | Details
-- | --
Azure Active Directory | 9 tests passed 3 warnings 10 tests failed 8 manual checks needed
Microsoft 365 Defender | 67 tests passed 7 warnings 3 tests failed 6 manual checks needed
Exchange Online | 10 tests passed  4 tests failed 23 manual checks needed
OneDrive for Business | 4 tests passed 1 warning 1 test failed 2 manual checks needed
SharePoint Online | 4 tests passed  1 test failed 1 manual check needed
Microsoft Teams | 16 tests passed   9 manual checks needed

**Comment by ethanb-cisa** [comment]
I'm not able to reproduce this in my test VM. 

Can you verify the RunSCuBA.ps1 file you are editing is the same file you are running via PowerShell.

Can you provide any other troubleshooting information?

**Comment by skirkpatrickms** [comment]
Unsure of what was going on.  Reboot the computer and its working as expected.
