### ISSUE TITLE
hands-on evaluation of new Azure AD Conditional Access feature - authentication strength

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#80]
### Current Problem
We currently have an issue with Azure AD policy 2.4 which is related to multifactor authentication. There is no practical way to enforce and audit the strength of the MFA method applied to users in the tenant. We need a way to ensure that the MFA methods applied to the tenant are phishing-resistant in accordance with OMB M-22-09.

### Potential Solution
Microsoft released a private preview of a new Conditional Access feature named Authentication Strength "which allow admins to configure which combinations of authentication methods are required when users sign in." This new feature may offer a way to enforce and audit the requirement for the MFA to be phishing-resistant, although we won't know unless we test it.

### Scope of Work
The assignee will evaluate the new feature in a hands-on capacity and determine if it meets our needs.

### Potential Outputs
If the Authentication Strength feature meets the goals described in this issue, then it could generate a change to both the AAD baseline document and the automation tool for policy 2.4.

### Reference Material
The technical materials provided by Microsoft are available in the original issue #245

**Comment by tkol2022** [comment]
@ahuynhMITRE

**Comment by ssatyapal123** [comment]
Performed hands-on evaluation on cisaent and y2zj1 G5 tenants to be able to sign on using Certificate Based Authentication with my DHS PIV card. It requires:

**1. Uploading the three necessary Certificate Authorities to the Azure Tenant (DHS_C4, Treasury, Federal Common Policy)**

> This was already done on the cisaent.

> DHS_C4 and Treasury certs are available for download here: https://pki.treas.gov/crl_certs.htm.

> Federal Common Policy cert is available here: https://playbooks.idmanagement.gov/fpki/common/obtain-and-verify/

**2. Enabling CBA under Authentication Methods in Azure AD Security for specific group(s)**
<img width="1413" alt="Screen Shot 2023-04-18 at 3 07 55 PM" src="https://user-images.githubusercontent.com/78565245/232880852-504c785c-6f9c-4b1b-929a-86988e56aa6d.png">
<img width="1419" alt="Screen Shot 2023-04-18 at 3 08 30 PM" src="https://user-images.githubusercontent.com/78565245/232880929-409b9c97-ac0d-4b15-8b05-825e2cb8bac6.png">

**3. Configuring my user account to include my UPN and Subject Key Identifier**

> These can be found by looking up my certificate properties locally

**4. Updating my Azure User identity to be a member of the test group in step (2)**

**Comment by tkol2022** [comment]
Related to this issue, I tested how authentication strength is enforced for Azure AD guest users. See #309 for details.

**Comment by ssatyapal123** [comment]
Ted went over his additional hands-on testing with me modifying the Grant Controls in the Conditional Access Policies to include different combinations of authentication strengths. Hands-on testing confirmed that ProviderSettings.JSON captures the Authentication Strength used in conditional access policies.The conditional access JSON contains the specific methods that are configured for a strength, so the Rego can check those methods directly against whatever policy we want.
**Ted's test results are summarized below:**

**Policy: Phishing-resistant MFA SHALL be enforced for all users**. Although we currently have a baseline policy which contains this requirement, until Authentication Strength was released, we were not able to implement a ScubaGear check. . 
![image](https://github.com/cisagov/ScubaGear/assets/78565245/7fabc617-de96-4799-a8cf-0e2c515abc4c)
**Policy that includes the Microsoft Authenticator Passwordless phone sign-in option** and this shows up in the JSON as the value “deviceBasedPush”.
![image](https://github.com/cisagov/ScubaGear/assets/78565245/3a83efa3-7917-46af-a101-7cfde548d592)

**Policy referencing a “custom” authentication strength definition that allows FIDO2, CBA and Temporary Access Pass.**
![image](https://github.com/cisagov/ScubaGear/assets/78565245/dac89fdf-8361-491d-8fb1-62a313e6a4b5)


Policy from the “y2zj1” tenant referencing a custom authentication strength that only allows CBA.
![image](https://github.com/cisagov/ScubaGear/assets/78565245/db322e73-e7ef-465a-8496-5f6e2db61ccf)

**Policy: MFA SHALL be required for all users.** If we keep this policy, it will be as a backup in case the Rego does not find a conditional access policy in the tenant that requires Phishing-resistant MFA. So this check would only apply if an agency hasn’t migrated to full phishing-resistant MFA or Passwordless MFA. We currently have a Rego check for this – we would need to retest it and make sure it can co-exist with authentication strength.

![image](https://github.com/cisagov/ScubaGear/assets/78565245/c87b3b3d-0505-4de6-8c3c-da635aa1d444)
