### ISSUE TITLE
installation scripts not remote signed

### ISSUE THREAD

**Issue by Brjame** [cisagov/ScubaGear#800]
Some of the installation scripts are not remote signed and require unblock

setup.ps1 and requiredversions.ps1

**Comment by Brjame** [comment]
Scubagear v1.0.0 I believe.  The file I have in my downloads folder is named ScubeGear-main.zip

Thanks,

Brian J.

**Comment by Brjame** [comment]
I managed to get the correct versions but in github if you go to Code and Download Zip I was getting a version of "main" that did not have signed Powershell scripts.

Thanks,

Brian J.

**Comment by gdasher** [comment]
Thanks, glad you got the right version.  We'll look at making the docs more clear that you one should download a release vs a snapshot of main (which is effectively dev quality code).
