### ISSUE TITLE
unable to parse input: yaml: line 5697: did not find expected ',' or ']' - Exchange Online

### ISSUE THREAD

**Issue by VNerdIO** [cisagov/ScubaGear#807]
# 🐛 Summary #

What's wrong? Please be specific.
Get an exception while running for Exchange Online.

## To reproduce ##
Invoke-SCuBA -ProductNames exo -M365Environment gcc

## Expected behavior ##

I've used this for AAD, Defender, and Teams without issue. Expected to generate a report.

## Any helpful log output or screenshots ##

Paste the results here:

```
System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand","query_name":"_dmarc.XXXX"}
{"query_method":"DoH","query_result":"Query resulted in exception,
System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand","query_name":"_dmarc.XXXX"}
unable to parse input: yaml: line 5697: did not find expected ',' or ']'
Fatal Error involving the OPA output function.
            Ending ScubaGear execution. See the exception message for more details: Cannot bind argument to parameter 'InputObject' because it is
null.
At C:\Users\XXX\ScubaGear\PowerShell\ScubaGear\Modules\Orchestrator.psm1:651 char:13
+             throw $InvokeRegoErrorMessage
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Fatal Error inv...use it is null.:String) [], RuntimeException
    + FullyQualifiedErrorId : Fatal Error involving the OPA output function.
                Ending ScubaGear execution. See the exception message for more details: Cannot bind argument to parameter 'InputObject' because it i
   s null.
```

Add any screenshots of the problem here.
Line 5697 of ProviderSettingsExport.json seems to be the problem. Easy fix, but I'm not sure how to use the edited version when I run the script.
![Screenshot at Jan 17 13-22-11](https://github.com/cisagov/ScubaGear/assets/34196863/7910f090-a85d-49d5-9eba-e55b54eb548d)

**Comment by adhilto** [comment]
@VNerdIO, thanks for submitting this. I can confirm that you've identified a bug and am able to reproduce it myself.

You most likely have a transport rule with a condition ending with a `\` character. For example, I created a rule just now for testing that looks for messages containing a backslash.
![image](https://github.com/cisagov/ScubaGear/assets/106177711/1a99a487-877d-4a60-a9a2-772501d54f75)

Part of the processing ScubaGear does behind the scenes is strip out backslashes which were causing problems for Rego. That post-processing causes that rule to be rendered like so in the json:
![image](https://github.com/cisagov/ScubaGear/assets/106177711/664ea7f3-e12b-4bca-bc12-9ab3b5415601)

Up until now, we hadn't found a case where this broke anything, but there's obviously a bug we need to fix here. I suspect https://github.com/cisagov/ScubaGear/issues/770 is another instance of the same problem.

We'll work to get a fix out soon. Your options in the meantime:
- Modify the offending transport rule (only if doing so would have no adverse affect for your tenant)
- Use the `Invoke-RunCached` function.

As you mentioned above, it's easy enough to fix the json typo. But how to use the edited version when you run the script? Like so:

1. Run ` Invoke-RunCached -p exo -OutPath example`. The same error you ran into before will occur.
2. Open the ProviderSettingsExport.json file within the `example` folder and correct the json error. In my case, that meant changing `"'` to `""`.
3. Run `Invoke-RunCached -p exo -OutPath example -ExportProvider $false`. ScubaGear will run using the modified json file, allowing you to bypass the bug until we work out a fix.

**Comment by VNerdIO** [comment]
@adhilto, Thank you for the workaround. I was able to pull the report.
