### ISSUE TITLE
Power Platform Functional Release Testing

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#832]
# 💡 Summary #

As part of Flipper release, several Rego assessment components have been refactored.  To ensure that the tool's update is accurate, detailed functional testing has been planned. Each policy will be functionally tested to check that all pass/fail scenarios have been correctly processed by the tool using existing automated functional test plans.

This issue functionally tests each policy of the Power Platform baseline of ScubaGear tool. The main objective is to test Power Platform policies and ensure that ScubaGear tool is providing the correct result for each configuration option. 

## Motivation and context ##
This functional testing ensures that ScubaGear results of pass/fail are accurate based on the latest version of the code.

## Implementation notes ##
To perform functional testing, do the following:

- [ ] Configure the automated testing and run against each tenant type for which a variant testplan is present.  Run the automated test plans (e.g. regular, g5, etc.) and note the results.
- [ ] For each test failure, investigate and note the cause of the failure and log any new issues needed to resolve

For details on how to use and execute the functional tests, please see #592 or reach out to the dev team via other channels.

## Acceptance criteria ##

- [ ] All existing test plan variants for the product have been successfully run
- [ ] Testplan results have been reviewed and any issues resolved or reported as new issues

**Comment by nanda-katikaneni** [comment]
Ran ScubaGear on E5, G5, G3, GCCHigh tenants. Results are consistent with configs. Passed.

Ran Full Functional test suite (setting all possible compliant and non-compliant configs, running scubagear for each config and making sure that results are as expected) on E5 tenant in service principal and interactive modes. All tests went fine and results as expected. Passed.
