### ISSUE TITLE
SharePoint Online Functional Release Testing

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#833]
# 💡 Summary #

As part of Flipper release, several Rego assessment components have been refactored.  To ensure that the tool's update is accurate, detailed functional testing has been planned. Each policy will be functionally tested to check that all pass/fail scenarios have been correctly processed by the tool using existing automated functional test plans.

This issue functionally tests each policy of the SharePoint Online/OneDrive baseline of ScubaGear tool. The main objective is to test SharePoint and OneDrive policies and ensure that ScubaGear tool is providing the correct result for each configuration option. 

## Motivation and context ##
This functional testing ensures that ScubaGear results of pass/fail are accurate based on the latest version of the code.

## Implementation notes ##
To perform functional testing, do the following:

- [x] Configure the automated testing and run against each tenant type for which a variant testplan is present.  Run the automated test plans (e.g. regular, g5, etc.) and note the results.
- [x] For each test failure, investigate and note the cause of the failure and log any new issues needed to resolve

For details on how to use and execute the functional tests, please see #592 or reach out to the dev team via other channels.

## Acceptance criteria ##

- [x] All existing test plan variants for the product have been successfully run
- [x] Testplan results have been reviewed and any issues resolved or reported as new issues

**Comment by Dylan-MITRE** [comment]
## G5 -- Pass
<img width="811" alt="G5" src="https://github.com/cisagov/ScubaGear/assets/107067015/2bb8bc61-8f8e-47ae-a217-a1fb6157cece">
<img width="816" alt="G5SPO" src="https://github.com/cisagov/ScubaGear/assets/107067015/1c1738d7-b10c-4361-9c15-a7dcab800f5f">

## G3 -- Pass
<img width="816" alt="G3" src="https://github.com/cisagov/ScubaGear/assets/107067015/2c9c8a5e-81ae-44d0-a642-11b53696aa0c">

## E5 -- Pass
<img width="811" alt="E5 " src="https://github.com/cisagov/ScubaGear/assets/107067015/5a011555-7da9-4be1-a701-1fca1f8e1de8">

## GCC High -- Pass
<img width="816" alt="gcc high" src="https://github.com/cisagov/ScubaGear/assets/107067015/5727429b-21e7-4e3a-a842-3824f4c00da1">

Also did manual test on G5 tenant and everything work as expected.

**Comment by Dylan-MITRE** [comment]
@schrolla

**Comment by Dylan-MITRE** [comment]
Closing as testing was completed with no major issues.
