### ISSUE TITLE
Add docs on how to use ScubaConfig

### ISSUE THREAD

**Issue by twneale** [cisagov/ScubaGear#845]
# 🐛 Summary #

`ScubaConfig` is designed to function as a singleton, such that only a single instance of the class exists at any given time. Calling `[scubaconfig]::GetInstance()` repeatedly will always return the same instance. This has some potentially confusing and unexpected effects, such as the loaded configuration persisting for the life of the powershell process, even from within in other modules that subsequently import the ScubaConfig module, possibly expecting a newly created config object to be empty. It requires client code to aggressively manage the state of the ScubaConfig cached instance to avoid inadvertently pulling in configs from a prior usage. This has implications for tests, where its necessary to call `[scubaconfig]::ResetInstance()` before and after tests to avoid pulling in configs from a prior test or accidentally injecting configs into a subsequent test.

There was most likely a compelling reason to make this a singleton, but I think the benefits are outweighed by the potentially confusing results. It would be more idiomatic and straight forward to make ScubaConfig a normal instance that people create and throw away when it's done.

There is a question of how to do this without having to change everything. I would suggest keeping `GetInstance` as a staticmethod, but turn it into a normal constructor that accepts the path to the config file as a positional arg. It would load the config and return a new instance of a scubaconfig. If no config is given, to preserve backward compatibility maybe it could look for an environment variable SCUBA_CONFIG by default and load the file from that path. If none of above, maybe throw an error.

If the motivation was to make it easy to find the loaded `scubaconfig` without having to manually pass it around everywhere, I would probably suggest we call a spade a spade and just explicitly make it a global variable. Both these methods result in the config lingering around the shell session permanently after Scuba runs unless affirmatively removed, so cleanup actions are necessary with both.

## To reproduce ##

1. Run some tests: `invoke-pester -path ./PowerShell/ScubaGear/Testing/Unit/PowerShell/ScubaConfig/`
2. Import scubaconfig: `using module ./PowerShell/ScubaGear/Modules/ScubaConfig/ScubaConfig.psm1` 
3. The last configuration loaded during the tests is still in place: `[scubaconfig]::GetInstance().Configuration`

## Expected behavior ##

I expected `[scubaconfig]::GetInstance()` to return an empty config the first time after importing the scubaconfig module. It will return whatever the last used scubaconfig object was. The orchestrator avoids any problems by removing and reimporting the scubaconfig module before running  👍 and calling `[scubaconfig]::ResetInstance()` after running. This has to be done carefully in any tests that incorporate ScubaConfig so as to avoid state persisting between runs and unexpected things happening.

Output:
```
> [scubaconfig]::GetInstance().Configuration
Name                           Value
----                           -----
OutProviderFileName            ProviderSettingsExport
M365Environment                commercial
OutReportName                  BaselineReports
ProductNames                   {aad, defender, exo, onedrive…}
.
DisconnectOnExit               False
AnObject                       {[name, MyObjectName]}
OutRegoFileName                TestResults
Description                    JSON Configuration file for unit test in SCuBA
OPAPath                        /home/tneale/feat/pr782/PowerShell/ScubaGear/Modules/ScubaConfig/../../..
OutPath                        .
OutFolderName                  M365BaselineConformance
LogIn                          True
```

Happy to take this one if it would be helpful.

**Comment by crutchfield** [comment]
Recommend we have a discussion on this issue.  I believe the Singleton pattern is appropriate.

**Comment by twneale** [comment]
I'm ready to be wrong...I'll get some time on your calendar.

**Comment by twneale** [comment]
@crutchfield and I got together on this. I will send a PR with some docstrings explaining how to manage the ScubaConfig instance to avoid surprises related to the singleton design.
