### ISSUE TITLE
Resolve MS.DEFENDER.1.1v1 functional test errors

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#860]
# 🐛 Summary #

The automated functional testing in the G5 variant test plan appears to fail from some of the non-compliant test cases for MS.DEFENDER.1.1v1.  The issue appears to stem from a race condition or possibly inconsistent reporting of status when rapidly enabling/disabling policies.  Need to resolve in some way to better support functional testing.

## To reproduce ##

1. Setup and run the automated test orchestration framework for Defender against a G5 licensed tenant
2. Set the test to filter and run MS.DEFENDER.1.1v1 tests
3. Review the results for failed tests 

## Expected behavior ##

All tests should pass to indicated that the expected assessment results were generated for the given inputs.

**Comment by crutchfield** [comment]
@schrolla I wonder if placing a "Start-Sleep -Seconds 2" 
 as a post condition would help determine if it is a API calling rate issue.
