### ISSUE TITLE
PowerBi licenses need to be verified

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#87]
- M365 G5 is required for Power BI Pro. 
- Power BI Premium is available as an add-on to G5 and provides dedicated capacity-based BI, self-service data prep for big data, and simplification of data management and access at enterprise scale. 
- AAD P2 is needed for additional conditional access policy control (included with G5).

Can you verify the the first bullet is true? I see here you just need a Gov plan to get it. [Power BI for US government customers - Overview - Power BI | Microsoft Docs](https://docs.microsoft.com/en-us/power-bi/enterprise/service-govus-overview#buy-a-power-bi-pro-subscription-for-government-customers) But the docs are quite confusing.

Also can you clarify why AAD P2 is need for CA policies? P1 is needed for CA access. Is there something specific about the CA that requires P2?

**Comment by tkol2022** [comment]
> Also can you clarify why AAD P2 is need for CA policies? P1 is needed for CA access. Is there something specific about the CA that requires P2?

Yes, for "risk based" CA policies (e.g. the ones that deal with user risk which rely on AAD Identity Protection), those specific policies require P2. P2 is also required for PIM related policies.

**Comment by tkol2022** [comment]
@buidav Can you answer the licensing questions on PowerBI and opine on whether this issue can be closed after that? Thanks!

**Comment by amart241** [comment]
> Not the Power Bi expert but I took a look at this issue with Alex recently.
> 
> Looks like any language relating to AAD P2 has already been removed from the baseline itself. <img alt="powerBiLiscense" width="810" src="https://user-images.githubusercontent.com/105074908/238454432-4ac9d4c1-2700-4b79-8747-4b348dba55f8.PNG">
> 
> As for Power Bi Pro & Power BI Premium they don't seem to require a E5/G5.
> 
> Power Bi Pro is included by default in a E5/G5 license bundle. Power BI Premium is available as an upgrade to Power BI Pro. Both Licenses look like they can be purchased standalone [Power BI licensing](https://powerbi.microsoft.com/en-us/pricing/)
> 
> I would close out this issue and just make an issue to update the text here for clarification.

I am agreeing with David here. I think that E5/G5 is not required, and power BI Pro can be added on. It is included with the G5 license though.

I can edit the language to make that more clear
