### ISSUE TITLE
Research into naming scheme for unique policy IDs 

### ISSUE THREAD

**Issue by mitchelbaker-cisa** [cisagov/ScubaGear#876]
# 💡 Summary #

When creating the unique policy IDs, the team was assuming SCB changes would have to go through the months long publication process so we would only update the policies and version in “bulk”. As we move towards a more continuous update process, below are some thoughts on the matter:
* Should this variable be updated to policy version to allow flexibility to update the policy without “publishing” a new baseline version each time?
* Should we keep it as baseline version and for each release increase the number regardless of if policies have been updated.
* Should we only update the “last modified” date and remove the variable as a whole?
* Create a new ID for policy updates and note changes in a change log format?
* Any combination of the options listed above.

Vendor | Business   Application | Group   Number | Policy   Number | Baseline   Version
-- | -- | -- | -- | --
MS | TEAMS | 1 | 1 | 1

A few more questions to think about: 
* Should baseline documents have their own standalone version so that policies don't have to be updated in bulk? 
* Should the baseline version be kept as an integer, or would a SemVer number be more appropriate to mark a policy update as major/minor/patch?

## Motivation and context ##

Our goal is to release SCB updates at the same speed as the SaaS products we cover (Microsoft 365), as opposed to going  through the month long publication process for any SCB updates. Once we begin to make smaller and more frequent SCB updates it seems intuitive to rethink how we've structured the baseline versions. 

## Implementation notes ##

TBD 

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Determine if baseline documents should have their own standalone version, or continue to update baseline versions in bulk. 
- [ ] The policy ID is used as a reference in both the baselines and assessment tool, assess the scope of what either a modification to the current policy ID or a new ID would implicate.

**Comment by Jeff-Jerousek** [comment]
To make this framework extensible and useful to me I've started to split out all of the baselines and rego files.

For example MS.TEAMS.1.1.1 

Is now a folder under baselines (it may end up somewhere else) called MS.Teams, and then there is a folder called 1.1 with:

- 1.1.1.md
- 1.1.1 Instructions.md
- 1.1.1.rego
- 1.1.1_test.rego

Then I can combine all of the files to match the original baselines (teams.md and TeamsConfig.rego) with the ones I want removed, or new ones I've added myself.

**Comment by ahuynhMITRE** [comment]
Decisions from Mar 18th meeting:

- For the policy ID the version number will be updated to align to "Policy version number"
  - policy numbers will increment by "1", minor increments will not be used
 
- New markdown file will be added to M365 and GWS GitHub repositories to detail the following for removed policies:
    - Policy ID
    - Policy
    - rationale
    - modified date
    - SCB version where the removal occurred (exo.md v1.4.0)
 
 - If a control has been decided to become OBE from a SCB remove the the following sections for the policy:
    - Policy ID
    - Policy
    - rationale
    - last modified
    - note
    - any resources and license requirements aligned to the policy
    - implementation steps 
  
- SCB baselines will be also be incremented by "1" for any policy changes. Baseline version numbers will be tied to their individual baseline and not the release, policy version, or scubagear version.

- New issues to be added include:
  - Enhancement to the automation to pull baseline version number from the SCB. This will remove the current hardcoded baseline version number seen in the report.
  - Creation of a "OBE" or Discontinued policies markdown detailing some of the information shared above.
  - Determine and create a location for these markdown "rules"
