### ISSUE TITLE
Update Purview Premium assesment to check status for all users

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#88]
# 💡 Summary #

Recap of this issue where we discovered the advanced audit log for the UAL (renamed to Purview Premium) is enabled on a per-user basis. Each user must also be assigned at minimum a E5/G5 license. Currently in the baseline policy we have 'advanced audit logging SHALL be enabled`. OMB M-21-31, as noted in the baseline policy, also requires that advanced audit logging be turned on. #308 covers the same topic in the SharePoint baseline.

Reposting several points made from the previous issues:

What are the the cons:
- Requires looping through all the users in both the GUI AND the command-line to enable
- Requires each user to be assigned an E5/G5 license or a special add-on license.

What are the benefits:
- [Provides access to EXO and SharePoint events in the UAL that are useful for IR](https://learn.microsoft.com/en-us/microsoft-365/compliance/audit-premium?view=o365-worldwide#audit-premium-events)

## Questions to CISA ##

- Do we relegate this policy to a SHOULD?  (Answer:  No, it remains a SHALL.  Related additional specific audit items remain a SHOULD.)
- Is there another path forward for this policy?
--------------------------------------------------------------------------
(Initial Issue text)
Follow-up to issue #200, where we discovered that advanced audit is enabled on a per-user basis not tenant-wide (TLRD: we decided to not implement the rego check for the alpha but to reassess the requirement for the MVP).

The cons of advanced audit are pretty self-evident now.
- Requires looping through all the users in both the GUI AND the command-line to enable (Workaround possible)
- Requires each user to be assigned an E5/G5 license or a special add-on license (Still true)

What are the benefits? Do they outweigh the cons?

Since this issue was originally created, Microsoft has indicated a change to which events are going to be made available as part of Purview Standard vs Purview Premium.  As a result, a careful review of individual audit items needs to be done to determine what specific audit items should be included in the baseline.  Regardless, advanced audit (Premium) checks are still desirable.

**Comment by gdasher** [comment]
My initial sense is that we demote to a should for now given the tradeoffs.

**Comment by gdasher** [comment]
I believe its no worse than the status quo situation.  We have several policies that can't be easily assessed automatically.  This one is particularly egregious though and hard for agencies to implement if they aren't in a position to script it.

Ok, on re-evaluating, I'm ok with removing this one from the baselines until/unless Microsoft adds a tenant level setting to enable.

**Comment by gdasher** [comment]
I think the action is to remove this from the baseline, right?  I'm not tracking if its there or not.
