### ISSUE TITLE
Non-Applicable policies should not generate warnings.

### ISSUE THREAD

**Issue by Jeff-Jerousek** [cisagov/ScubaGear#892]
# 🐛 Summary #

What's wrong? Please be specific.

MS.SHAREPOINT.3.2v1

Generates a warning when both file types are set to 2 and input.OneDrive_PnP_Flag == false

## To reproduce ##

1. Set     
        TenantPolicy.FileAnonymousLinkType = 2
        FolderAnonymousLinkType = 2
        OneDrive_PnP_Flag == false

1. Then this
Run SCUBA

## Expected behavior ##
No warning as policy is not applicable

What did you expect to happen that didn't?
A warning was generated.

## Any helpful log output or screenshots ##

Requirement not met: both files and folders are not limited to view for Anyone

**Comment by tkol2022** [comment]
Hello @Jeff-Jerousek 
Can you please clarify, "No warning as policy is not applicable". Specifically why do you consider the policy as being not applicable in your case? Did you set the **Files** and **Folders** permissions for **Anyone links** to **View**?

Currently the policy is coded to show a Pass when the following is configured in the Sharepoint admin portal under **Choose expiration and permissions options for Anyone links**.
Files: View which corresponds to FileAnonymousLinkType = 1
Folders: View which corresponds to FolderAnonymousLinkType = 1

![image](https://github.com/cisagov/ScubaGear/assets/107076927/4d5452e7-6e6b-4275-901a-f0db35f8991d)

**Comment by Jeff-Jerousek** [comment]
@tkol2022 I think @schrolla covers it in https://github.com/cisagov/ScubaGear/issues/951 specifically, the comment in the rego file.

I would also note that we don't use anyone links, we have external sharing turned off, so we don't have expiration turned on. Maybe this shouldn't even be evaluated in that case?

**Comment by tkol2022** [comment]
Thanks. It sounds like the fix for #951 will address the problem you are having. We appreciate you feedback and I will ping you when the fix is ready so that you can validate as well. 

To answer your question, yes, when the external sharing slider is set to certain values (like external sharing off), numerous policies like the ones related to Anyone links become not-applicable and should not be evaluated.
