### ISSUE TITLE
Revise SPF Requirements

### ISSUE THREAD

**Issue by adhilto** [cisagov/ScubaGear#900]
# 💡 Summary #
- Delete MS.EXO.2.1v1
- Revise MS.EXO.2.2v1 to “An SPF policy SHALL be published for each domain that fails all non-approved senders.”

## Motivation and context ##
- Maintaining a list is not configuration item (more of a prerequisite)
- There was some confusion about what to do with the list once you have it.
- Also some confusion about IP vs domains (e.g., `include:spf.protection.outlook.com`).
- "only these" is ambiguous
- Explicitly spell out that non-approved senders should fail

## Implementation notes ##
See https://github.com/cisagov/ScubaGear/issues/857 for a related technical issue.

## Acceptance criteria ##
- [ ] The baseline is revised
- [ ] The Rego is updated to reflect the change

**Comment by adhilto** [comment]
See https://github.com/cisagov/ScubaGoggles/pull/188 for this change which has already been made in the Gmail baseline.

**Comment by isab-m** [comment]
Issue handoff 4/16, I was able to complete: 

- Deletion of MS.EXO.2.1v1 baseline markdown
- Deletion of MS.EXO.2.1v1 rego test
- Revision of MS.EXO.2.2v1 baseline markdown
- Revision of MS.EXO2.2v1 rego test/policy name to MS.EXO.2.1v1
- Add test for SPF redirection 

Still needs:
- Rest of test cases for SPF redirection

Used https://github.com/cisagov/ScubaGoggles/pull/188 for referencing the changes needed for this issue
