### ISSUE TITLE
AAD module generates an error at launch

### ISSUE THREAD

**Issue by houstek** [cisagov/ScubaGear#903]
# 🐛 Summary #

The AAD module generates an error at launch. All prerequisites are correct.

## To reproduce ##

Invoke-SCuBA -ProductNames aad -Verbose

## Any helpful log output or screenshots ##
PS C:\temp\ScubaGear-1.1.0> Invoke-SCuBA -ProductNames aad -Verbose
COMMENTAIRES : Suppression de la fonction importée « Select-DohServer ».
COMMENTAIRES : Suppression de la fonction importée « Get-ScubaDmarcRecord ».
COMMENTAIRES : Suppression de la fonction importée « Invoke-RobustDnsTxt ».
COMMENTAIRES : Suppression de la fonction importée « Get-ScubaSpfRecord ».
COMMENTAIRES : Suppression de la fonction importée « Get-ScubaDkimRecord ».
COMMENTAIRES : Suppression de la fonction importée « Get-EXOTenantDetail ».
COMMENTAIRES : Suppression de la fonction importée « Export-EXOProvider ».
COMMENTAIRES : Suppression de la fonction importée « Get-PrivilegedUser ».
COMMENTAIRES : Suppression de la fonction importée « Get-PrivilegedRole ».
COMMENTAIRES : Suppression de la fonction importée « Get-AADTenantDetail ».
COMMENTAIRES : Suppression de la fonction importée « Export-AADProvider ».
COMMENTAIRES : Suppression de la fonction importée « Export-DefenderProvider ».
COMMENTAIRES : Suppression de la fonction importée « Get-TeamsTenantDetail ».
COMMENTAIRES : Suppression de la fonction importée « Export-TeamsProvider ».
COMMENTAIRES : Suppression de la fonction importée « Export-SharePointProvider ».
COMMENTAIRES : Suppression de la fonction importée « Invoke-Rego ».
COMMENTAIRES : Suppression de la fonction importée « New-Report ».
COMMENTAIRES : Suppression de la fonction importée « Import-SecureBaseline ».
COMMENTAIRES : Suppression de la fonction importée « Disconnect-SCuBATenant ».
COMMENTAIRES : Suppression de la fonction importée « Connect-Tenant ».
COMMENTAIRES : Chargement du module à partir du chemin
« C:\temp\ScubaGear-1.1.0\PowerShell\ScubaGear\Modules\Providers\ExportAADProvider.psm1 ».
COMMENTAIRES : Exportation de la fonction « Export-AADProvider ».
COMMENTAIRES : Exportation de la fonction « Get-AADTenantDetail ».
COMMENTAIRES : Exportation de la fonction « Get-PrivilegedUser ».
COMMENTAIRES : Exportation de la fonction « Get-PrivilegedRole ».
COMMENTAIRES : Importation de la fonction « Export-AADProvider ».
COMMENTAIRES : Importation de la fonction « Get-AADTenantDetail ».
COMMENTAIRES : Importation de la fonction « Get-PrivilegedRole ».
COMMENTAIRES : Importation de la fonction « Get-PrivilegedUser ».
COMMENTAIRES : Chargement du module à partir du chemin
« C:\temp\ScubaGear-1.1.0\PowerShell\ScubaGear\Modules\Providers\ExportDefenderProvider.psm1 ».
COMMENTAIRES : Exportation de la fonction « Export-DefenderProvider ».
COMMENTAIRES : Importation de la fonction « Export-DefenderProvider ».
COMMENTAIRES : Chargement du module à partir du chemin
« C:\temp\ScubaGear-1.1.0\PowerShell\ScubaGear\Modules\Providers\ExportEXOProvider.psm1 ».
COMMENTAIRES : Exportation de la fonction « Export-EXOProvider ».
COMMENTAIRES : Exportation de la fonction « Get-EXOTenantDetail ».
COMMENTAIRES : Exportation de la fonction « Select-DohServer ».
COMMENTAIRES : Exportation de la fonction « Invoke-RobustDnsTxt ».
COMMENTAIRES : Exportation de la fonction « Get-ScubaSpfRecord ».
COMMENTAIRES : Exportation de la fonction « Get-ScubaDkimRecord ».
COMMENTAIRES : Exportation de la fonction « Get-ScubaDmarcRecord ».
COMMENTAIRES : Importation de la fonction « Export-EXOProvider ».
COMMENTAIRES : Importation de la fonction « Get-EXOTenantDetail ».
COMMENTAIRES : Importation de la fonction « Get-ScubaDkimRecord ».
COMMENTAIRES : Importation de la fonction « Get-ScubaDmarcRecord ».
COMMENTAIRES : Importation de la fonction « Get-ScubaSpfRecord ».
COMMENTAIRES : Importation de la fonction « Invoke-RobustDnsTxt ».
COMMENTAIRES : Importation de la fonction « Select-DohServer ».                                                         COMMENTAIRES : Importation de la fonction « Export-PowerPlatformProvider ».                                             COMMENTAIRES : Importation de la fonction « Get-PowerPlatformTenantDetail ».                                            COMMENTAIRES : Chargement du module à partir du chemin                                                                  « C:\temp\ScubaGear-1.1.0\PowerShell\ScubaGear\Modules\Providers\ExportSharePointProvider.psm1 ».                       COMMENTAIRES : Exportation de la fonction « Export-SharePointProvider ».
COMMENTAIRES : Importation de la fonction « Export-SharePointProvider ».
COMMENTAIRES : Chargement du module à partir du chemin
« C:\temp\ScubaGear-1.1.0\PowerShell\ScubaGear\Modules\Providers\ExportTeamsProvider.psm1 ».
COMMENTAIRES : Exportation de la fonction « Export-TeamsProvider ».
COMMENTAIRES : Exportation de la fonction « Get-TeamsTenantDetail ».
COMMENTAIRES : Importation de la fonction « Export-TeamsProvider ».
COMMENTAIRES : Importation de la fonction « Get-TeamsTenantDetail ».
COMMENTAIRES : Chargement du module à partir du chemin
« C:\temp\ScubaGear-1.1.0\PowerShell\ScubaGear\Modules\Connection\Connection.psm1 ».
COMMENTAIRES : Importation de la fonction « Connect-Tenant ».
COMMENTAIRES : Importation de la fonction « Disconnect-SCuBATenant ».
COMMENTAIRES : Chargement du module à partir du chemin
« C:\temp\ScubaGear-1.1.0\PowerShell\ScubaGear\Modules\RunRego\RunRego.psm1 ».
COMMENTAIRES : Importation de la fonction « Invoke-Rego ».
COMMENTAIRES : Chargement du module à partir du chemin
« C:\temp\ScubaGear-1.1.0\PowerShell\ScubaGear\Modules\CreateReport\CreateReport.psm1 ».
COMMENTAIRES : Importation de la fonction « Import-SecureBaseline ».
COMMENTAIRES : Importation de la fonction « New-Report ».
COMMENTAIRES : Chargement du module à partir du chemin
« C:\temp\ScubaGear-1.1.0\PowerShell\ScubaGear\Modules\ScubaConfig\ScubaConfig.psm1 ».
COMMENTAIRES : Importation de la fonction « Copy-ScubaBaselineDocument ».
Fatal Error involving the Report Creation.
            Ending ScubaGear execution. See the exception message for more details: Objet non valide passé, ':' ou '}'
attendu. (677065):         {
                "baseline_version": "1",
                "module_version": "1.1.0",
                "date": "02/10/2024 05:38:58 Paris, Madrid",
                "tenant_details": [
    {
        "AADAdditionalData":  {
                                  "AssignedPlans":  [
                                                        {
                                                            "AssignedDateTime":  "Date(1707461129000)",
                                                            "CapabilityStatus":  "Suspended",
                                                            "Service":  "MicrosoftCommunicationsOnline",
![2024-02-10_05-49](https://github.com/cisagov/ScubaGear/assets/16977281/340cc03c-c93f-40a7-a20d-c98bb41fb329)

Add any screenshots of the problem here.

**Comment by fariaz** [comment]
Hi,

Same issue for me i tried with powershell 5.1 and 7.

Br

**Comment by houstek** [comment]
Is that enough for you? 


Fatal Error involving the Report Creation.
            Ending ScubaGear execution. See the exception message for more details: Objet non valide passé, ':' ou '}' attendu. (677065):         {
                "baseline_version": "1",
                "module_version": "1.1.0",
                "date": "02/12/2024 20:53:11 Paris, Madrid",
                "tenant_details": [
    {
        "AADAdditionalData":  {
                                  "AssignedPlans":  [
                                                        {
                                                            "AssignedDateTime":  "Date(1707461129000)",
                                                            "CapabilityStatus":  "Suspended",
                                                            "Service":  "MicrosoftCommunicationsOnline",
                                                            "ServicePlanId":  "42a3ec34-28ba-46b6-992f-db53a675ac5b"
                                                        },
                                                        {
                                                            "AssignedDateTime":  "Date(1705477222000)",
                                                            "CapabilityStatus":  "Enabled",
                                                            "Service":  "TeamspaceAPI",
                                                            "ServicePlanId":  "ec17f317-f4bc-451e-b2da-0167e5c260f9"
                                                        },
                                                        {
                                                            "AssignedDateTime":  "Date(1705477222000)",
                                                            "CapabilityStatus":  "Enabled",
                                                            "Service":  "TeamspaceAPI",
                                                            "ServicePlanId":  "0374d34c-6be4-4dbb-b3f0-26105db0b28a"
                                                        },

**Comment by houstek** [comment]
I attach an overview of the file ProviderSettingsExport.json
I do indeed have non-alphanumeric characters in the names of the conditional access policies. I have: "é" "=" ">" "," "_" "(" ")"

![2024-02-12_22-10](https://github.com/cisagov/ScubaGear/assets/16977281/c36009eb-87fd-45f2-9712-9537200948e7)

**Comment by houstek** [comment]
With the Graph module in version 2.12, the script works perfectly :)
