### ISSUE TITLE
Unable to generate report

### ISSUE THREAD

**Issue by OlivierBla** [cisagov/ScubaGear#904]
Hello, 
I executed setup.ps1 and all modules was installed.
When starting Invoke-Scuba, after signing and execution code, the console show many errors (i think it's when to generate the HTML report)

   "ExceptIfSubjectOrBodyContainsWords":  [
                                               ],
        "DocumentMatchesPatterns":  [
                                    ],
        "ExceptIfDocumentMatchesPatterns":  [
                                            ],
        "DocumentContainsWords":  [
                                  ],
        "ExceptIfDocumentContainsWords":  [
                                          ],
        "SenderADAttributeMatchesPatterns":  null,
        "ExceptIfSenderADAttributeMatchesPatterns":  null,
        "SenderADAttributeContainsWords":  null,
        "ExceptIfSenderADAttributeContainsWords":  null,
        "RecipientADAttributeMatchesPatterns":  null,
        "ExceptIfRecipientADAttributeMatchesPatterns":  null,
        "RecipientADAttributeContainsWords":  null,
        "ExceptIfRecipientADAttributeContainsWords":  null,
        "ContentCharacterSetContainsWords":  [
                                             ],
        "ExceptIfContentCharacterSetContainsWords":  [
                                                     ],
        "DocumentNameMatchesPatterns":  [
                                        ],
        "ExceptIfDocumentNameMatchesPatterns":  [
                                                ],
        "MessageSizeOver":  "",
        "ExceptIfMessageSizeOver":  "",
        "MessageTypeMatches":  null,
        "ExceptIfMessageTypeMatches":  null,
        "UnscannableDocumentExtensionIs":  [
                                           ],
        "ExceptIfUnscannableDocumentExtensionIs":  [
                                                   ],

  },
    {
        "Description":  null,
        "AllowBroadcastScheduling":  true,
        "AllowBroadcastTranscription":  false,
        "BroadcastAttendeeVisibilityMode":  "EveryoneInCompany",
        "BroadcastRecordingMode":  "AlwaysEnabled",
        "DataSource":  "Memory",
        "Key":  {
                    "ScopeClass":  "Tag",
                    "SchemaId":  "XName=",
                    "AuthorityId":  "Class=Host;InstanceId=00000000-0000-0000-0000-000000000000;XmlRoot=",
                        "DefaultXml":  "SchemaId=;Data=;ConfigObject=;Signature=00000000-0000-0000-0000-000000000000;I
   sModified=True",
                    "XmlRoot":  "name={urn:schema:Microsoft.Rtc.Management.ScopeFramework.2008}AnchoredXmlKey"
                },
        "Identity":  "Tag:Default",
        "ConfigMetadata":  {
                               "Authority":  "Host"
                           }
    }
],
    "teams_successful_commands": [
    "Get-CsTenant",
    "Get-CsTeamsMeetingPolicy",
    "Get-CsTenantFederationConfiguration",
    "Get-CsTeamsClientConfiguration",
    "Get-CsTeamsAppPermissionPolicy",
    "Get-CsTeamsMeetingBroadcastPolicy"
],
    "teams_unsuccessful_commands": [
]
        }

**Comment by OlivierBla** [comment]
Hello to complete the investigations : 
- I ran Invoke-SCuba -OutPath .\reports 
         of course .\reports is in my main directory folder
In this folder (at the end of Invoke-ScuBa execution with many errors), i can found files and folder : 
- ProviderSettingsExport.json
- TestResults.csv
- TestResults.json
- IndividualReports -> (Folder)

but no HTML file locate on reports folder.

Thanks

**Comment by joostgrunwald** [comment]
I had the same problem

**Comment by KillerRyuk** [comment]
Same.  Here is the error that happens.  PS C:\Users\[$USER]\Downloads\ScubaGear-main\ScubaGear-main> Invoke-SCuBA -productnames aad
Fatal Error involving the Report Creation.
            Ending ScubaGear execution. See the exception message for more details: Invalid object passed in, ':' or '}' expected. (572882):         {
                "baseline_version": "1",
                "module_version": "1.1.0",
                "date": "02/12/2024 14:48:38 Central Standard Time",
                "tenant_details": [
    {

**Comment by OlivierBla** [comment]
Thanks Schrolla  for your answer.
However, i follow your instructions but different error, when i replace RequiredVersions.ps1, and after uninstall and reinstall scuba, i have the following error when running powershell command to load the scuba module :  import-module -Name .\PowerShell\Scubagear

Import-Module : No acceptable installed version found for module: Microsoft.Graph.Beta.Users
        Required Min Version: 2.0.0 | Max Version: 2.12.0
        Run Get-InstalledModule to see a list of currently installed modules
        Run SetUp.ps1 or Install-Module Microsoft.Graph.Beta.Users -Force -MaximumVersion 2.12.0 to install the latest
acceptable version of Microsoft.Graph.Beta.Users
Au caractère Ligne:1 : 1
+ Import-Module .\PowerShell\ScubaGear
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : No acceptable installed version found for module: Microsoft.Graph.Beta.Users
        Required Min Version: 2.0.0 | Max Version: 2.12.0
        Run Get-InstalledModule to see a list of currently installed modules                                                        Run SetUp.ps1 or Install-Module Microsoft.Graph.Beta.Users -Force -MaximumVersion 2.12.0 to install the la     test acceptable version of Microsoft.Graph.Beta.Users,Microsoft.PowerShell.Commands.ImportModuleCommand
