### ISSUE TITLE
AAD - Incorrectly passes test when match policy has unchecked conditions that limit scope

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#92]
AAD 2.1 requires that legacy authentication be blocked.  The implementation guidance requires creating and enabling a conditional access policy that blocks the ActiveSync and Other client app types for all users and apps.  The test, however, does not ensure that additional policy conditions that may restrict the policy scope are not set.  As such, the test may incorrectly note that the baseline item has been satisfied when the actual policy in place is too narrow to fully meet the baseline requirement.

This was tested by adjusting the CISA test tenant policy, "Live - Legacy Authentication SHALL be Blocked", which originally met AAD 2.1 requirements by adding a condition that required that the device platform be Linux.  As such, the policy would NOT block legacy authentication for non-Linux (or unidentified) client types.  This additional condition significantly alters the policy such that it no longer meets the intent of AAD 2.1 as a significant number of clients might still use legacy authentication.  However, running the SCuBA orchestrator showed that AAD 2.1 still passed after the policy change.

Recommend updating the AAD 2.1 policy test to account for and check these additional conditions to ensure that a matching policy is not overly narrow in scope.

**Comment by tkol2022** [comment]
Is this bug specific to policy 2.1 or does this affect all AAD policies that rely on conditional access?

If this affects all CA policies, should the scope of this fix include the programming correction for the other AAD policy checks as well?

**Comment by tkol2022** [comment]
@schrolla Agree. Since #316 is a specific manifestation of this problem, should we close that one as well?

Also, I placed an "Urgent" priority on #86 because #316 indicates that this affected the pilots.

**Comment by adhilto** [comment]
I'm on-board with closing this issue.

**Comment by adhilto** [comment]
Closing per conversation in today's standup
