### ISSUE TITLE
Update AAD baseline references from Azure AD to Microsoft Entra ID

### ISSUE THREAD

**Issue by tkol2022** [cisagov/ScubaGear#921]
# 💡 Summary #

To stay aligned with Microsoft's product updates, we need to update the AAD baseline to call the product "Microsoft Entra ID". The scope of the changes for this issue is constrained to:

- Baseline prose updates
- Update HTML report display name

Changes to the source code are scoped to other issues.

**Comment by tkol2022** [comment]
When changing references to Microsoft Entra ID, we need to be sure the related service names such as "Conditional Access" are also updated to Microsoft's new name. I found out that the new name for that service is Microsoft Entra Conditional Access, not Microsoft Entra ID Conditional Access. Thanks @jsfirey for the attention to detail on this topic.

![image](https://github.com/cisagov/ScubaGear/assets/107076927/68097ec5-024d-473e-beb9-ed9fdce8f08e)

**Comment by worldsdream** [comment]
@tkol2022 You can check the naming in the table:

https://learn.microsoft.com/en-us/entra/fundamentals/new-name#glossary-of-updated-terminology

For example:

Before:

- Azure AD multifactor authentication (MFA)
- Azure Active Directory multifactor authentication (MFA)

After:

- Microsoft Entra multifactor authentication (MFA)

**Comment by tkol2022** [comment]
> @tkol2022 You can check the naming in the table:
> 
> https://learn.microsoft.com/en-us/entra/fundamentals/new-name#glossary-of-updated-terminology
> 
> For example:
> 
> Before:
> 
> * Azure AD multifactor authentication (MFA)
> * Azure Active Directory multifactor authentication (MFA)
> 
> After:
> 
> * Microsoft Entra multifactor authentication (MFA)

big thanks
