### ISSUE TITLE
Run SetUp.ps1 and it tells it installs modules but it doesn't

### ISSUE THREAD

**Issue by worldsdream** [cisagov/ScubaGear#923]
# 🐛 Summary #

## To reproduce ##

Run the SetUp.ps1, and it shows:

![image1](https://github.com/cisagov/ScubaGear/assets/12443285/64edef9c-1a70-4715-856f-6f9b40715d87)

When going to the Windows PowerShell modules folder > all modules are installed.

## Expected behavior ##

It should install the modules, and show the module version in the output.

## Any helpful log output or screenshots ##

PowerShell 5.1
Unrestricted execution policy

![info](https://github.com/cisagov/ScubaGear/assets/12443285/ac127e07-d0dd-4584-978a-728037580585)

**Comment by crutchfield** [comment]
Perhaps we can have a conversation about developing a pre-check to look for issues users encounter based on known issues.

**Comment by worldsdream** [comment]
@schrolla Thanks for the explanation.

It works on another Windows Server 2022 (so that should not be the problem).

I installed the modules manually and that worked. For me, that's okay. But it would have been nice to force the download. Because why can I do it manually and not through the script...

**Comment by wingcomm** [comment]
This seems to be a bug in PowerShell with the Sharepoint Module. None of the suggested workarounds here or that I have found elsewhere found seem to resolve this issue. I'm seeing it on all of my systems where I have PowerShell 7 installed.

**Comment by wingcomm** [comment]
@schrolla I cloned a new Base Windows 10 VM and its running fine but we're getting some other errors, I'll open a separate issue.

**Comment by icnee** [comment]
i have just downloaded the file and i am using it for the first time but the file of setup.ps1 is missing can anyone help me out with this ?
