### ISSUE TITLE
Test and update MS Graph PowerShell SDK module - v2.15.0

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#930]
# 💡 Summary #

Dependent module msgraph-sdk-powershell has released a new version v2.15.0 with a number of bug fixes.  Test the new version for compatibility with ScubaGear and update compatible versions based on the results.

## Motivation and context ##

The MS Graph SDK is used for interacting with several M365 services.  The previous version (2.13.0-2.14.1) contained a bug that made it incompatible with ScubaGear.  This new version is supposed to resolve that bug.  Updating the versions supported by ScubaGear will make sure it has the latest available features and capabilities for querying M365 services.

## Implementation notes ##

Please provide details for implementation, such as:

- Remove existing versions of Microsoft.Graph.* modules from the test system
- Update RequiredVersions.ps1 max version to v2.15.0 (or latest)
- Run ScubaGear functional tests against multiple tenants and products and validate results
- If new version works, issue PR to update max version in RequiredVersion.ps1

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Compatibility of latest Microsoft.Graph.* modules with ScubaGear has been determined
- [ ] If compatible, PR with updated max version has been merged into ScubaGear

**Comment by BohrenAn** [comment]
The Microsoft.Graph and Microsoft.Graph.Beta Modules are updated about every two weeks.
I don't think it's useful to limit it to 2.15.0

I propose to set it to (pass unless a new major Version is released)
MaximumVersion = [version] '2.99.99999'

Kind Regards
Andres

**Comment by crutchfield** [comment]
I tend to agree with implementing version to 2.99.9999 since that was my initial implementation.  However, until we implement better mechanisms to rapidly detect and address breaking module changes I am going with pin major and minor  and let the patch float.  We can address further in the future.
