### ISSUE TITLE
some baseline policies in ScubaGear report have incorrect criticality values

### ISSUE THREAD

**Issue by tkol2022** [cisagov/ScubaGear#949]
# 💡 Summary #

Some of the criticality values displayed in the Sharepoint report were found to be inconsistent with the secure baseline document. The scope of this issue is to correct these in Sharepoint and examine / correct other baselines.

## Screenshot examples ##

![image](https://github.com/cisagov/ScubaGear/assets/107076927/7f04ef56-50a1-436e-9106-737df5a47418)

![image](https://github.com/cisagov/ScubaGear/assets/107076927/533328db-0396-4e14-834f-28d9e3852dcf)

## Implementation notes ##

- [ ] Review each of the policies in the Sharepoint Rego and compare their criticality values with the baseline document. Modify the Rego criticalities to align with the baselines wherever discrepancies are found.
- [ ] Repeat this process for all other baselines (AAD, Defender, etc.)

**Comment by crutchfield** [comment]
@tkol2022 Does the assumption hold that the secure baseline documents policy verbiage is authoritative?  This is to mean if policy MS.SHAREPOINT.x.y.vz says "The blah, blah, blah SHALL do blah" then the correct criticality is SHALL.

**Comment by tkol2022** [comment]
Affirmative.
