### ISSUE TITLE
Investigate Using Service principal for Authentication to each of the M365 products

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#96]
### Overview
Perform a hands-on investigation to determine which of the M365 products (AAD, Defender, etc.) can authenticate using a service principal instead of an interactive user login. The overall goal is to enhance the ScubaGear tool to support service principals for pipelines and other unattended tool execution use cases.

### Scope

- [ ] Create a service principal (application) in Azure AD that will be used as the identity to authenticate to the products

Perform these steps for each of the 7 products that the tool audits (AAD, Defender, EXO, Teams, OneDrive, Sharepoint, PowerPlatform).

- [ ] Review the product documentation for the authentication Cmdlet and determine if it supports client certificates and/or client secrets
- [ ] Setup the certificate or secret in Azure AD
- [ ] Try authenticating to the product using the service principal and document any problems
- [ ] Run the Cmdlets that are used in the respective ScubaGear provider script and make sure they work

- [ ] Create a spreadsheet that contains the details of the investigation

**Comment by albandrod** [comment]
it works! but it still throw some errors in Defender & Teams

![image](https://user-images.githubusercontent.com/39189511/225616361-8ae74ca4-cfd6-460f-95da-76afca1d0177.png)
