### ISSUE TITLE
MS Graph connection missing scope, RoleManagementPolicy.Read.AzureADGroup

### ISSUE THREAD

**Issue by crutchfield** [cisagov/ScubaGear#975]
# 🐛 Summary #

To support getting privileged role data Scuba users (including service principals) need elevated privileges.  

## To reproduce ##

1. Run nightly product tests. 

## Expected behavior ##

Expected aad tests to pass, failed due to lack of privileges

**Comment by tkol2022** [comment]
@schrolla  the branch created for this https://github.com/cisagov/ScubaGear/tree/975-ms-graph-connection-missing-scope-rolemanagementpolicyreadazureadgroup is probably not going to be needed because I fixed the problem in PR #945. Just FYI.
