### ISSUE TITLE
Enhance ScubaGear AAD report by clarifying how conditional access policy exclusions work

### ISSUE THREAD

**Issue by tkol2022** [cisagov/ScubaGear#985]
# 💡 Summary #

This issue is meant to improve how we communicate conditional access policy user/group exclusions to users in ScubaGear. We received [feedback from a user in another issue](https://github.com/cisagov/ScubaGear/issues/941) that they did not understand why their configuration was failing the policy check for AAD 1.1 even though they were following the configuration instructions. **The user was not aware of config file CA policy exclusions**.

Currently the AAD report has a note at the top of the page that mentions CA policy exclusions, but it does not appear to be designed to help users setup exclusions via the config file when they need to, therefore this issue is focused on helping the users do so.

## Motivation and context ##

Users can get clear instructions on how exclusions work and how to set them up so that they pass the policy checks, assuming their configuration is compliant with Scuba.

## Implementation notes ##

- [ ] Determine how the message at the top of the AAD report should be modified and adjust it. Screenshot of the current message for reference is below. Add a link to the [ScubaGear README exclusions section](https://github.com/cisagov/ScubaGear?tab=readme-ov-file#aad-conditional-access-policy-exemptions) so that users can follow the steps to setup their config file with exclusions when needed. 
- [x] Augment the README exclusions sections to make it clear that exclusions should only be used when an organization has performed a formal risk acceptance of the excluded accounts via their risk management process.
- [ ] Perform the HTML update that Mitchel described in his comment attached to this issue.

![image](https://github.com/cisagov/ScubaGear/assets/107076927/ab81bdcb-14dc-4eb0-aa05-68fa2bd58200)

**Comment by mitchelbaker-cisa** [comment]
We have a nested  \<p> tag ("Note: Conditional Access (CA).." text) within an \<h4> tag here which fails [guideline 2.4.6](https://www.w3.org/WAI/WCAG22/Understanding/headings-and-labels). If we keep this text then the \<p> should be removed and the \<h4> should be modified.

**Comment by tkol2022** [comment]
@dagarwal-mitre Please replace the existing Note paragraph at the top of the AAD baseline report with the revised paragraph below:

Note: Several of the policies in this baseline allow you to define specific user accounts that will be excluded from the assessment checks via a configuration file. Please reference [this section in the README file](https://github.com/cisagov/ScubaGear/LINK_GOES_HERE) if you need instructions on setting up exclusions. These types of account exclusions must only be used if they are approved within an organization's security risk acceptance process. **Exclusions can introduce grave risks to your system**.
