### ISSUE TITLE
Rego Test cases are duplicated

### ISSUE THREAD

**Issue by adhilto** [cisagov/ScubaGear#99]
Problem: the Rego test cases are stored in both of these locations:
- Testing/**/*.rego
- Testing/Unit/Rego/**/*.rego

I suspect the test cases were copied from the old location (Testing/**/*.rego) and were never deleted. Should be a quick fix, we just need to delete the old files. `RunUnitTests.ps1` and the Github action have both already been updated to use the new location.

Action:
Delete all sub-folders from the Testing folder except for those under the Unit folder.

**Comment by gdasher** [comment]
This might be another artifact of how ethan did the merge.  Yes, we should just clean this up.
